# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model\gatewayUploadDialog_UI.ui'
#
# Created: Tue Aug 04 10:17:38 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_gatewayUploadDialog(object):
    def setupUi(self, gatewayUploadDialog):
        gatewayUploadDialog.setObjectName("gatewayUploadDialog")
        gatewayUploadDialog.resize(495, 631)
        gatewayUploadDialog.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(gatewayUploadDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(gatewayUploadDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(gatewayUploadDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(gatewayUploadDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sinterConfigGUIButton = QtGui.QPushButton(gatewayUploadDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sinterConfigGUIButton.setIcon(icon)
        self.sinterConfigGUIButton.setObjectName("sinterConfigGUIButton")
        self.horizontalLayout_3.addWidget(self.sinterConfigGUIButton)
        self.configFileButton = QtGui.QPushButton(gatewayUploadDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.configFileButton.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.configFileButton.setFont(font)
        self.configFileButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.configFileButton.setIcon(icon1)
        self.configFileButton.setFlat(False)
        self.configFileButton.setObjectName("configFileButton")
        self.horizontalLayout_3.addWidget(self.configFileButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.appEdit = QtGui.QLineEdit(gatewayUploadDialog)
        self.appEdit.setEnabled(False)
        self.appEdit.setObjectName("appEdit")
        self.gridLayout.addWidget(self.appEdit, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(gatewayUploadDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.simNameEdit = QtGui.QComboBox(gatewayUploadDialog)
        self.simNameEdit.setEditable(True)
        self.simNameEdit.setObjectName("simNameEdit")
        self.gridLayout.addWidget(self.simNameEdit, 1, 2, 1, 1)
        self.deleteSimButton = QtGui.QPushButton(gatewayUploadDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteSimButton.setIcon(icon2)
        self.deleteSimButton.setObjectName("deleteSimButton")
        self.gridLayout.addWidget(self.deleteSimButton, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtGui.QGroupBox(gatewayUploadDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addFileButton = QtGui.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFileButton.setIcon(icon3)
        self.addFileButton.setObjectName("addFileButton")
        self.horizontalLayout_2.addWidget(self.addFileButton)
        self.removeFileButton = QtGui.QPushButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeFileButton.setIcon(icon4)
        self.removeFileButton.setObjectName("removeFileButton")
        self.horizontalLayout_2.addWidget(self.removeFileButton)
        self.relpathButton = QtGui.QPushButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/subArrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.relpathButton.setIcon(icon5)
        self.relpathButton.setObjectName("relpathButton")
        self.horizontalLayout_2.addWidget(self.relpathButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.fileTable = QtGui.QTableWidget(self.groupBox)
        self.fileTable.setObjectName("fileTable")
        self.fileTable.setColumnCount(2)
        self.fileTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fileTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.fileTable)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(gatewayUploadDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.localRadio = QtGui.QRadioButton(self.groupBox_2)
        self.localRadio.setObjectName("localRadio")
        self.gridLayout_2.addWidget(self.localRadio, 2, 0, 1, 1)
        self.lrRadio = QtGui.QRadioButton(self.groupBox_2)
        self.lrRadio.setObjectName("lrRadio")
        self.gridLayout_2.addWidget(self.lrRadio, 3, 0, 1, 1)
        self.addConfigButton = QtGui.QPushButton(self.groupBox_2)
        self.addConfigButton.setEnabled(False)
        self.addConfigButton.setText("")
        self.addConfigButton.setIcon(icon3)
        self.addConfigButton.setObjectName("addConfigButton")
        self.gridLayout_2.addWidget(self.addConfigButton, 4, 1, 1, 1)
        self.multiRadio = QtGui.QRadioButton(self.groupBox_2)
        self.multiRadio.setObjectName("multiRadio")
        self.gridLayout_2.addWidget(self.multiRadio, 4, 0, 1, 1)
        self.removeConfigButton = QtGui.QPushButton(self.groupBox_2)
        self.removeConfigButton.setEnabled(False)
        self.removeConfigButton.setText("")
        self.removeConfigButton.setIcon(icon4)
        self.removeConfigButton.setObjectName("removeConfigButton")
        self.gridLayout_2.addWidget(self.removeConfigButton, 4, 2, 1, 1)
        self.remoteRadio = QtGui.QRadioButton(self.groupBox_2)
        self.remoteRadio.setObjectName("remoteRadio")
        self.gridLayout_2.addWidget(self.remoteRadio, 1, 0, 1, 1)
        self.currentRadio = QtGui.QRadioButton(self.groupBox_2)
        self.currentRadio.setChecked(True)
        self.currentRadio.setObjectName("currentRadio")
        self.gridLayout_2.addWidget(self.currentRadio, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.tableWidget = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.okButton = QtGui.QPushButton(gatewayUploadDialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.okButton.setIcon(icon6)
        self.okButton.setIconSize(QtCore.QSize(16, 16))
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(gatewayUploadDialog)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cancelButton.setIcon(icon7)
        self.cancelButton.setIconSize(QtCore.QSize(16, 16))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(gatewayUploadDialog)
        QtCore.QMetaObject.connectSlotsByName(gatewayUploadDialog)

    def retranslateUi(self, gatewayUploadDialog):
        gatewayUploadDialog.setWindowTitle(QtGui.QApplication.translate("gatewayUploadDialog", "Turbine Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Add/Update Turbine Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Simulation Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Application:", None, QtGui.QApplication.UnicodeUTF8))
        self.sinterConfigGUIButton.setToolTip(QtGui.QApplication.translate("gatewayUploadDialog", "<html><head/><body><p>Edit or create a new SimSinter configuration file with the Sinter Config GUI.  This is a windows only option.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sinterConfigGUIButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Create/Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.configFileButton.setToolTip(QtGui.QApplication.translate("gatewayUploadDialog", "Search for a sinter configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.configFileButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.appEdit.setToolTip(QtGui.QApplication.translate("gatewayUploadDialog", "Application used to run the simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Sinter Configuration File:", None, QtGui.QApplication.UnicodeUTF8))
        self.simNameEdit.setToolTip(QtGui.QApplication.translate("gatewayUploadDialog", "Name of simulation on Turbine.  The drop down will show and allow the user to select existing simulations.  A new name can also be entered to create a new simulation.", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSimButton.setToolTip(QtGui.QApplication.translate("gatewayUploadDialog", "Delete a simulation from Turbine", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSimButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("gatewayUploadDialog", "Additional Files", None, QtGui.QApplication.UnicodeUTF8))
        self.addFileButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Add Files...", None, QtGui.QApplication.UnicodeUTF8))
        self.removeFileButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Remove Files", None, QtGui.QApplication.UnicodeUTF8))
        self.relpathButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Resource Relative Path", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("gatewayUploadDialog", "Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.fileTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("gatewayUploadDialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("gatewayUploadDialog", "Turbine Gateway Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.localRadio.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.lrRadio.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Remote + Local", None, QtGui.QApplication.UnicodeUTF8))
        self.multiRadio.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Multiple/Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.remoteRadio.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Remote", None, QtGui.QApplication.UnicodeUTF8))
        self.currentRadio.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("gatewayUploadDialog", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("gatewayUploadDialog", "Configuration File", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Okay", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("gatewayUploadDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
