# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalysisDialog_UI.ui'
#
# Created: Thu Feb 11 17:04:19 2016
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1165, 943)
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        self.gridLayout_8 = QtGui.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.infoGroup = QtGui.QGroupBox(Dialog)
        self.infoGroup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.infoGroup.setFont(font)
        self.infoGroup.setObjectName("infoGroup")
        self.gridLayout_7 = QtGui.QGridLayout(self.infoGroup)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.infoTable = QtGui.QTableWidget(self.infoGroup)
        self.infoTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.infoTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.infoTable.setObjectName("infoTable")
        self.infoTable.setColumnCount(1)
        self.infoTable.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(0, item)
        self.infoTable.horizontalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.infoTable, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.infoGroup, 0, 0, 1, 1)
        self.analysisTableGroup = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.analysisTableGroup.setFont(font)
        self.analysisTableGroup.setObjectName("analysisTableGroup")
        self.gridLayout_3 = QtGui.QGridLayout(self.analysisTableGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.analysisTable = QtGui.QTableWidget(self.analysisTableGroup)
        self.analysisTable.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.analysisTable.setFont(font)
        self.analysisTable.setObjectName("analysisTable")
        self.analysisTable.setColumnCount(5)
        self.analysisTable.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.analysisTable.setItem(0, 3, item)
        self.gridLayout_3.addWidget(self.analysisTable, 0, 0, 1, 2)
        self.info_button = QtGui.QPushButton(self.analysisTableGroup)
        self.info_button.setObjectName("info_button")
        self.gridLayout_3.addWidget(self.info_button, 1, 0, 1, 1)
        self.results_button = QtGui.QPushButton(self.analysisTableGroup)
        self.results_button.setObjectName("results_button")
        self.gridLayout_3.addWidget(self.results_button, 1, 1, 1, 1)
        self.delete_button = QtGui.QPushButton(self.analysisTableGroup)
        self.delete_button.setObjectName("delete_button")
        self.gridLayout_3.addWidget(self.delete_button, 2, 0, 1, 2)
        self.gridLayout_8.addWidget(self.analysisTableGroup, 1, 0, 1, 1)
        self.analysisGroup = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.analysisGroup.setFont(font)
        self.analysisGroup.setObjectName("analysisGroup")
        self.gridLayout_6 = QtGui.QGridLayout(self.analysisGroup)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.modeButton = QtGui.QPushButton(self.analysisGroup)
        self.modeButton.setObjectName("modeButton")
        self.gridLayout_6.addWidget(self.modeButton, 0, 0, 1, 1)
        self.modePages = QtGui.QStackedWidget(self.analysisGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.modePages.setFont(font)
        self.modePages.setObjectName("modePages")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_10 = QtGui.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.wizardScreenGroup = QtGui.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.wizardScreenGroup.setFont(font)
        self.wizardScreenGroup.setObjectName("wizardScreenGroup")
        self.gridLayout_11 = QtGui.QGridLayout(self.wizardScreenGroup)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.wizardScreenText = QtGui.QLabel(self.wizardScreenGroup)
        self.wizardScreenText.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenText.setFont(font)
        self.wizardScreenText.setWordWrap(True)
        self.wizardScreenText.setObjectName("wizardScreenText")
        self.horizontalLayout_21.addWidget(self.wizardScreenText)
        self.enableScreen_button = QtGui.QPushButton(self.wizardScreenGroup)
        self.enableScreen_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.enableScreen_button.setFont(font)
        self.enableScreen_button.setObjectName("enableScreen_button")
        self.horizontalLayout_21.addWidget(self.enableScreen_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.gridLayout_11.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.wizardScreenOutput_static = QtGui.QLabel(self.wizardScreenGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenOutput_static.setFont(font)
        self.wizardScreenOutput_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wizardScreenOutput_static.setWordWrap(False)
        self.wizardScreenOutput_static.setObjectName("wizardScreenOutput_static")
        self.horizontalLayout_13.addWidget(self.wizardScreenOutput_static)
        self.wizardScreenOutput_combo = QtGui.QComboBox(self.wizardScreenGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenOutput_combo.setFont(font)
        self.wizardScreenOutput_combo.setToolTip("")
        self.wizardScreenOutput_combo.setObjectName("wizardScreenOutput_combo")
        self.horizontalLayout_13.addWidget(self.wizardScreenOutput_combo)
        spacerItem1 = QtGui.QSpacerItem(138, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.gridLayout_11.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.wizardScreenMethod_static = QtGui.QLabel(self.wizardScreenGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenMethod_static.setFont(font)
        self.wizardScreenMethod_static.setObjectName("wizardScreenMethod_static")
        self.horizontalLayout_12.addWidget(self.wizardScreenMethod_static)
        self.wizardScreenMethod_combo = QtGui.QComboBox(self.wizardScreenGroup)
        self.wizardScreenMethod_combo.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenMethod_combo.setFont(font)
        self.wizardScreenMethod_combo.setObjectName("wizardScreenMethod_combo")
        self.wizardScreenMethod_combo.addItem("")
        self.horizontalLayout_12.addWidget(self.wizardScreenMethod_combo)
        spacerItem2 = QtGui.QSpacerItem(138, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.gridLayout_11.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.wizardScreenCompute_static = QtGui.QLabel(self.wizardScreenGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenCompute_static.setFont(font)
        self.wizardScreenCompute_static.setObjectName("wizardScreenCompute_static")
        self.horizontalLayout_11.addWidget(self.wizardScreenCompute_static)
        self.wizardScreenCompute_button = QtGui.QPushButton(self.wizardScreenGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenCompute_button.setFont(font)
        self.wizardScreenCompute_button.setObjectName("wizardScreenCompute_button")
        self.horizontalLayout_11.addWidget(self.wizardScreenCompute_button)
        spacerItem3 = QtGui.QSpacerItem(280, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.gridLayout_11.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.wizardScreenRepeat_static = QtGui.QLabel(self.wizardScreenGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardScreenRepeat_static.setFont(font)
        self.wizardScreenRepeat_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wizardScreenRepeat_static.setWordWrap(True)
        self.wizardScreenRepeat_static.setObjectName("wizardScreenRepeat_static")
        self.gridLayout_11.addWidget(self.wizardScreenRepeat_static, 4, 0, 1, 1)
        self.gridLayout_10.addWidget(self.wizardScreenGroup, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.wizardAnalysisText = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalysisText.setFont(font)
        self.wizardAnalysisText.setWordWrap(True)
        self.wizardAnalysisText.setObjectName("wizardAnalysisText")
        self.gridLayout_12.addWidget(self.wizardAnalysisText, 0, 0, 1, 4)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.output_static_3 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.output_static_3.setFont(font)
        self.output_static_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_static_3.setWordWrap(False)
        self.output_static_3.setObjectName("output_static_3")
        self.horizontalLayout_14.addWidget(self.output_static_3)
        self.wizardEnsemble_radio = QtGui.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardEnsemble_radio.setFont(font)
        self.wizardEnsemble_radio.setObjectName("wizardEnsemble_radio")
        self.horizontalLayout_14.addWidget(self.wizardEnsemble_radio)
        self.wizardRS_radio = QtGui.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRS_radio.setFont(font)
        self.wizardRS_radio.setObjectName("wizardRS_radio")
        self.horizontalLayout_14.addWidget(self.wizardRS_radio)
        spacerItem4 = QtGui.QSpacerItem(138, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.gridLayout_12.addLayout(self.horizontalLayout_14, 1, 0, 1, 4)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.output_static_5 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.output_static_5.setFont(font)
        self.output_static_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.output_static_5.setWordWrap(False)
        self.output_static_5.setObjectName("output_static_5")
        self.horizontalLayout_20.addWidget(self.output_static_5)
        self.wizardAnalysisOutput_combo = QtGui.QComboBox(self.groupBox_8)
        self.wizardAnalysisOutput_combo.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalysisOutput_combo.setFont(font)
        self.wizardAnalysisOutput_combo.setObjectName("wizardAnalysisOutput_combo")
        self.horizontalLayout_20.addWidget(self.wizardAnalysisOutput_combo)
        spacerItem5 = QtGui.QSpacerItem(138, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.gridLayout_12.addLayout(self.horizontalLayout_20, 2, 0, 1, 3)
        self.wizardRS_static = QtGui.QLabel(self.groupBox_8)
        self.wizardRS_static.setMinimumSize(QtCore.QSize(400, 27))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRS_static.setFont(font)
        self.wizardRS_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wizardRS_static.setWordWrap(True)
        self.wizardRS_static.setMargin(0)
        self.wizardRS_static.setIndent(-1)
        self.wizardRS_static.setObjectName("wizardRS_static")
        self.gridLayout_12.addWidget(self.wizardRS_static, 3, 0, 1, 4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 0, 1, 1)
        self.wizardRS_combo1 = RSCombo1(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRS_combo1.setFont(font)
        self.wizardRS_combo1.setObjectName("wizardRS_combo1")
        self.wizardRS_combo1.addItem("")
        self.wizardRS_combo1.addItem("")
        self.wizardRS_combo1.addItem("")
        self.wizardRS_combo1.addItem("")
        self.gridLayout_5.addWidget(self.wizardRS_combo1, 0, 1, 1, 2)
        self.wizardRS_combo2 = RSCombo2(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRS_combo2.setFont(font)
        self.wizardRS_combo2.setObjectName("wizardRS_combo2")
        self.gridLayout_5.addWidget(self.wizardRS_combo2, 0, 3, 1, 1)
        self.wizardRSLegendre_static = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRSLegendre_static.setFont(font)
        self.wizardRSLegendre_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wizardRSLegendre_static.setObjectName("wizardRSLegendre_static")
        self.gridLayout_5.addWidget(self.wizardRSLegendre_static, 0, 4, 1, 2)
        self.wizardRSLegendre_spin = LegendreSpinBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRSLegendre_spin.setFont(font)
        self.wizardRSLegendre_spin.setObjectName("wizardRSLegendre_spin")
        self.gridLayout_5.addWidget(self.wizardRSLegendre_spin, 0, 6, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 7, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 1, 0, 1, 1)
        self.wizardUserRegression_static = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardUserRegression_static.setFont(font)
        self.wizardUserRegression_static.setObjectName("wizardUserRegression_static")
        self.gridLayout_5.addWidget(self.wizardUserRegression_static, 1, 1, 1, 1)
        self.wizardUserRegressionFile_edit = QtGui.QLineEdit(self.groupBox_8)
        self.wizardUserRegressionFile_edit.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardUserRegressionFile_edit.setFont(font)
        self.wizardUserRegressionFile_edit.setReadOnly(True)
        self.wizardUserRegressionFile_edit.setObjectName("wizardUserRegressionFile_edit")
        self.gridLayout_5.addWidget(self.wizardUserRegressionFile_edit, 1, 2, 1, 3)
        self.wizardUserRegressionBrowse_button = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardUserRegressionBrowse_button.setFont(font)
        self.wizardUserRegressionBrowse_button.setObjectName("wizardUserRegressionBrowse_button")
        self.gridLayout_5.addWidget(self.wizardUserRegressionBrowse_button, 1, 5, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 1, 7, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 4, 0, 1, 3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.wizardRSValidate_static = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRSValidate_static.setFont(font)
        self.wizardRSValidate_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wizardRSValidate_static.setWordWrap(True)
        self.wizardRSValidate_static.setObjectName("wizardRSValidate_static")
        self.horizontalLayout_22.addWidget(self.wizardRSValidate_static)
        self.wizardRSValidate_button = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRSValidate_button.setFont(font)
        self.wizardRSValidate_button.setObjectName("wizardRSValidate_button")
        self.horizontalLayout_22.addWidget(self.wizardRSValidate_button)
        self.wizardRSValidateNote_static = QtGui.QLabel(self.groupBox_8)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wizardRSValidateNote_static.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardRSValidateNote_static.setFont(font)
        self.wizardRSValidateNote_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wizardRSValidateNote_static.setObjectName("wizardRSValidateNote_static")
        self.horizontalLayout_22.addWidget(self.wizardRSValidateNote_static)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem10)
        self.gridLayout_12.addLayout(self.horizontalLayout_22, 5, 0, 1, 4)
        self.wizardViz_static = QtGui.QLabel(self.groupBox_8)
        self.wizardViz_static.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardViz_static.setFont(font)
        self.wizardViz_static.setWordWrap(True)
        self.wizardViz_static.setObjectName("wizardViz_static")
        self.gridLayout_12.addWidget(self.wizardViz_static, 6, 0, 1, 4)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.wizardViz_combo1 = QtGui.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardViz_combo1.setFont(font)
        self.wizardViz_combo1.setObjectName("wizardViz_combo1")
        self.horizontalLayout_17.addWidget(self.wizardViz_combo1)
        self.wizardViz_combo2 = QtGui.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardViz_combo2.setFont(font)
        self.wizardViz_combo2.setObjectName("wizardViz_combo2")
        self.horizontalLayout_17.addWidget(self.wizardViz_combo2)
        self.wizardViz_combo3 = QtGui.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardViz_combo3.setFont(font)
        self.wizardViz_combo3.setObjectName("wizardViz_combo3")
        self.horizontalLayout_17.addWidget(self.wizardViz_combo3)
        self.wizardViz_button = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardViz_button.setFont(font)
        self.wizardViz_button.setObjectName("wizardViz_button")
        self.horizontalLayout_17.addWidget(self.wizardViz_button)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.gridLayout_12.addLayout(self.horizontalLayout_17, 7, 0, 1, 2)
        self.wizardAnalysisRepeat_static = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalysisRepeat_static.setFont(font)
        self.wizardAnalysisRepeat_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wizardAnalysisRepeat_static.setWordWrap(True)
        self.wizardAnalysisRepeat_static.setObjectName("wizardAnalysisRepeat_static")
        self.gridLayout_12.addWidget(self.wizardAnalysisRepeat_static, 8, 0, 1, 4)
        self.wizardAnalyze_static = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalyze_static.setFont(font)
        self.wizardAnalyze_static.setObjectName("wizardAnalyze_static")
        self.gridLayout_12.addWidget(self.wizardAnalyze_static, 9, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.wizardAnalyze_combo1 = QtGui.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalyze_combo1.setFont(font)
        self.wizardAnalyze_combo1.setObjectName("wizardAnalyze_combo1")
        self.wizardAnalyze_combo1.addItem("")
        self.wizardAnalyze_combo1.addItem("")
        self.horizontalLayout_16.addWidget(self.wizardAnalyze_combo1)
        self.wizardAnalyze_combo2 = QtGui.QComboBox(self.groupBox_8)
        self.wizardAnalyze_combo2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalyze_combo2.setFont(font)
        self.wizardAnalyze_combo2.setObjectName("wizardAnalyze_combo2")
        self.horizontalLayout_16.addWidget(self.wizardAnalyze_combo2)
        self.gridLayout_12.addLayout(self.horizontalLayout_16, 9, 1, 1, 1)
        self.wizardAnalyze_button = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardAnalyze_button.setFont(font)
        self.wizardAnalyze_button.setObjectName("wizardAnalyze_button")
        self.gridLayout_12.addWidget(self.wizardAnalyze_button, 9, 2, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 9, 3, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.wizardInfer_static = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardInfer_static.setFont(font)
        self.wizardInfer_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wizardInfer_static.setWordWrap(True)
        self.wizardInfer_static.setObjectName("wizardInfer_static")
        self.horizontalLayout_27.addWidget(self.wizardInfer_static)
        self.wizardInfer_button = QtGui.QPushButton(self.groupBox_8)
        self.wizardInfer_button.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.wizardInfer_button.setFont(font)
        self.wizardInfer_button.setObjectName("wizardInfer_button")
        self.horizontalLayout_27.addWidget(self.wizardInfer_button)
        self.gridLayout_12.addLayout(self.horizontalLayout_27, 10, 0, 1, 4)
        self.gridLayout_10.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.modePages.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_9 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_static = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.output_static.setFont(font)
        self.output_static.setAlignment(QtCore.Qt.AlignCenter)
        self.output_static.setObjectName("output_static")
        self.horizontalLayout.addWidget(self.output_static)
        self.output_combo = QtGui.QComboBox(self.page_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.output_combo.setFont(font)
        self.output_combo.setObjectName("output_combo")
        self.horizontalLayout.addWidget(self.output_combo)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.paramSelectGroup = QtGui.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.paramSelectGroup.setFont(font)
        self.paramSelectGroup.setObjectName("paramSelectGroup")
        self.gridLayout = QtGui.QGridLayout(self.paramSelectGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.screen_static = QtGui.QLabel(self.paramSelectGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.screen_static.setFont(font)
        self.screen_static.setObjectName("screen_static")
        self.horizontalLayout_7.addWidget(self.screen_static)
        self.screen_combo = QtGui.QComboBox(self.paramSelectGroup)
        self.screen_combo.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.screen_combo.setFont(font)
        self.screen_combo.setObjectName("screen_combo")
        self.horizontalLayout_7.addWidget(self.screen_combo)
        self.screen_button = QtGui.QPushButton(self.paramSelectGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.screen_button.setFont(font)
        self.screen_button.setObjectName("screen_button")
        self.horizontalLayout_7.addWidget(self.screen_button)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.paramSelectGroup, 1, 0, 1, 1)
        self.ensembleDataGroup = QtGui.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.ensembleDataGroup.setFont(font)
        self.ensembleDataGroup.setObjectName("ensembleDataGroup")
        self.gridLayout_2 = QtGui.QGridLayout(self.ensembleDataGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dataAnalyze_static = QtGui.QLabel(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataAnalyze_static.setFont(font)
        self.dataAnalyze_static.setObjectName("dataAnalyze_static")
        self.gridLayout_2.addWidget(self.dataAnalyze_static, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dataAnalyze_combo1 = QtGui.QComboBox(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataAnalyze_combo1.setFont(font)
        self.dataAnalyze_combo1.setObjectName("dataAnalyze_combo1")
        self.dataAnalyze_combo1.addItem("")
        self.dataAnalyze_combo1.addItem("")
        self.dataAnalyze_combo1.addItem("")
        self.horizontalLayout_8.addWidget(self.dataAnalyze_combo1)
        self.dataAnalyze_combo2 = QtGui.QComboBox(self.ensembleDataGroup)
        self.dataAnalyze_combo2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataAnalyze_combo2.setFont(font)
        self.dataAnalyze_combo2.setObjectName("dataAnalyze_combo2")
        self.horizontalLayout_8.addWidget(self.dataAnalyze_combo2)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.dataAnalyze_button = QtGui.QPushButton(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataAnalyze_button.setFont(font)
        self.dataAnalyze_button.setObjectName("dataAnalyze_button")
        self.gridLayout_2.addWidget(self.dataAnalyze_button, 0, 2, 1, 1)
        self.dataViz_static = QtGui.QLabel(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataViz_static.setFont(font)
        self.dataViz_static.setObjectName("dataViz_static")
        self.gridLayout_2.addWidget(self.dataViz_static, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dataViz_combo1 = QtGui.QComboBox(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataViz_combo1.setFont(font)
        self.dataViz_combo1.setObjectName("dataViz_combo1")
        self.horizontalLayout_9.addWidget(self.dataViz_combo1)
        self.dataViz_combo2 = QtGui.QComboBox(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataViz_combo2.setFont(font)
        self.dataViz_combo2.setObjectName("dataViz_combo2")
        self.horizontalLayout_9.addWidget(self.dataViz_combo2)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.dataViz_button = QtGui.QPushButton(self.ensembleDataGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dataViz_button.setFont(font)
        self.dataViz_button.setObjectName("dataViz_button")
        self.gridLayout_2.addWidget(self.dataViz_button, 1, 2, 1, 1)
        self.gridLayout_9.addWidget(self.ensembleDataGroup, 2, 0, 1, 1)
        self.RSGroup = QtGui.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.RSGroup.setFont(font)
        self.RSGroup.setObjectName("RSGroup")
        self.gridLayout_4 = QtGui.QGridLayout(self.RSGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.RS_static = QtGui.QLabel(self.RSGroup)
        self.RS_static.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RS_static.setFont(font)
        self.RS_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RS_static.setObjectName("RS_static")
        self.gridLayout_4.addWidget(self.RS_static, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RS_combo1 = RSCombo1(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RS_combo1.setFont(font)
        self.RS_combo1.setObjectName("RS_combo1")
        self.RS_combo1.addItem("")
        self.RS_combo1.addItem("")
        self.RS_combo1.addItem("")
        self.RS_combo1.addItem("")
        self.horizontalLayout_5.addWidget(self.RS_combo1)
        self.RS_combo2 = RSCombo2(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RS_combo2.setFont(font)
        self.RS_combo2.setObjectName("RS_combo2")
        self.horizontalLayout_5.addWidget(self.RS_combo2)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.RSMarsBasis_static = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSMarsBasis_static.setFont(font)
        self.RSMarsBasis_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RSMarsBasis_static.setObjectName("RSMarsBasis_static")
        self.horizontalLayout_18.addWidget(self.RSMarsBasis_static)
        self.RSMarsBasis_spin = MarsBasisSpinBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSMarsBasis_spin.setFont(font)
        self.RSMarsBasis_spin.setObjectName("RSMarsBasis_spin")
        self.horizontalLayout_18.addWidget(self.RSMarsBasis_spin)
        self.gridLayout_4.addLayout(self.horizontalLayout_18, 2, 1, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.RSMarsDegree_static = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSMarsDegree_static.setFont(font)
        self.RSMarsDegree_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RSMarsDegree_static.setObjectName("RSMarsDegree_static")
        self.horizontalLayout_24.addWidget(self.RSMarsDegree_static)
        self.RSMarsDegree_spin = MarsDegreeSpinBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSMarsDegree_spin.setFont(font)
        self.RSMarsDegree_spin.setObjectName("RSMarsDegree_spin")
        self.horizontalLayout_24.addWidget(self.RSMarsDegree_spin)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 3, 1, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.expertUserRegression_static = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.expertUserRegression_static.setFont(font)
        self.expertUserRegression_static.setObjectName("expertUserRegression_static")
        self.horizontalLayout_25.addWidget(self.expertUserRegression_static)
        self.expertUserRegressionFile_edit = QtGui.QLineEdit(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.expertUserRegressionFile_edit.setFont(font)
        self.expertUserRegressionFile_edit.setReadOnly(True)
        self.expertUserRegressionFile_edit.setObjectName("expertUserRegressionFile_edit")
        self.horizontalLayout_25.addWidget(self.expertUserRegressionFile_edit)
        self.expertUserRegressionBrowse_button = QtGui.QPushButton(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.expertUserRegressionBrowse_button.setFont(font)
        self.expertUserRegressionBrowse_button.setObjectName("expertUserRegressionBrowse_button")
        self.horizontalLayout_25.addWidget(self.expertUserRegressionBrowse_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_25, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 6, 0, 1, 1)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.testSet_chkbox = QtGui.QCheckBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.testSet_chkbox.setFont(font)
        self.testSet_chkbox.setObjectName("testSet_chkbox")
        self.horizontalLayout_39.addWidget(self.testSet_chkbox)
        self.testSet_edit = QtGui.QLineEdit(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.testSet_edit.setFont(font)
        self.testSet_edit.setReadOnly(True)
        self.testSet_edit.setObjectName("testSet_edit")
        self.horizontalLayout_39.addWidget(self.testSet_edit)
        self.testSetBrowse_button = QtGui.QPushButton(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.testSetBrowse_button.setFont(font)
        self.testSetBrowse_button.setObjectName("testSetBrowse_button")
        self.horizontalLayout_39.addWidget(self.testSetBrowse_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_39, 6, 1, 1, 1)
        self.RSValidate_button = QtGui.QPushButton(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSValidate_button.setFont(font)
        self.RSValidate_button.setObjectName("RSValidate_button")
        self.gridLayout_4.addWidget(self.RSValidate_button, 6, 2, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.RSValidationGroups_static = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSValidationGroups_static.setFont(font)
        self.RSValidationGroups_static.setObjectName("RSValidationGroups_static")
        self.horizontalLayout_23.addWidget(self.RSValidationGroups_static)
        self.RSValidationGroups_spin = QtGui.QSpinBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSValidationGroups_spin.setFont(font)
        self.RSValidationGroups_spin.setObjectName("RSValidationGroups_spin")
        self.horizontalLayout_23.addWidget(self.RSValidationGroups_spin)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 7, 1, 1, 1)
        self.RSCodeBrowse_button = QtGui.QPushButton(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSCodeBrowse_button.setFont(font)
        self.RSCodeBrowse_button.setObjectName("RSCodeBrowse_button")
        self.gridLayout_4.addWidget(self.RSCodeBrowse_button, 8, 1, 1, 1)
        self.RSViz_static = QtGui.QLabel(self.RSGroup)
        self.RSViz_static.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSViz_static.setFont(font)
        self.RSViz_static.setObjectName("RSViz_static")
        self.gridLayout_4.addWidget(self.RSViz_static, 9, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RSViz_combo1 = QtGui.QComboBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSViz_combo1.setFont(font)
        self.RSViz_combo1.setObjectName("RSViz_combo1")
        self.horizontalLayout_6.addWidget(self.RSViz_combo1)
        self.RSViz_combo2 = QtGui.QComboBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSViz_combo2.setFont(font)
        self.RSViz_combo2.setObjectName("RSViz_combo2")
        self.horizontalLayout_6.addWidget(self.RSViz_combo2)
        self.RSViz_combo3 = QtGui.QComboBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSViz_combo3.setFont(font)
        self.RSViz_combo3.setObjectName("RSViz_combo3")
        self.horizontalLayout_6.addWidget(self.RSViz_combo3)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 9, 1, 1, 1)
        self.RSViz_button = QtGui.QPushButton(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSViz_button.setFont(font)
        self.RSViz_button.setObjectName("RSViz_button")
        self.gridLayout_4.addWidget(self.RSViz_button, 9, 2, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RSVizMax_chkbox = QtGui.QCheckBox(self.RSGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.RSVizMax_chkbox.setFont(font)
        self.RSVizMax_chkbox.setObjectName("RSVizMax_chkbox")
        self.horizontalLayout_3.addWidget(self.RSVizMax_chkbox)
        self.RSVizMax_edit = QtGui.QLineEdit(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSVizMax_edit.setFont(font)
        self.RSVizMax_edit.setObjectName("RSVizMax_edit")
        self.horizontalLayout_3.addWidget(self.RSVizMax_edit)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RSVizMin_chkbox = QtGui.QCheckBox(self.RSGroup)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.RSVizMin_chkbox.setFont(font)
        self.RSVizMin_chkbox.setObjectName("RSVizMin_chkbox")
        self.horizontalLayout_2.addWidget(self.RSVizMin_chkbox)
        self.RSVizMin_edit = QtGui.QLineEdit(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSVizMin_edit.setFont(font)
        self.RSVizMin_edit.setObjectName("RSVizMin_edit")
        self.horizontalLayout_2.addWidget(self.RSVizMin_edit)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 10, 1, 1, 1)
        self.RSAnalyze_static = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSAnalyze_static.setFont(font)
        self.RSAnalyze_static.setObjectName("RSAnalyze_static")
        self.gridLayout_4.addWidget(self.RSAnalyze_static, 11, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.RSAnalyze_combo1 = QtGui.QComboBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSAnalyze_combo1.setFont(font)
        self.RSAnalyze_combo1.setObjectName("RSAnalyze_combo1")
        self.RSAnalyze_combo1.addItem("")
        self.RSAnalyze_combo1.addItem("")
        self.RSAnalyze_combo1.addItem("")
        self.horizontalLayout_10.addWidget(self.RSAnalyze_combo1)
        self.RSAnalyze_combo2 = QtGui.QComboBox(self.RSGroup)
        self.RSAnalyze_combo2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSAnalyze_combo2.setFont(font)
        self.RSAnalyze_combo2.setObjectName("RSAnalyze_combo2")
        self.horizontalLayout_10.addWidget(self.RSAnalyze_combo2)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 11, 1, 1, 1)
        self.RSAnalyze_button = QtGui.QPushButton(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSAnalyze_button.setFont(font)
        self.RSAnalyze_button.setObjectName("RSAnalyze_button")
        self.gridLayout_4.addWidget(self.RSAnalyze_button, 11, 2, 1, 1)
        self.inputPrior_table = InputPriorTable(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.inputPrior_table.setFont(font)
        self.inputPrior_table.setObjectName("inputPrior_table")
        self.inputPrior_table.setColumnCount(8)
        self.inputPrior_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(7, item)
        self.gridLayout_4.addWidget(self.inputPrior_table, 13, 1, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RSLegendre_static = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSLegendre_static.setFont(font)
        self.RSLegendre_static.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RSLegendre_static.setObjectName("RSLegendre_static")
        self.horizontalLayout_4.addWidget(self.RSLegendre_static)
        self.RSLegendre_spin = LegendreSpinBox(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.RSLegendre_spin.setFont(font)
        self.RSLegendre_spin.setObjectName("RSLegendre_spin")
        self.horizontalLayout_4.addWidget(self.RSLegendre_spin)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.pointEval_label = QtGui.QLabel(self.RSGroup)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pointEval_label.setFont(font)
        self.pointEval_label.setText("")
        self.pointEval_label.setObjectName("pointEval_label")
        self.gridLayout_4.addWidget(self.pointEval_label, 12, 1, 1, 1)
        self.gridLayout_9.addWidget(self.RSGroup, 3, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_26.addWidget(self.label)
        self.expertInfer_button = QtGui.QPushButton(self.page_2)
        self.expertInfer_button.setObjectName("expertInfer_button")
        self.horizontalLayout_26.addWidget(self.expertInfer_button)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem15)
        self.gridLayout_9.addLayout(self.horizontalLayout_26, 4, 0, 1, 1)
        self.modePages.addWidget(self.page_2)
        self.gridLayout_6.addWidget(self.modePages, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.analysisGroup, 0, 1, 2, 1)

        self.retranslateUi(Dialog)
        self.modePages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.modeButton, self.output_combo)
        Dialog.setTabOrder(self.output_combo, self.screen_combo)
        Dialog.setTabOrder(self.screen_combo, self.screen_button)
        Dialog.setTabOrder(self.screen_button, self.dataAnalyze_combo1)
        Dialog.setTabOrder(self.dataAnalyze_combo1, self.dataAnalyze_combo2)
        Dialog.setTabOrder(self.dataAnalyze_combo2, self.dataAnalyze_button)
        Dialog.setTabOrder(self.dataAnalyze_button, self.dataViz_combo1)
        Dialog.setTabOrder(self.dataViz_combo1, self.dataViz_combo2)
        Dialog.setTabOrder(self.dataViz_combo2, self.dataViz_button)
        Dialog.setTabOrder(self.dataViz_button, self.RS_combo1)
        Dialog.setTabOrder(self.RS_combo1, self.RS_combo2)
        Dialog.setTabOrder(self.RS_combo2, self.RSLegendre_spin)
        Dialog.setTabOrder(self.RSLegendre_spin, self.expertUserRegressionFile_edit)
        Dialog.setTabOrder(self.expertUserRegressionFile_edit, self.expertUserRegressionBrowse_button)
        Dialog.setTabOrder(self.expertUserRegressionBrowse_button, self.RSValidationGroups_spin)
        Dialog.setTabOrder(self.RSValidationGroups_spin, self.RSCodeBrowse_button)
        Dialog.setTabOrder(self.RSCodeBrowse_button, self.RSAnalyze_combo1)
        Dialog.setTabOrder(self.RSAnalyze_combo1, self.RSAnalyze_combo2)
        Dialog.setTabOrder(self.RSAnalyze_combo2, self.RSAnalyze_button)
        Dialog.setTabOrder(self.RSAnalyze_button, self.inputPrior_table)
        Dialog.setTabOrder(self.inputPrior_table, self.RSViz_combo1)
        Dialog.setTabOrder(self.RSViz_combo1, self.RSViz_combo2)
        Dialog.setTabOrder(self.RSViz_combo2, self.RSViz_combo3)
        Dialog.setTabOrder(self.RSViz_combo3, self.RSVizMax_chkbox)
        Dialog.setTabOrder(self.RSVizMax_chkbox, self.RSVizMax_edit)
        Dialog.setTabOrder(self.RSVizMax_edit, self.RSVizMin_chkbox)
        Dialog.setTabOrder(self.RSVizMin_chkbox, self.RSVizMin_edit)
        Dialog.setTabOrder(self.RSVizMin_edit, self.expertInfer_button)
        Dialog.setTabOrder(self.expertInfer_button, self.analysisTable)
        Dialog.setTabOrder(self.analysisTable, self.enableScreen_button)
        Dialog.setTabOrder(self.enableScreen_button, self.wizardScreenOutput_combo)
        Dialog.setTabOrder(self.wizardScreenOutput_combo, self.wizardScreenMethod_combo)
        Dialog.setTabOrder(self.wizardScreenMethod_combo, self.wizardScreenCompute_button)
        Dialog.setTabOrder(self.wizardScreenCompute_button, self.wizardEnsemble_radio)
        Dialog.setTabOrder(self.wizardEnsemble_radio, self.wizardRS_radio)
        Dialog.setTabOrder(self.wizardRS_radio, self.wizardAnalysisOutput_combo)
        Dialog.setTabOrder(self.wizardAnalysisOutput_combo, self.wizardRS_combo1)
        Dialog.setTabOrder(self.wizardRS_combo1, self.wizardRS_combo2)
        Dialog.setTabOrder(self.wizardRS_combo2, self.wizardRSLegendre_spin)
        Dialog.setTabOrder(self.wizardRSLegendre_spin, self.wizardUserRegressionFile_edit)
        Dialog.setTabOrder(self.wizardUserRegressionFile_edit, self.wizardUserRegressionBrowse_button)
        Dialog.setTabOrder(self.wizardUserRegressionBrowse_button, self.wizardRSValidate_button)
        Dialog.setTabOrder(self.wizardRSValidate_button, self.wizardAnalyze_combo1)
        Dialog.setTabOrder(self.wizardAnalyze_combo1, self.wizardAnalyze_combo2)
        Dialog.setTabOrder(self.wizardAnalyze_combo2, self.wizardViz_combo1)
        Dialog.setTabOrder(self.wizardViz_combo1, self.wizardViz_combo2)
        Dialog.setTabOrder(self.wizardViz_combo2, self.wizardViz_combo3)
        Dialog.setTabOrder(self.wizardViz_combo3, self.wizardInfer_button)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Ensemble 1: Rosenbrock", None, QtGui.QApplication.UnicodeUTF8))
        self.infoGroup.setTitle(QtGui.QApplication.translate("Dialog", "Ensemble Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Ensemble ID", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "# Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "# Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Sample Design", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Sample Size", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.verticalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Descriptor", None, QtGui.QApplication.UnicodeUTF8))
        self.infoTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTableGroup.setTitle(QtGui.QApplication.translate("Dialog", "Analyses Performed", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "SubType", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Input(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Output(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Response Surface", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.analysisTable.isSortingEnabled()
        self.analysisTable.setSortingEnabled(False)
        self.analysisTable.item(0, 0).setText(QtGui.QApplication.translate("Dialog", "Parameter Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.item(0, 1).setText(QtGui.QApplication.translate("Dialog", "Gradient Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.item(0, 3).setText(QtGui.QApplication.translate("Dialog", "CO2_Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisTable.setSortingEnabled(__sortingEnabled)
        self.info_button.setText(QtGui.QApplication.translate("Dialog", "Additional Info", None, QtGui.QApplication.UnicodeUTF8))
        self.results_button.setText(QtGui.QApplication.translate("Dialog", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setText(QtGui.QApplication.translate("Dialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisGroup.setTitle(QtGui.QApplication.translate("Dialog", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.modeButton.setToolTip(QtGui.QApplication.translate("Dialog", "Click to toggle between WIZARD and EXPERT modes.\n"
"WIZARD mode provides step-by-step guidance.\n"
"EXPERT mode has more options and features.", None, QtGui.QApplication.UnicodeUTF8))
        self.modeButton.setText(QtGui.QApplication.translate("Dialog", "Mode: Expert (Click for Wizard Mode)", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenGroup.setTitle(QtGui.QApplication.translate("Dialog", "Qualitative Parameter Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenText.setText(QtGui.QApplication.translate("Dialog", "You have over 10 inputs.  Parameter selection is recommended to determine which inputs can be removed from initial consideration.", None, QtGui.QApplication.UnicodeUTF8))
        self.enableScreen_button.setToolTip(QtGui.QApplication.translate("Dialog", "Parameter screening will allow you to identify\n"
"(and thus eliminate) insignificant input parameters.", None, QtGui.QApplication.UnicodeUTF8))
        self.enableScreen_button.setText(QtGui.QApplication.translate("Dialog", "Enable Parameter\n"
"Screening", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenOutput_static.setText(QtGui.QApplication.translate("Dialog", "1. Choose output to analyze (Select most important output):", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenMethod_static.setText(QtGui.QApplication.translate("Dialog", "2. Choose Parameter Selection Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenMethod_combo.setItemText(0, QtGui.QApplication.translate("Dialog", "MARS Bagging (Recommended)", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenCompute_static.setText(QtGui.QApplication.translate("Dialog", "3. Click here:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenCompute_button.setToolTip(QtGui.QApplication.translate("Dialog", "The results will be a bar chart that shows the significance\n"
"of each input with respect to the chosen output.\n"
"You can use this information to eliminate insignificant\n"
"input parameters from subsequent analyses.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenCompute_button.setText(QtGui.QApplication.translate("Dialog", "Compute input importance", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardScreenRepeat_static.setText(QtGui.QApplication.translate("Dialog", "4. Repeat for all important outputs.  Note those inputs to which the important outputs are not as sensitive.  Create a new ensemble where these inputs are fixed to reduce the complexity and duration of analysis calculations.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalysisText.setText(QtGui.QApplication.translate("Dialog", "You have at least 1000 samples.  This is enough to perform analysis on the ensemble data with good results.  You may still choose to analyze data generated from a response surface trained on the ensemble data instead.", None, QtGui.QApplication.UnicodeUTF8))
        self.output_static_3.setText(QtGui.QApplication.translate("Dialog", "1. Choose which output values to use in analysis:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardEnsemble_radio.setToolTip(QtGui.QApplication.translate("Dialog", "Analysis will be performed on the \"raw\" ensemble.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardEnsemble_radio.setText(QtGui.QApplication.translate("Dialog", "Ensemble Data", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_radio.setToolTip(QtGui.QApplication.translate("Dialog", "Analysis will be performed on a much larger ensemble,\n"
"where the output values are interpolated from\n"
"the response surface. The results should be smoother\n"
"than those achieved through ensemble data analysis.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_radio.setText(QtGui.QApplication.translate("Dialog", "Response Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.output_static_5.setText(QtGui.QApplication.translate("Dialog", "2. Choose output variable to analyze (Select most important output):", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_static.setText(QtGui.QApplication.translate("Dialog", "3. We will now determine which response surface method best fits the data.  Select a candidate method from the following:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select response surface type.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_combo1.setItemText(0, QtGui.QApplication.translate("Dialog", "Polynomial ->", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_combo1.setItemText(1, QtGui.QApplication.translate("Dialog", "MARS ->", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_combo1.setItemText(2, QtGui.QApplication.translate("Dialog", "Support Vector Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_combo1.setItemText(3, QtGui.QApplication.translate("Dialog", "Kriging", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRS_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select response surface subtype, if available.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRSLegendre_static.setText(QtGui.QApplication.translate("Dialog", "Legendre Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRSLegendre_spin.setToolTip(QtGui.QApplication.translate("Dialog", "For Legendre response surfaces, a higher value will result\n"
"in a more accurate response surface, but at the expense\n"
"of longer runtime. The allowable maximum value is\n"
"dependent on sample size.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardUserRegression_static.setText(QtGui.QApplication.translate("Dialog", "User Regression File:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardUserRegressionFile_edit.setToolTip(QtGui.QApplication.translate("Dialog", "For the user-regression response surface, an executable\n"
"that reads the inputs and writes the output is required.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardUserRegressionBrowse_button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRSValidate_static.setText(QtGui.QApplication.translate("Dialog", "4. Click here:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRSValidate_button.setToolTip(QtGui.QApplication.translate("Dialog", "The results will be a histogram of response surface errors\n"
"and a scatterplot of actual vs. predicted values.\n"
"If the response surface is a good fit, (1) the histogram bars\n"
" should be centered near zero, and (2) the scatterplot\n"
"should resemble a diagonal line.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRSValidate_button.setText(QtGui.QApplication.translate("Dialog", "Validate", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardRSValidateNote_static.setText(QtGui.QApplication.translate("Dialog", "Note: Validation may take a long time if you have certain combinations of a large sample size,\n"
" large number of inputs, and certain response surface (e.g. Kriging, Mars with Bagging)", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardViz_static.setText(QtGui.QApplication.translate("Dialog", "5. To visualize the response surface (for correctness of the chosen method for the selected output), choose the inputs and click \"Visualize\".", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardViz_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardViz_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardViz_combo3.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardViz_button.setToolTip(QtGui.QApplication.translate("Dialog", "The resulting plots will show output values\n"
"interpolated from the trained response surface.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardViz_button.setText(QtGui.QApplication.translate("Dialog", "Visualize", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalysisRepeat_static.setText(QtGui.QApplication.translate("Dialog", "6. Repeat with different methods until the validation plot demonstrates a response surface method that fits the data well.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_static.setText(QtGui.QApplication.translate("Dialog", "7. Choose UQ Analysis:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select analysis type.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_combo1.setItemText(0, QtGui.QApplication.translate("Dialog", "Uncertainty Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_combo1.setItemText(1, QtGui.QApplication.translate("Dialog", "Sensitivity Analysis ->", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select analysis subtype, if available.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_button.setToolTip(QtGui.QApplication.translate("Dialog", "Analysis is performed with respect to the ensemble\n"
"data or response surface as designated above.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardAnalyze_button.setText(QtGui.QApplication.translate("Dialog", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardInfer_static.setText(QtGui.QApplication.translate("Dialog", "8. Repeat steps 2 through 6 for each output of importance and take note of the best response surface for each. To infer input distributions from output distributions (from observations or expert judgement), click here:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardInfer_button.setToolTip(QtGui.QApplication.translate("Dialog", "Click to open separate dialog for Bayesian Inference.", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardInfer_button.setText(QtGui.QApplication.translate("Dialog", "Infer...", None, QtGui.QApplication.UnicodeUTF8))
        self.output_static.setText(QtGui.QApplication.translate("Dialog", "Select Output under Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.paramSelectGroup.setTitle(QtGui.QApplication.translate("Dialog", "Qualitative Parameter Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.screen_static.setText(QtGui.QApplication.translate("Dialog", "Choose Parameter Selection Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.screen_button.setToolTip(QtGui.QApplication.translate("Dialog", "The results will be a bar chart that shows the significance\n"
"of each input with respect to the chosen output.\n"
"You can use this information to eliminate insignificant\n"
"input parameters from subsequent analyses.", None, QtGui.QApplication.UnicodeUTF8))
        self.screen_button.setText(QtGui.QApplication.translate("Dialog", "Compute input importance", None, QtGui.QApplication.UnicodeUTF8))
        self.ensembleDataGroup.setTitle(QtGui.QApplication.translate("Dialog", "Ensemble Data Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_static.setText(QtGui.QApplication.translate("Dialog", "Choose UQ Analysis:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select analysis type.", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_combo1.setItemText(0, QtGui.QApplication.translate("Dialog", "Uncertainty Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_combo1.setItemText(1, QtGui.QApplication.translate("Dialog", "Correlation Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_combo1.setItemText(2, QtGui.QApplication.translate("Dialog", "Sensitivity Analysis ->", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select analysis subtype, if available.", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_button.setToolTip(QtGui.QApplication.translate("Dialog", "Analysis will be performed on the \"raw\" ensemble.", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAnalyze_button.setText(QtGui.QApplication.translate("Dialog", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.dataViz_static.setText(QtGui.QApplication.translate("Dialog", "Visualize Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataViz_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.dataViz_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.dataViz_button.setToolTip(QtGui.QApplication.translate("Dialog", "Selection of 1 input will result in a 2-D scatterplot.\n"
"Selection of 2 inputs will result in a 3-D scatterplot.", None, QtGui.QApplication.UnicodeUTF8))
        self.dataViz_button.setText(QtGui.QApplication.translate("Dialog", "Visualize", None, QtGui.QApplication.UnicodeUTF8))
        self.RSGroup.setTitle(QtGui.QApplication.translate("Dialog", "Response Surface (RS) Based Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_static.setText(QtGui.QApplication.translate("Dialog", "Select RS:", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select response surface type.", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_combo1.setItemText(0, QtGui.QApplication.translate("Dialog", "Polynomial ->", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_combo1.setItemText(1, QtGui.QApplication.translate("Dialog", "MARS ->", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_combo1.setItemText(2, QtGui.QApplication.translate("Dialog", "Support Vector Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_combo1.setItemText(3, QtGui.QApplication.translate("Dialog", "Kriging", None, QtGui.QApplication.UnicodeUTF8))
        self.RS_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select response surface subtype, if available.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSMarsBasis_static.setText(QtGui.QApplication.translate("Dialog", "MARS Number of basis functions:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSMarsBasis_spin.setToolTip(QtGui.QApplication.translate("Dialog", "Depending on the chosen response surface, you can\n"
"customize its parameter(s). A higher value will result\n"
"in a more accurate response surface, but at the expense\n"
"of longer runtime.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSMarsDegree_static.setText(QtGui.QApplication.translate("Dialog", "MARS Degree of interaction:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSMarsDegree_spin.setToolTip(QtGui.QApplication.translate("Dialog", "Depending on the chosen response surface, you can\n"
"customize its parameter(s). A higher value will result\n"
"in a more accurate response surface, but at the expense\n"
"of longer runtime.", None, QtGui.QApplication.UnicodeUTF8))
        self.expertUserRegression_static.setText(QtGui.QApplication.translate("Dialog", "User Regression File:", None, QtGui.QApplication.UnicodeUTF8))
        self.expertUserRegressionFile_edit.setToolTip(QtGui.QApplication.translate("Dialog", "For the user-regression response surface, an executable\n"
"that reads the inputs and writes the output is required.", None, QtGui.QApplication.UnicodeUTF8))
        self.expertUserRegressionBrowse_button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Validate:", None, QtGui.QApplication.UnicodeUTF8))
        self.testSet_chkbox.setText(QtGui.QApplication.translate("Dialog", "Use separate test set", None, QtGui.QApplication.UnicodeUTF8))
        self.testSetBrowse_button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.RSValidate_button.setToolTip(QtGui.QApplication.translate("Dialog", "The results will be a histogram of response surface errors\n"
"and a scatterplot of actual vs. predicted values.\n"
"If the response surface is a good fit, (1) the histogram bars\n"
" should be centered near zero, and (2) the scatterplot\n"
"should resemble a diagonal line.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSValidate_button.setText(QtGui.QApplication.translate("Dialog", "Validate", None, QtGui.QApplication.UnicodeUTF8))
        self.RSValidationGroups_static.setText(QtGui.QApplication.translate("Dialog", "Number of Cross-Validation Groups:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSCodeBrowse_button.setToolTip(QtGui.QApplication.translate("Dialog", "Click to save the trained response surface as a Python\n"
"script that reads the inputs and writes the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSCodeBrowse_button.setText(QtGui.QApplication.translate("Dialog", "Save RS interpolation code to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.RSViz_static.setText(QtGui.QApplication.translate("Dialog", "Visualize RS:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSViz_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSViz_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSViz_combo3.setToolTip(QtGui.QApplication.translate("Dialog", "Select unique input(s) to plot against the output.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSViz_button.setToolTip(QtGui.QApplication.translate("Dialog", "The resulting plots will show output values\n"
"interpolated from the trained response surface.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSViz_button.setText(QtGui.QApplication.translate("Dialog", "Visualize", None, QtGui.QApplication.UnicodeUTF8))
        self.RSVizMax_chkbox.setToolTip(QtGui.QApplication.translate("Dialog", "To focus onto a specific range of the output,\n"
"restrict the upper and lower thresholds.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSVizMax_chkbox.setText(QtGui.QApplication.translate("Dialog", "Upper Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSVizMin_chkbox.setToolTip(QtGui.QApplication.translate("Dialog", "To focus onto a specific range of the output,\n"
"restrict the upper and lower thresholds.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSVizMin_chkbox.setText(QtGui.QApplication.translate("Dialog", "Lower Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_static.setText(QtGui.QApplication.translate("Dialog", "Choose UQ Analysis:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_combo1.setToolTip(QtGui.QApplication.translate("Dialog", "Select analysis type.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_combo1.setItemText(0, QtGui.QApplication.translate("Dialog", "Uncertainty Analysis ->", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_combo1.setItemText(1, QtGui.QApplication.translate("Dialog", "Sensitivity Analysis ->", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_combo1.setItemText(2, QtGui.QApplication.translate("Dialog", "Point Evaluation", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_combo2.setToolTip(QtGui.QApplication.translate("Dialog", "Select analysis subtype, if available.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_button.setToolTip(QtGui.QApplication.translate("Dialog", "Analysis will be performed on a much larger ensemble,\n"
"where the output values are interpolated from\n"
"the response surface. The results should be smoother\n"
"than those achieved through ensemble data analysis.", None, QtGui.QApplication.UnicodeUTF8))
        self.RSAnalyze_button.setText(QtGui.QApplication.translate("Dialog", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.setToolTip(QtGui.QApplication.translate("Dialog", "Input probability distributions can be modified\n"
"based on prior knowledge about the input parameters.", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Input Name", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "PDF Param1", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "PDF Param2", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.RSLegendre_static.setText(QtGui.QApplication.translate("Dialog", "Legendre Polynomial Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.RSLegendre_spin.setToolTip(QtGui.QApplication.translate("Dialog", "Depending on the chosen response surface, you can\n"
"customize its parameter(s). A higher value will result\n"
"in a more accurate response surface, but at the expense\n"
"of longer runtime.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Bayesian Inference", None, QtGui.QApplication.UnicodeUTF8))
        self.expertInfer_button.setToolTip(QtGui.QApplication.translate("Dialog", "Click to open separate dialog for Bayesian Inference.", None, QtGui.QApplication.UnicodeUTF8))
        self.expertInfer_button.setText(QtGui.QApplication.translate("Dialog", "Infer...", None, QtGui.QApplication.UnicodeUTF8))

from foqus_lib.gui.uq.InputPriorTable import InputPriorTable
from foqus_lib.gui.uq.RSCombos import LegendreSpinBox, RSCombo2, RSCombo1, MarsDegreeSpinBox, MarsBasisSpinBox
