# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InferenceDialog_UI.ui'
#
# Created: Thu Mar 10 11:34:32 2016
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 835)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputInstruction = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.outputInstruction.setFont(font)
        self.outputInstruction.setWordWrap(True)
        self.outputInstruction.setObjectName("outputInstruction")
        self.gridLayout_2.addWidget(self.outputInstruction, 0, 0, 1, 1)
        self.output_table = QtGui.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.output_table.setFont(font)
        self.output_table.setObjectName("output_table")
        self.output_table.setColumnCount(7)
        self.output_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.output_table.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.output_table, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.inputPrior_table = InputPriorTable(self.groupBox_2)
        self.inputPrior_table.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.inputPrior_table.setFont(font)
        self.inputPrior_table.setObjectName("inputPrior_table")
        self.inputPrior_table.setColumnCount(9)
        self.inputPrior_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.inputPrior_table.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.inputPrior_table, 1, 0, 1, 1)
        self.inputInstruction = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.inputInstruction.setFont(font)
        self.inputInstruction.setWordWrap(True)
        self.inputInstruction.setObjectName("inputInstruction")
        self.gridLayout.addWidget(self.inputInstruction, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.numExperiments_static = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.numExperiments_static.setFont(font)
        self.numExperiments_static.setObjectName("numExperiments_static")
        self.horizontalLayout.addWidget(self.numExperiments_static)
        self.numExperiments_spin = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.numExperiments_spin.setFont(font)
        self.numExperiments_spin.setMinimum(1)
        self.numExperiments_spin.setMaximum(999999999)
        self.numExperiments_spin.setObjectName("numExperiments_spin")
        self.horizontalLayout.addWidget(self.numExperiments_spin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loadObs_button = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.loadObs_button.setFont(font)
        self.loadObs_button.setObjectName("loadObs_button")
        self.horizontalLayout.addWidget(self.loadObs_button)
        self.saveObs_button = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.saveObs_button.setFont(font)
        self.saveObs_button.setObjectName("saveObs_button")
        self.horizontalLayout.addWidget(self.saveObs_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.obsInstruction = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.obsInstruction.setFont(font)
        self.obsInstruction.setWordWrap(True)
        self.obsInstruction.setObjectName("obsInstruction")
        self.gridLayout_3.addWidget(self.obsInstruction, 1, 0, 1, 1)
        self.obs_table = QtGui.QTableWidget(self.groupBox)
        self.obs_table.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.obs_table.setFont(font)
        self.obs_table.setObjectName("obs_table")
        self.obs_table.setColumnCount(6)
        self.obs_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.obs_table.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.obs_table, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 2)
        self.saveInstruction = QtGui.QLabel(Dialog)
        self.saveInstruction.setObjectName("saveInstruction")
        self.gridLayout_5.addWidget(self.saveInstruction, 2, 0, 1, 2)
        self.horizontalLayout_infSave = QtGui.QHBoxLayout()
        self.horizontalLayout_infSave.setObjectName("horizontalLayout_infSave")
        self.infSave_chkbox = QtGui.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.infSave_chkbox.setFont(font)
        self.infSave_chkbox.setMouseTracking(False)
        self.infSave_chkbox.setObjectName("infSave_chkbox")
        self.horizontalLayout_infSave.addWidget(self.infSave_chkbox)
        self.infSave_edit = QtGui.QLineEdit(Dialog)
        self.infSave_edit.setReadOnly(True)
        self.infSave_edit.setObjectName("infSave_edit")
        self.horizontalLayout_infSave.addWidget(self.infSave_edit)
        self.infSave_button = QtGui.QPushButton(Dialog)
        self.infSave_button.setObjectName("infSave_button")
        self.horizontalLayout_infSave.addWidget(self.infSave_button)
        self.gridLayout_5.addLayout(self.horizontalLayout_infSave, 3, 0, 1, 1)
        self.horizontalLayout_discrepancySave = QtGui.QHBoxLayout()
        self.horizontalLayout_discrepancySave.setObjectName("horizontalLayout_discrepancySave")
        self.discrepancy_chkbox = QtGui.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.discrepancy_chkbox.setFont(font)
        self.discrepancy_chkbox.setObjectName("discrepancy_chkbox")
        self.horizontalLayout_discrepancySave.addWidget(self.discrepancy_chkbox)
        self.discrepancySave_chkbox = QtGui.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.discrepancySave_chkbox.setFont(font)
        self.discrepancySave_chkbox.setMouseTracking(False)
        self.discrepancySave_chkbox.setObjectName("discrepancySave_chkbox")
        self.horizontalLayout_discrepancySave.addWidget(self.discrepancySave_chkbox)
        self.discrepancySave_edit = QtGui.QLineEdit(Dialog)
        self.discrepancySave_edit.setReadOnly(True)
        self.discrepancySave_edit.setObjectName("discrepancySave_edit")
        self.horizontalLayout_discrepancySave.addWidget(self.discrepancySave_edit)
        self.discrepancySave_button = QtGui.QPushButton(Dialog)
        self.discrepancySave_button.setObjectName("discrepancySave_button")
        self.horizontalLayout_discrepancySave.addWidget(self.discrepancySave_button)
        self.gridLayout_5.addLayout(self.horizontalLayout_discrepancySave, 4, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(351, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.inferInstruction = QtGui.QLabel(Dialog)
        self.inferInstruction.setObjectName("inferInstruction")
        self.horizontalLayout_2.addWidget(self.inferInstruction)
        self.inf_button = QtGui.QPushButton(Dialog)
        self.inf_button.setObjectName("inf_button")
        self.horizontalLayout_2.addWidget(self.inf_button)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.replotInstruction = QtGui.QLabel(Dialog)
        self.replotInstruction.setMinimumSize(QtCore.QSize(450, 0))
        self.replotInstruction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.replotInstruction.setWordWrap(True)
        self.replotInstruction.setObjectName("replotInstruction")
        self.horizontalLayout_2.addWidget(self.replotInstruction)
        self.replot_button = QtGui.QPushButton(Dialog)
        self.replot_button.setObjectName("replot_button")
        self.horizontalLayout_2.addWidget(self.replot_button)
        self.close_button = QtGui.QPushButton(Dialog)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        spacerItem4 = QtGui.QSpacerItem(351, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.close_button, QtCore.SIGNAL("clicked()"), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Output Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputInstruction.setText(QtGui.QApplication.translate("Dialog", "1. Select the outputs that have been observed. (Distribution is assumed to be known through experiment or expert knowledge.) \n"
"2. For the observed outputs, select the response surface type. (Solvent Fit requires Solvent Fit Emulator)", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.setToolTip(QtGui.QApplication.translate("Dialog", "Designate a response surface for each observed output.", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Observed?", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Output Name", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Response Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "(cont\'d)", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Legendre Order", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "MARS # Basis Func\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.output_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "MARS Deg. of Interaction", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Input Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.setToolTip(QtGui.QApplication.translate("Dialog", "Designate input type:\n"
"Variable for uncertain inputs\n"
"Fixed for deterministic inputs\n"
"Design for control inputs that can vary from experiments", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Input Name", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Display?", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Fixed Value", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "PDF Param1", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "PDF Param2", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.inputPrior_table.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.inputInstruction.setText(QtGui.QApplication.translate("Dialog", "3. For each input, specify the type. Variable: change in value within an experiment.  Fixed: Same between all experiments.  Design: Fixed within each experiment, but different between experiments.\n"
"4. Select the variable inputs you want displayed in the final output.  (This only affects what is displayed, not the underlying numerical calculations. You can change this later and replot without redoing the calculations.)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Observations:", None, QtGui.QApplication.UnicodeUTF8))
        self.numExperiments_static.setText(QtGui.QApplication.translate("Dialog", "5. Select the number of experiments:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadObs_button.setText(QtGui.QApplication.translate("Dialog", "Load Observations File...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveObs_button.setText(QtGui.QApplication.translate("Dialog", "Save Observations File...", None, QtGui.QApplication.UnicodeUTF8))
        self.obsInstruction.setText(QtGui.QApplication.translate("Dialog", "6. Enter the values of the design inputs for each experiment.\n"
"7. Enter the observed mean and standard devation for each of those outputs.", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.setToolTip(QtGui.QApplication.translate("Dialog", "Enter the fixed value(s) of the design input(s) and\n"
"the statistics of the (noisy) observed output(s).", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Experiment 1", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Experiment 2", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Design Variable 1 Value", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Design Variable 2 Value", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Output 1 Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Output 1 Std Dev", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Output 2 Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.obs_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Output 2 Std Dev", None, QtGui.QApplication.UnicodeUTF8))
        self.saveInstruction.setText(QtGui.QApplication.translate("Dialog", "8. If it is desired to save the posterior input samples to a file for use later, check the box and set the name and location of the resulting file.", None, QtGui.QApplication.UnicodeUTF8))
        self.infSave_chkbox.setToolTip(QtGui.QApplication.translate("Dialog", "Click checkbox to save posterior samples as a PSUADE file.", None, QtGui.QApplication.UnicodeUTF8))
        self.infSave_chkbox.setText(QtGui.QApplication.translate("Dialog", "Save Posterior Input Samples to File:", None, QtGui.QApplication.UnicodeUTF8))
        self.infSave_button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.discrepancy_chkbox.setToolTip(QtGui.QApplication.translate("Dialog", "Apply discrepancy modeling when building response surface.", None, QtGui.QApplication.UnicodeUTF8))
        self.discrepancy_chkbox.setText(QtGui.QApplication.translate("Dialog", "Use Discrepancy", None, QtGui.QApplication.UnicodeUTF8))
        self.discrepancySave_chkbox.setToolTip(QtGui.QApplication.translate("Dialog", "Click checkbox to save discrepancy samples as a PSUADE file.", None, QtGui.QApplication.UnicodeUTF8))
        self.discrepancySave_chkbox.setText(QtGui.QApplication.translate("Dialog", "Save Discrepancy Input Samples to File:", None, QtGui.QApplication.UnicodeUTF8))
        self.discrepancySave_button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.inferInstruction.setText(QtGui.QApplication.translate("Dialog", "9. Click here:", None, QtGui.QApplication.UnicodeUTF8))
        self.inf_button.setToolTip(QtGui.QApplication.translate("Dialog", "Click this button to start/stop inference.", None, QtGui.QApplication.UnicodeUTF8))
        self.inf_button.setText(QtGui.QApplication.translate("Dialog", "Infer", None, QtGui.QApplication.UnicodeUTF8))
        self.replotInstruction.setText(QtGui.QApplication.translate("Dialog", "10. To change which inputs are displayed after step 6 without recalculating, select/deselect them as in Step 3.  Then click here:", None, QtGui.QApplication.UnicodeUTF8))
        self.replot_button.setToolTip(QtGui.QApplication.translate("Dialog", "You can plot a subset of inputs by designating which ones\n"
"to display in ‘Input Settings”.", None, QtGui.QApplication.UnicodeUTF8))
        self.replot_button.setText(QtGui.QApplication.translate("Dialog", "Replot", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

from foqus_lib.gui.uq.InputPriorTable import InputPriorTable
