# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimSetup_UI.ui'
#
# Created: Mon Sep 14 16:58:20 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(793, 626)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 5)
        self.samplePages = QtGui.QStackedWidget(Dialog)
        self.samplePages.setObjectName("samplePages")
        self.chooseSchemePage = QtGui.QWidget()
        self.chooseSchemePage.setObjectName("chooseSchemePage")
        self.gridLayout_2 = QtGui.QGridLayout(self.chooseSchemePage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.samplingTabs = QtGui.QTabWidget(self.chooseSchemePage)
        self.samplingTabs.setObjectName("samplingTabs")
        self.distTab = QtGui.QWidget()
        self.distTab.setObjectName("distTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.distTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.distTable = InputPriorTable(self.distTab)
        self.distTable.setMaximumSize(QtCore.QSize(100000, 1000000))
        self.distTable.setObjectName("distTable")
        self.distTable.setColumnCount(8)
        self.distTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.distTable.setHorizontalHeaderItem(7, item)
        self.gridLayout_3.addWidget(self.distTable, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.allFixedButton = QtGui.QPushButton(self.distTab)
        self.allFixedButton.setObjectName("allFixedButton")
        self.horizontalLayout_5.addWidget(self.allFixedButton)
        self.allVariableButton = QtGui.QPushButton(self.distTab)
        self.allVariableButton.setObjectName("allVariableButton")
        self.horizontalLayout_5.addWidget(self.allVariableButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.samplingTabs.addTab(self.distTab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.allSchemesRadio = QtGui.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allSchemesRadio.setFont(font)
        self.allSchemesRadio.setObjectName("allSchemesRadio")
        self.verticalLayout.addWidget(self.allSchemesRadio)
        self.paramScreenRadio = QtGui.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.paramScreenRadio.setFont(font)
        self.paramScreenRadio.setObjectName("paramScreenRadio")
        self.verticalLayout.addWidget(self.paramScreenRadio)
        self.otherRadio = QtGui.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.otherRadio.setFont(font)
        self.otherRadio.setObjectName("otherRadio")
        self.verticalLayout.addWidget(self.otherRadio)
        self.adaptiveRefineRadio = QtGui.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.adaptiveRefineRadio.setFont(font)
        self.adaptiveRefineRadio.setObjectName("adaptiveRefineRadio")
        self.verticalLayout.addWidget(self.adaptiveRefineRadio)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.schemesList = QtGui.QListWidget(self.tab_2)
        self.schemesList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.schemesList.setObjectName("schemesList")
        QtGui.QListWidgetItem(self.schemesList)
        QtGui.QListWidgetItem(self.schemesList)
        QtGui.QListWidgetItem(self.schemesList)
        self.gridLayout_4.addWidget(self.schemesList, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.numSamplesBox = QtGui.QSpinBox(self.tab_2)
        self.numSamplesBox.setMinimum(10)
        self.numSamplesBox.setMaximum(1000000)
        self.numSamplesBox.setProperty("value", 1000)
        self.numSamplesBox.setObjectName("numSamplesBox")
        self.horizontalLayout_4.addWidget(self.numSamplesBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.generateSamplesButton = QtGui.QPushButton(self.tab_2)
        self.generateSamplesButton.setObjectName("generateSamplesButton")
        self.horizontalLayout_2.addWidget(self.generateSamplesButton)
        self.generateStatusText = QtGui.QLabel(self.tab_2)
        self.generateStatusText.setObjectName("generateStatusText")
        self.horizontalLayout_2.addWidget(self.generateStatusText)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 4, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 1, 0, 1, 1)
        self.samplingTabs.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.samplingTabs, 0, 0, 1, 1)
        self.samplePages.addWidget(self.chooseSchemePage)
        self.loadSamplesPage = QtGui.QWidget()
        self.loadSamplesPage.setObjectName("loadSamplesPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.loadSamplesPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.loadSamplesPage)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 501, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sampleFileNameEdit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sampleFileNameEdit.setFont(font)
        self.sampleFileNameEdit.setObjectName("sampleFileNameEdit")
        self.horizontalLayout.addWidget(self.sampleFileNameEdit)
        self.browseButton = QtGui.QPushButton(self.layoutWidget)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.samplePages.addWidget(self.loadSamplesPage)
        self.adaptiveFSDataPage = QtGui.QWidget()
        self.adaptiveFSDataPage.setObjectName("adaptiveFSDataPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.adaptiveFSDataPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dataViewWidget = QtGui.QWidget(self.adaptiveFSDataPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataViewWidget.sizePolicy().hasHeightForWidth())
        self.dataViewWidget.setSizePolicy(sizePolicy)
        self.dataViewWidget.setObjectName("dataViewWidget")
        self.verticalLayout_5.addWidget(self.dataViewWidget)
        self.samplePages.addWidget(self.adaptiveFSDataPage)
        self.gridLayout.addWidget(self.samplePages, 5, 0, 1, 5)
        spacerItem7 = QtGui.QSpacerItem(143, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 6, 0, 1, 1)
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 6, 1, 1, 1)
        self.previewButton = QtGui.QPushButton(Dialog)
        self.previewButton.setObjectName("previewButton")
        self.gridLayout.addWidget(self.previewButton, 6, 2, 1, 1)
        self.doneButton = QtGui.QPushButton(Dialog)
        self.doneButton.setObjectName("doneButton")
        self.gridLayout.addWidget(self.doneButton, 6, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(95, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 6, 4, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chooseSchemeRadio = QtGui.QRadioButton(self.groupBox_2)
        self.chooseSchemeRadio.setChecked(True)
        self.chooseSchemeRadio.setObjectName("chooseSchemeRadio")
        self.verticalLayout_2.addWidget(self.chooseSchemeRadio)
        self.flowsheetDataRadio = QtGui.QRadioButton(self.groupBox_2)
        self.flowsheetDataRadio.setObjectName("flowsheetDataRadio")
        self.verticalLayout_2.addWidget(self.flowsheetDataRadio)
        self.loadSamplesRadio = QtGui.QRadioButton(self.groupBox_2)
        self.loadSamplesRadio.setObjectName("loadSamplesRadio")
        self.verticalLayout_2.addWidget(self.loadSamplesRadio)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.samplePages.setCurrentIndex(0)
        self.samplingTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.doneButton, self.previewButton)
        Dialog.setTabOrder(self.previewButton, self.cancelButton)
        Dialog.setTabOrder(self.cancelButton, self.samplingTabs)
        Dialog.setTabOrder(self.samplingTabs, self.distTable)
        Dialog.setTabOrder(self.distTable, self.allFixedButton)
        Dialog.setTabOrder(self.allFixedButton, self.allVariableButton)
        Dialog.setTabOrder(self.allVariableButton, self.sampleFileNameEdit)
        Dialog.setTabOrder(self.sampleFileNameEdit, self.browseButton)
        Dialog.setTabOrder(self.browseButton, self.allSchemesRadio)
        Dialog.setTabOrder(self.allSchemesRadio, self.paramScreenRadio)
        Dialog.setTabOrder(self.paramScreenRadio, self.otherRadio)
        Dialog.setTabOrder(self.otherRadio, self.adaptiveRefineRadio)
        Dialog.setTabOrder(self.adaptiveRefineRadio, self.schemesList)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Simulation Ensemble Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.samplingTabs.setToolTip(QtGui.QApplication.translate("Dialog", "Identify the input parameters with uncertainty and characterize their probability distributions.", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Param 1", None, QtGui.QApplication.UnicodeUTF8))
        self.distTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Param 2", None, QtGui.QApplication.UnicodeUTF8))
        self.allFixedButton.setToolTip(QtGui.QApplication.translate("Dialog", "Click to set all input parameters to fixed.", None, QtGui.QApplication.UnicodeUTF8))
        self.allFixedButton.setText(QtGui.QApplication.translate("Dialog", "All Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.allVariableButton.setToolTip(QtGui.QApplication.translate("Dialog", "Click to set all input parameters to variable.", None, QtGui.QApplication.UnicodeUTF8))
        self.allVariableButton.setText(QtGui.QApplication.translate("Dialog", "All Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.samplingTabs.setTabText(self.samplingTabs.indexOf(self.distTab), QtGui.QApplication.translate("Dialog", "Distributions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Different sampling schemes are required to achieve certain UQ tasks.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Show schemes:", None, QtGui.QApplication.UnicodeUTF8))
        self.allSchemesRadio.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.paramScreenRadio.setText(QtGui.QApplication.translate("Dialog", "For parameter screening only", None, QtGui.QApplication.UnicodeUTF8))
        self.otherRadio.setText(QtGui.QApplication.translate("Dialog", "For response surface analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.adaptiveRefineRadio.setText(QtGui.QApplication.translate("Dialog", "For adaptive response surface analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.schemesList.setToolTip(QtGui.QApplication.translate("Dialog", "Select the sampling scheme suitable for your analysis.\n"
"Each sampling scheme will fill the space differently.\n"
"You can always preview your ensemble after it is generated.", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.schemesList.isSortingEnabled()
        self.schemesList.setSortingEnabled(False)
        self.schemesList.item(0).setText(QtGui.QApplication.translate("Dialog", "Monte Carlo", None, QtGui.QApplication.UnicodeUTF8))
        self.schemesList.item(1).setText(QtGui.QApplication.translate("Dialog", "Quasi Monte Carlo", None, QtGui.QApplication.UnicodeUTF8))
        self.schemesList.item(2).setText(QtGui.QApplication.translate("Dialog", "METIS", None, QtGui.QApplication.UnicodeUTF8))
        self.schemesList.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "# of samples?", None, QtGui.QApplication.UnicodeUTF8))
        self.generateSamplesButton.setText(QtGui.QApplication.translate("Dialog", "Generate Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.generateStatusText.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.samplingTabs.setTabText(self.samplingTabs.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Sampling scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Load samples", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("Dialog", "Preview Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("Dialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Choose how to generate samples:", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseSchemeRadio.setToolTip(QtGui.QApplication.translate("Dialog", "Choose this option if you want to generate\n"
"a new ensemble.", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseSchemeRadio.setText(QtGui.QApplication.translate("Dialog", "Choose sampling scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.flowsheetDataRadio.setToolTip(QtGui.QApplication.translate("Dialog", "Choose this option if you have an existing\n"
"ensemble from your flowsheet.", None, QtGui.QApplication.UnicodeUTF8))
        self.flowsheetDataRadio.setText(QtGui.QApplication.translate("Dialog", "Load flowsheet samples", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSamplesRadio.setToolTip(QtGui.QApplication.translate("Dialog", "Choose this option if you have an existing\n"
"ensemble saved as a PSUADE file.", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSamplesRadio.setText(QtGui.QApplication.translate("Dialog", "Load all samples from a single file", None, QtGui.QApplication.UnicodeUTF8))

from foqus_lib.gui.uq.InputPriorTable import InputPriorTable
