name: Build docs
description: Build documentation
runs:
  using: composite
  steps:
    - name: Install docs dependencies
      shell: bash
      run: |
        echo '::group::Output of "pip install" commands'
        pip_cmd="pip --no-cache-dir install --progress-bar off"
        $pip_cmd --upgrade pip wheel setuptools
        $pip_cmd -r requirements-dev.txt
        echo '::endgroup::'
    - name: Build docs
      shell: bash
      working-directory: docs/
      run: |
        echo '::group::Output of make'
        make CLOPTS="-qW --keep-going" clean dummy
        echo '::endgroup::'
