# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# the build.os and build.tools section is mandatory
build:
  os: ubuntu-20.04  # for consistency, matches the one used for CI
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
    fail_on_warning: true
    configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements-dev.txt

# Build all formats
formats:
    - pdf
    - htmlzip
