[files]
extend-exclude = [
    "*.smp",
    "*.ui",
    "*.html",
    "*.css",
    "*.js",
    "*.svg",
    "*.foqus",
    "*.bkp",
    "*.acmf",
    "*.for",
    "*.his",
    "*.def",
    "*.ads",
    "*.pt",
    "*.pkl",
    "*.R",
    "*.json",
]

[default.extend-words]
# Ignore IDAES
IDAES = "IDAES"
FO = "FO"  # TODO: probably an abbreviation?
sur = "sur"  # abbreviation for 'surrogate'
nd = "nd"  # used as a variable name in sdoeAnalysisDialog
astroid = "astroid"  # Python package name