# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help\helpBrowser_UI.ui'
#
# Created: Mon Jan 25 09:49:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_helpBrowser(object):
    def setupUi(self, helpBrowser):
        helpBrowser.setObjectName("helpBrowser")
        helpBrowser.resize(881, 734)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.HelpBrowser = QtGui.QWidget()
        self.HelpBrowser.setObjectName("HelpBrowser")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.HelpBrowser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.webviewLayout = QtGui.QVBoxLayout()
        self.webviewLayout.setObjectName("webviewLayout")
        self.verticalLayout_2.addLayout(self.webviewLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backButton = QtGui.QPushButton(self.HelpBrowser)
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(24, 24))
        self.backButton.setFlat(True)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.forwardButton = QtGui.QPushButton(self.HelpBrowser)
        self.forwardButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon1)
        self.forwardButton.setIconSize(QtCore.QSize(24, 24))
        self.forwardButton.setFlat(True)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.contentsButton = QtGui.QPushButton(self.HelpBrowser)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.contentsButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.contentsButton.setFont(font)
        self.contentsButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.contentsButton.setFlat(False)
        self.contentsButton.setObjectName("contentsButton")
        self.horizontalLayout.addWidget(self.contentsButton)
        self.aboutButton = QtGui.QPushButton(self.HelpBrowser)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.aboutButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.aboutButton.setFont(font)
        self.aboutButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.aboutButton.setFlat(False)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout.addWidget(self.aboutButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.HelpBrowser, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pycodeEdit = QtGui.QPlainTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.pycodeEdit.setFont(font)
        self.pycodeEdit.setObjectName("pycodeEdit")
        self.verticalLayout_5.addWidget(self.pycodeEdit)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.execButton = QtGui.QPushButton(self.tab_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.execButton.setIcon(icon2)
        self.execButton.setObjectName("execButton")
        self.horizontalLayout_2.addWidget(self.execButton)
        self.stopButton = QtGui.QPushButton(self.tab_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.ccButton = QtGui.QPushButton(self.tab_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ccButton.setIcon(icon4)
        self.ccButton.setObjectName("ccButton")
        self.horizontalLayout_2.addWidget(self.ccButton)
        self.loadButton = QtGui.QPushButton(self.tab_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/load.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadButton.setIcon(icon5)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.saveButton = QtGui.QPushButton(self.tab_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon6)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.resEdit = QtGui.QPlainTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.resEdit.setFont(font)
        self.resEdit.setReadOnly(True)
        self.resEdit.setObjectName("resEdit")
        self.verticalLayout_4.addWidget(self.resEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.crButton = QtGui.QPushButton(self.groupBox_2)
        self.crButton.setIcon(icon4)
        self.crButton.setObjectName("crButton")
        self.horizontalLayout_3.addWidget(self.crButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.logView = QtGui.QTextBrowser(self.tab)
        self.logView.setObjectName("logView")
        self.verticalLayout_6.addWidget(self.logView)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clearLogButton = QtGui.QPushButton(self.tab)
        self.clearLogButton.setObjectName("clearLogButton")
        self.horizontalLayout_4.addWidget(self.clearLogButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        helpBrowser.setWidget(self.dockWidgetContents)

        self.retranslateUi(helpBrowser)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(helpBrowser)

    def retranslateUi(self, helpBrowser):
        helpBrowser.setWindowTitle(QtGui.QApplication.translate("helpBrowser", "Help Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.backButton.setToolTip(QtGui.QApplication.translate("helpBrowser", "<html><head/><body><p>Back</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.forwardButton.setToolTip(QtGui.QApplication.translate("helpBrowser", "<html><head/><body><p>Forward</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.contentsButton.setText(QtGui.QApplication.translate("helpBrowser", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setText(QtGui.QApplication.translate("helpBrowser", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HelpBrowser), QtGui.QApplication.translate("helpBrowser", "Help Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("helpBrowser", "Python Code (executes in FOQUS session object)", None, QtGui.QApplication.UnicodeUTF8))
        self.execButton.setText(QtGui.QApplication.translate("helpBrowser", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("helpBrowser", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.ccButton.setText(QtGui.QApplication.translate("helpBrowser", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("helpBrowser", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("helpBrowser", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("helpBrowser", "Result (displays contents of res when complete)", None, QtGui.QApplication.UnicodeUTF8))
        self.crButton.setText(QtGui.QApplication.translate("helpBrowser", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("helpBrowser", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.clearLogButton.setText(QtGui.QApplication.translate("helpBrowser", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("helpBrowser", "Log Viewer", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
