# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dash_UI.ui'
#
# Created: Thu Feb 26 19:44:42 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dash(object):
    def setupUi(self, Dash):
        Dash.setObjectName("Dash")
        Dash.resize(810, 638)
        Dash.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dash.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dash.setFont(font)
        Dash.setFrameShape(QtGui.QFrame.NoFrame)
        Dash.setFrameShadow(QtGui.QFrame.Plain)
        self.verticalLayout = QtGui.QVBoxLayout(Dash)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dash)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.versionBox = QtGui.QLineEdit(self.tab)
        self.versionBox.setEnabled(True)
        self.versionBox.setObjectName("versionBox")
        self.gridLayout_2.addWidget(self.versionBox, 1, 2, 1, 1)
        self.idBox = QtGui.QLineEdit(self.tab)
        self.idBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idBox.setFont(font)
        self.idBox.setObjectName("idBox")
        self.gridLayout_2.addWidget(self.idBox, 4, 2, 1, 1)
        self.creationTimeBox = QtGui.QLineEdit(self.tab)
        self.creationTimeBox.setEnabled(False)
        self.creationTimeBox.setObjectName("creationTimeBox")
        self.gridLayout_2.addWidget(self.creationTimeBox, 5, 2, 1, 1)
        self.modTimeBox = QtGui.QLineEdit(self.tab)
        self.modTimeBox.setEnabled(False)
        self.modTimeBox.setObjectName("modTimeBox")
        self.gridLayout_2.addWidget(self.modTimeBox, 6, 2, 1, 1)
        self.sessionNameEdit = QtGui.QLineEdit(self.tab)
        self.sessionNameEdit.setObjectName("sessionNameEdit")
        self.gridLayout_2.addWidget(self.sessionNameEdit, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.confCombo = QtGui.QComboBox(self.tab)
        self.confCombo.setObjectName("confCombo")
        self.confCombo.addItem("")
        self.confCombo.addItem("")
        self.confCombo.addItem("")
        self.gridLayout_2.addWidget(self.confCombo, 3, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.superscriptButton = QtGui.QPushButton(self.tab_2)
        self.superscriptButton.setEnabled(True)
        self.superscriptButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/superscript.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.superscriptButton.setIcon(icon)
        self.superscriptButton.setIconSize(QtCore.QSize(24, 24))
        self.superscriptButton.setCheckable(True)
        self.superscriptButton.setFlat(True)
        self.superscriptButton.setObjectName("superscriptButton")
        self.horizontalLayout_3.addWidget(self.superscriptButton)
        self.subscriptButton = QtGui.QPushButton(self.tab_2)
        self.subscriptButton.setEnabled(True)
        self.subscriptButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/suberscript.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.subscriptButton.setIcon(icon1)
        self.subscriptButton.setIconSize(QtCore.QSize(24, 24))
        self.subscriptButton.setCheckable(True)
        self.subscriptButton.setFlat(True)
        self.subscriptButton.setObjectName("subscriptButton")
        self.horizontalLayout_3.addWidget(self.subscriptButton)
        self.boldButton = QtGui.QPushButton(self.tab_2)
        self.boldButton.setEnabled(True)
        self.boldButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/bold.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.boldButton.setIcon(icon2)
        self.boldButton.setIconSize(QtCore.QSize(24, 24))
        self.boldButton.setCheckable(True)
        self.boldButton.setFlat(True)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout_3.addWidget(self.boldButton)
        self.underlineButton = QtGui.QPushButton(self.tab_2)
        self.underlineButton.setEnabled(True)
        self.underlineButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/underline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.underlineButton.setIcon(icon3)
        self.underlineButton.setIconSize(QtCore.QSize(24, 24))
        self.underlineButton.setCheckable(True)
        self.underlineButton.setFlat(True)
        self.underlineButton.setObjectName("underlineButton")
        self.horizontalLayout_3.addWidget(self.underlineButton)
        self.overlineButton = QtGui.QPushButton(self.tab_2)
        self.overlineButton.setEnabled(True)
        self.overlineButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/overline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.overlineButton.setIcon(icon4)
        self.overlineButton.setIconSize(QtCore.QSize(24, 24))
        self.overlineButton.setCheckable(True)
        self.overlineButton.setFlat(True)
        self.overlineButton.setObjectName("overlineButton")
        self.horizontalLayout_3.addWidget(self.overlineButton)
        self.fontButton = QtGui.QPushButton(self.tab_2)
        self.fontButton.setEnabled(True)
        self.fontButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/font.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fontButton.setIcon(icon5)
        self.fontButton.setIconSize(QtCore.QSize(24, 24))
        self.fontButton.setFlat(True)
        self.fontButton.setObjectName("fontButton")
        self.horizontalLayout_3.addWidget(self.fontButton)
        self.colorButton = QtGui.QPushButton(self.tab_2)
        self.colorButton.setEnabled(True)
        self.colorButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/color.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.colorButton.setIcon(icon6)
        self.colorButton.setIconSize(QtCore.QSize(24, 24))
        self.colorButton.setFlat(True)
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout_3.addWidget(self.colorButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.textEdit = QtGui.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.buttonBox = QtGui.QDialogButtonBox(self.tab_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.changeLogEdit = QtGui.QTextEdit(self.tab_3)
        self.changeLogEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.changeLogEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.changeLogEdit.setObjectName("changeLogEdit")
        self.verticalLayout_8.addWidget(self.changeLogEdit)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_9.setBuddy(self.versionBox)
        self.label_5.setBuddy(self.idBox)
        self.label_8.setBuddy(self.modTimeBox)
        self.label_7.setBuddy(self.creationTimeBox)

        self.retranslateUi(Dash)
        self.tabWidget.setCurrentIndex(0)
        self.confCombo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dash)

    def retranslateUi(self, Dash):
        Dash.setWindowTitle(QtGui.QApplication.translate("Dash", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dash", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dash", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dash", "Modification Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dash", "Creation Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dash", "Session Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.confCombo.setItemText(0, QtGui.QApplication.translate("Dash", "experimental", None, QtGui.QApplication.UnicodeUTF8))
        self.confCombo.setItemText(1, QtGui.QApplication.translate("Dash", "testing", None, QtGui.QApplication.UnicodeUTF8))
        self.confCombo.setItemText(2, QtGui.QApplication.translate("Dash", "production", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dash", "Confidence:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dash", "(generated)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dash", "(required)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dash", "(generated)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dash", "(generated)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dash", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.superscriptButton.setToolTip(QtGui.QApplication.translate("Dash", "<html><head/><body><p>Superscript</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.subscriptButton.setToolTip(QtGui.QApplication.translate("Dash", "<html><head/><body><p>Subscript</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setToolTip(QtGui.QApplication.translate("Dash", "<html><head/><body><p>Bold</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.overlineButton.setToolTip(QtGui.QApplication.translate("Dash", "<html><head/><body><p>Overline</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fontButton.setToolTip(QtGui.QApplication.translate("Dash", "<html><head/><body><p>Select font</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.colorButton.setToolTip(QtGui.QApplication.translate("Dash", "<html><head/><body><p>Select color</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dash", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dash", "Change Log", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
