# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessionDescriptionEdit_UI.ui'
#
# Created: Fri Mar 27 20:26:00 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_sessionDescriptionDialog(object):
    def setupUi(self, sessionDescriptionDialog):
        sessionDescriptionDialog.setObjectName("sessionDescriptionDialog")
        sessionDescriptionDialog.resize(667, 479)
        sessionDescriptionDialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(sessionDescriptionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.superscriptButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.superscriptButton.setEnabled(True)
        self.superscriptButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/superscript.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.superscriptButton.setIcon(icon)
        self.superscriptButton.setIconSize(QtCore.QSize(24, 24))
        self.superscriptButton.setCheckable(True)
        self.superscriptButton.setFlat(True)
        self.superscriptButton.setObjectName("superscriptButton")
        self.horizontalLayout.addWidget(self.superscriptButton)
        self.subscriptButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.subscriptButton.setEnabled(True)
        self.subscriptButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/suberscript.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.subscriptButton.setIcon(icon1)
        self.subscriptButton.setIconSize(QtCore.QSize(24, 24))
        self.subscriptButton.setCheckable(True)
        self.subscriptButton.setFlat(True)
        self.subscriptButton.setObjectName("subscriptButton")
        self.horizontalLayout.addWidget(self.subscriptButton)
        self.boldButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.boldButton.setEnabled(True)
        self.boldButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/bold.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.boldButton.setIcon(icon2)
        self.boldButton.setIconSize(QtCore.QSize(24, 24))
        self.boldButton.setCheckable(True)
        self.boldButton.setFlat(True)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout.addWidget(self.boldButton)
        self.underlineButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.underlineButton.setEnabled(True)
        self.underlineButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/underline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.underlineButton.setIcon(icon3)
        self.underlineButton.setIconSize(QtCore.QSize(24, 24))
        self.underlineButton.setCheckable(True)
        self.underlineButton.setFlat(True)
        self.underlineButton.setObjectName("underlineButton")
        self.horizontalLayout.addWidget(self.underlineButton)
        self.overlineButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.overlineButton.setEnabled(True)
        self.overlineButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/overline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.overlineButton.setIcon(icon4)
        self.overlineButton.setIconSize(QtCore.QSize(24, 24))
        self.overlineButton.setCheckable(True)
        self.overlineButton.setFlat(True)
        self.overlineButton.setObjectName("overlineButton")
        self.horizontalLayout.addWidget(self.overlineButton)
        self.fontButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.fontButton.setEnabled(True)
        self.fontButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/font.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fontButton.setIcon(icon5)
        self.fontButton.setIconSize(QtCore.QSize(24, 24))
        self.fontButton.setFlat(True)
        self.fontButton.setObjectName("fontButton")
        self.horizontalLayout.addWidget(self.fontButton)
        self.colorButton = QtGui.QPushButton(sessionDescriptionDialog)
        self.colorButton.setEnabled(True)
        self.colorButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/color.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.colorButton.setIcon(icon6)
        self.colorButton.setIconSize(QtCore.QSize(24, 24))
        self.colorButton.setFlat(True)
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout.addWidget(self.colorButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtGui.QTextEdit(sessionDescriptionDialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonBox = QtGui.QDialogButtonBox(sessionDescriptionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(sessionDescriptionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), sessionDescriptionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), sessionDescriptionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(sessionDescriptionDialog)

    def retranslateUi(self, sessionDescriptionDialog):
        sessionDescriptionDialog.setWindowTitle(QtGui.QApplication.translate("sessionDescriptionDialog", "Session Description Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.superscriptButton.setToolTip(QtGui.QApplication.translate("sessionDescriptionDialog", "<html><head/><body><p>Superscript</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.subscriptButton.setToolTip(QtGui.QApplication.translate("sessionDescriptionDialog", "<html><head/><body><p>Subscript</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setToolTip(QtGui.QApplication.translate("sessionDescriptionDialog", "<html><head/><body><p>Bold</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.overlineButton.setToolTip(QtGui.QApplication.translate("sessionDescriptionDialog", "<html><head/><body><p>Overline</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fontButton.setToolTip(QtGui.QApplication.translate("sessionDescriptionDialog", "<html><head/><body><p>Select font</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.colorButton.setToolTip(QtGui.QApplication.translate("sessionDescriptionDialog", "<html><head/><body><p>Select color</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
