# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main\settingsFrame_UI.ui'
#
# Created: Tue Feb 02 11:48:32 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settingsFrame(object):
    def setupUi(self, settingsFrame):
        settingsFrame.setObjectName("settingsFrame")
        settingsFrame.resize(690, 613)
        settingsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        settingsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_6 = QtGui.QVBoxLayout(settingsFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(settingsFrame)
        self.tabWidget.setObjectName("tabWidget")
        self.FOQUS = QtGui.QWidget()
        self.FOQUS.setObjectName("FOQUS")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.FOQUS)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settingsInWDirCheck = QtGui.QCheckBox(self.FOQUS)
        self.settingsInWDirCheck.setObjectName("settingsInWDirCheck")
        self.verticalLayout_4.addWidget(self.settingsInWDirCheck)
        self.dmfCheck = QtGui.QCheckBox(self.FOQUS)
        self.dmfCheck.setChecked(True)
        self.dmfCheck.setObjectName("dmfCheck")
        self.verticalLayout_4.addWidget(self.dmfCheck)
        self.saveBackCheck = QtGui.QCheckBox(self.FOQUS)
        self.saveBackCheck.setObjectName("saveBackCheck")
        self.verticalLayout_4.addWidget(self.saveBackCheck)
        self.saveSmallCheck = QtGui.QCheckBox(self.FOQUS)
        self.saveSmallCheck.setChecked(True)
        self.saveSmallCheck.setObjectName("saveSmallCheck")
        self.verticalLayout_4.addWidget(self.saveSmallCheck)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.simSinterBrowsButton = QtGui.QPushButton(self.FOQUS)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simSinterBrowsButton.setIcon(icon)
        self.simSinterBrowsButton.setObjectName("simSinterBrowsButton")
        self.gridLayout_2.addWidget(self.simSinterBrowsButton, 3, 2, 1, 1)
        self.wdirBrowseButton = QtGui.QPushButton(self.FOQUS)
        self.wdirBrowseButton.setIcon(icon)
        self.wdirBrowseButton.setObjectName("wdirBrowseButton")
        self.gridLayout_2.addWidget(self.wdirBrowseButton, 1, 2, 1, 1)
        self.psuadeEdit = QtGui.QLineEdit(self.FOQUS)
        self.psuadeEdit.setObjectName("psuadeEdit")
        self.gridLayout_2.addWidget(self.psuadeEdit, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.FOQUS)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 1)
        self.sinterConfigEdit = QtGui.QLineEdit(self.FOQUS)
        self.sinterConfigEdit.setObjectName("sinterConfigEdit")
        self.gridLayout_2.addWidget(self.sinterConfigEdit, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.FOQUS)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        self.psuadeBrowseButton = QtGui.QPushButton(self.FOQUS)
        self.psuadeBrowseButton.setIcon(icon)
        self.psuadeBrowseButton.setObjectName("psuadeBrowseButton")
        self.gridLayout_2.addWidget(self.psuadeBrowseButton, 2, 2, 1, 1)
        self.wdirEdit = QtGui.QLineEdit(self.FOQUS)
        self.wdirEdit.setObjectName("wdirEdit")
        self.gridLayout_2.addWidget(self.wdirEdit, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.FOQUS)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.FOQUS)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 0, 1, 1)
        self.runMethodCombo = QtGui.QComboBox(self.FOQUS)
        self.runMethodCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.runMethodCombo.setObjectName("runMethodCombo")
        self.runMethodCombo.addItem("")
        self.runMethodCombo.addItem("")
        self.gridLayout_2.addWidget(self.runMethodCombo, 0, 1, 1, 1)
        self.alamoPathEdit = QtGui.QLineEdit(self.FOQUS)
        self.alamoPathEdit.setObjectName("alamoPathEdit")
        self.gridLayout_2.addWidget(self.alamoPathEdit, 4, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.FOQUS)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 4, 0, 1, 1)
        self.alamoPathButton = QtGui.QPushButton(self.FOQUS)
        self.alamoPathButton.setIcon(icon)
        self.alamoPathButton.setObjectName("alamoPathButton")
        self.gridLayout_2.addWidget(self.alamoPathButton, 4, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.FOQUS)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 5, 0, 1, 1)
        self.rScriptPath = QtGui.QLineEdit(self.FOQUS)
        self.rScriptPath.setObjectName("rScriptPath")
        self.gridLayout_2.addWidget(self.rScriptPath, 5, 1, 1, 1)
        self.rScriptPathButton = QtGui.QPushButton(self.FOQUS)
        self.rScriptPathButton.setIcon(icon)
        self.rScriptPathButton.setObjectName("rScriptPathButton")
        self.gridLayout_2.addWidget(self.rScriptPathButton, 5, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.FOQUS)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 0, 1, 1)
        self.javaHomeEdit = QtGui.QLineEdit(self.FOQUS)
        self.javaHomeEdit.setObjectName("javaHomeEdit")
        self.gridLayout_2.addWidget(self.javaHomeEdit, 6, 1, 1, 1)
        self.javaHomeButton = QtGui.QPushButton(self.FOQUS)
        self.javaHomeButton.setIcon(icon)
        self.javaHomeButton.setObjectName("javaHomeButton")
        self.gridLayout_2.addWidget(self.javaHomeButton, 6, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabWidget.addTab(self.FOQUS, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.testLite = QtGui.QPushButton(self.groupBox_4)
        self.testLite.setObjectName("testLite")
        self.horizontalLayout_13.addWidget(self.testLite)
        self.startLite = QtGui.QPushButton(self.groupBox_4)
        self.startLite.setObjectName("startLite")
        self.horizontalLayout_13.addWidget(self.startLite)
        self.stopLite = QtGui.QPushButton(self.groupBox_4)
        self.stopLite.setObjectName("stopLite")
        self.horizontalLayout_13.addWidget(self.stopLite)
        self.changePort = QtGui.QPushButton(self.groupBox_4)
        self.changePort.setObjectName("changePort")
        self.horizontalLayout_13.addWidget(self.changePort)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.turbLiteHomeEdit = QtGui.QLineEdit(self.groupBox_4)
        self.turbLiteHomeEdit.setObjectName("turbLiteHomeEdit")
        self.gridLayout_3.addWidget(self.turbLiteHomeEdit, 1, 1, 1, 1)
        self.turbLiteBrowseButton = QtGui.QPushButton(self.groupBox_4)
        self.turbLiteBrowseButton.setIcon(icon)
        self.turbLiteBrowseButton.setObjectName("turbLiteBrowseButton")
        self.gridLayout_3.addWidget(self.turbLiteBrowseButton, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.aspenVersionCombo = QtGui.QComboBox(self.groupBox_4)
        self.aspenVersionCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.aspenVersionCombo.setObjectName("aspenVersionCombo")
        self.aspenVersionCombo.addItem("")
        self.aspenVersionCombo.addItem("")
        self.aspenVersionCombo.addItem("")
        self.gridLayout_3.addWidget(self.aspenVersionCombo, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.turbConfEdit = QtGui.QLineEdit(self.groupBox_4)
        self.turbConfEdit.setObjectName("turbConfEdit")
        self.gridLayout_3.addWidget(self.turbConfEdit, 2, 1, 1, 1)
        self.turbConfigEditButton = QtGui.QPushButton(self.groupBox_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turbConfigEditButton.setIcon(icon1)
        self.turbConfigEditButton.setObjectName("turbConfigEditButton")
        self.gridLayout_3.addWidget(self.turbConfigEditButton, 2, 3, 1, 1)
        self.turbBrowseButton = QtGui.QPushButton(self.groupBox_4)
        self.turbBrowseButton.setIcon(icon)
        self.turbBrowseButton.setObjectName("turbBrowseButton")
        self.gridLayout_3.addWidget(self.turbBrowseButton, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.verticalLayout_12.addWidget(self.groupBox_4)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem2)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.TestTurb = QtGui.QPushButton(self.groupBox_5)
        self.TestTurb.setObjectName("TestTurb")
        self.horizontalLayout_12.addWidget(self.TestTurb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.turbCConfigEditButton = QtGui.QPushButton(self.groupBox_5)
        self.turbCConfigEditButton.setIcon(icon1)
        self.turbCConfigEditButton.setObjectName("turbCConfigEditButton")
        self.gridLayout_4.addWidget(self.turbCConfigEditButton, 0, 3, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 0, 1, 1)
        self.turbConfClusterEdit = QtGui.QLineEdit(self.groupBox_5)
        self.turbConfClusterEdit.setObjectName("turbConfClusterEdit")
        self.gridLayout_4.addWidget(self.turbConfClusterEdit, 0, 1, 1, 1)
        self.turbCBrowseButton = QtGui.QPushButton(self.groupBox_5)
        self.turbCBrowseButton.setIcon(icon)
        self.turbCBrowseButton.setObjectName("turbCBrowseButton")
        self.gridLayout_4.addWidget(self.turbCBrowseButton, 0, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 1, 0, 1, 1)
        self.trIntervalEdit = QtGui.QLineEdit(self.groupBox_5)
        self.trIntervalEdit.setMaxLength(6)
        self.trIntervalEdit.setObjectName("trIntervalEdit")
        self.gridLayout_4.addWidget(self.trIntervalEdit, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 2, 0, 1, 1)
        self.trReSubEdit = QtGui.QLineEdit(self.groupBox_5)
        self.trReSubEdit.setObjectName("trReSubEdit")
        self.gridLayout_4.addWidget(self.trReSubEdit, 2, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.foqusLogLevelSlide = QtGui.QSlider(self.groupBox)
        self.foqusLogLevelSlide.setMinimum(1)
        self.foqusLogLevelSlide.setMaximum(5)
        self.foqusLogLevelSlide.setPageStep(1)
        self.foqusLogLevelSlide.setOrientation(QtCore.Qt.Vertical)
        self.foqusLogLevelSlide.setTickPosition(QtGui.QSlider.TicksBelow)
        self.foqusLogLevelSlide.setObjectName("foqusLogLevelSlide")
        self.horizontalLayout_4.addWidget(self.foqusLogLevelSlide)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.turbineLogLevelSlide = QtGui.QSlider(self.groupBox_2)
        self.turbineLogLevelSlide.setMinimum(1)
        self.turbineLogLevelSlide.setMaximum(5)
        self.turbineLogLevelSlide.setSingleStep(1)
        self.turbineLogLevelSlide.setPageStep(5)
        self.turbineLogLevelSlide.setTracking(True)
        self.turbineLogLevelSlide.setOrientation(QtCore.Qt.Vertical)
        self.turbineLogLevelSlide.setTickPosition(QtGui.QSlider.TicksBelow)
        self.turbineLogLevelSlide.setTickInterval(1)
        self.turbineLogLevelSlide.setObjectName("turbineLogLevelSlide")
        self.horizontalLayout.addWidget(self.turbineLogLevelSlide)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.foqusToConsoleCheck = QtGui.QCheckBox(self.groupBox_3)
        self.foqusToConsoleCheck.setText("")
        self.foqusToConsoleCheck.setObjectName("foqusToConsoleCheck")
        self.horizontalLayout_7.addWidget(self.foqusToConsoleCheck)
        spacerItem14 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 4, 1, 1)
        self.foqusLogFileEdit = QtGui.QLineEdit(self.groupBox_3)
        self.foqusLogFileEdit.setEnabled(False)
        self.foqusLogFileEdit.setObjectName("foqusLogFileEdit")
        self.gridLayout.addWidget(self.foqusLogFileEdit, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.turbineToFileCheck = QtGui.QCheckBox(self.groupBox_3)
        self.turbineToFileCheck.setText("")
        self.turbineToFileCheck.setObjectName("turbineToFileCheck")
        self.horizontalLayout_6.addWidget(self.turbineToFileCheck)
        spacerItem16 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.turbineLogFileEdit = QtGui.QLineEdit(self.groupBox_3)
        self.turbineLogFileEdit.setEnabled(False)
        self.turbineLogFileEdit.setObjectName("turbineLogFileEdit")
        self.gridLayout.addWidget(self.turbineLogFileEdit, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem17 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.foqusToFileCheck = QtGui.QCheckBox(self.groupBox_3)
        self.foqusToFileCheck.setText("")
        self.foqusToFileCheck.setObjectName("foqusToFileCheck")
        self.horizontalLayout_5.addWidget(self.foqusToFileCheck)
        spacerItem18 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 3, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem19 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.turbineToConsoleCheck = QtGui.QCheckBox(self.groupBox_3)
        self.turbineToConsoleCheck.setText("")
        self.turbineToConsoleCheck.setObjectName("turbineToConsoleCheck")
        self.horizontalLayout_8.addWidget(self.turbineToConsoleCheck)
        spacerItem20 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 4, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 1, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem22)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.logFormatEdit = QtGui.QLineEdit(self.tab_2)
        self.logFormatEdit.setObjectName("logFormatEdit")
        self.horizontalLayout_9.addWidget(self.logFormatEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.rotateLogCheck = QtGui.QCheckBox(self.tab_2)
        self.rotateLogCheck.setObjectName("rotateLogCheck")
        self.verticalLayout_5.addWidget(self.rotateLogCheck)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem23)
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_10.addWidget(self.label_25)
        self.logSizeEdit = QtGui.QLineEdit(self.tab_2)
        self.logSizeEdit.setEnabled(False)
        self.logSizeEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logSizeEdit.setObjectName("logSizeEdit")
        self.horizontalLayout_10.addWidget(self.logSizeEdit)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem25)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.revertButton = QtGui.QPushButton(settingsFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.revertButton.setIcon(icon2)
        self.revertButton.setObjectName("revertButton")
        self.horizontalLayout_3.addWidget(self.revertButton)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label_19.setBuddy(self.sinterConfigEdit)
        self.label_16.setBuddy(self.wdirEdit)
        self.label_18.setBuddy(self.psuadeEdit)
        self.label_27.setBuddy(self.runMethodCombo)
        self.label_24.setBuddy(self.alamoPathEdit)
        self.label_29.setBuddy(self.alamoPathEdit)
        self.label_22.setBuddy(self.javaHomeEdit)
        self.label_17.setBuddy(self.turbConfEdit)
        self.label_20.setBuddy(self.aspenVersionCombo)
        self.label_26.setBuddy(self.turbLiteHomeEdit)
        self.label_28.setBuddy(self.turbConfClusterEdit)
        self.label_31.setBuddy(self.trIntervalEdit)
        self.label_30.setBuddy(self.trReSubEdit)
        self.label_6.setBuddy(self.foqusLogLevelSlide)
        self.label_7.setBuddy(self.foqusLogLevelSlide)
        self.label_8.setBuddy(self.foqusLogLevelSlide)
        self.label_14.setBuddy(self.foqusLogLevelSlide)
        self.label_5.setBuddy(self.foqusLogLevelSlide)
        self.label_12.setBuddy(self.turbineLogLevelSlide)
        self.label_11.setBuddy(self.turbineLogLevelSlide)
        self.label_10.setBuddy(self.turbineLogLevelSlide)
        self.label_15.setBuddy(self.turbineLogLevelSlide)
        self.label_9.setBuddy(self.turbineLogLevelSlide)
        self.label_3.setBuddy(self.turbineLogFileEdit)
        self.label.setBuddy(self.foqusLogFileEdit)
        self.label_25.setBuddy(self.logSizeEdit)

        self.retranslateUi(settingsFrame)
        self.tabWidget.setCurrentIndex(0)
        self.aspenVersionCombo.setCurrentIndex(2)
        QtCore.QObject.connect(self.rotateLogCheck, QtCore.SIGNAL("clicked(bool)"), self.logSizeEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(settingsFrame)

    def retranslateUi(self, settingsFrame):
        settingsFrame.setWindowTitle(QtGui.QApplication.translate("settingsFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsInWDirCheck.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>When selected, the FOQUS settings are saved in the working directory in the file foqus.cfg.  When this file is present in the working directory it will override the settings found in %APPDATA%\\.foqus.cfg on Windows or $HOME/.foqus.cfg on other operating systems.  This options is most useful if you would like to run more than one copy of FOQUS at a time.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsInWDirCheck.setText(QtGui.QApplication.translate("settingsFrame", "Save settings to working directory", None, QtGui.QApplication.UnicodeUTF8))
        self.dmfCheck.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>This option turns on and off DMF features.  If you do not have a CCSI DMF server set up this option shuld be turned off.  To change this option a FOQUS restaart is required.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dmfCheck.setText(QtGui.QApplication.translate("settingsFrame", "Use DMF if available (Changing this settting requires a FOQUS restart)", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBackCheck.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>This option saves two copies on the FOQUS session file when saved.  One is the selected file name the other has the session unique identifier appened to the file name.  The unique identifier changes each time the session is saved, so this option can create a history of the FOQUS session and the user would be able to go back to any saved point.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBackCheck.setText(QtGui.QApplication.translate("settingsFrame", "Automatically create backup session file, when saving changes", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSmallCheck.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>This option reduces the session file size by eliminating whitespace.  The FOQUS files are in json format.  I can be useful to add white space to the file to make it more human readable.  In most cases, users will not wish to read a FOQUS session file, and the white sapce is unneeded.  White space can significantly increace the file size.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSmallCheck.setText(QtGui.QApplication.translate("settingsFrame", "Smaller session files, (no whitespace, hard to read if debugging, but much smaller)", None, QtGui.QApplication.UnicodeUTF8))
        self.simSinterBrowsButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.wdirBrowseButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("settingsFrame", "SimSinter Home", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("settingsFrame", "Working Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.psuadeBrowseButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("settingsFrame", "PSUADE EXE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("settingsFrame", "FOQUS Flowsheet Run Method", None, QtGui.QApplication.UnicodeUTF8))
        self.runMethodCombo.setItemText(0, QtGui.QApplication.translate("settingsFrame", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.runMethodCombo.setItemText(1, QtGui.QApplication.translate("settingsFrame", "Remote", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("settingsFrame", "ALAMO EXE", None, QtGui.QApplication.UnicodeUTF8))
        self.alamoPathButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("settingsFrame", "RScript Path", None, QtGui.QApplication.UnicodeUTF8))
        self.rScriptPathButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("settingsFrame", "Java Home", None, QtGui.QApplication.UnicodeUTF8))
        self.javaHomeEdit.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>Java home is required for the data managment framework.  If you are not using the data managment framework, this setting is ignored.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.javaHomeButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FOQUS), QtGui.QApplication.translate("settingsFrame", "FOQUS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("settingsFrame", "TurbineLite (Local)", None, QtGui.QApplication.UnicodeUTF8))
        self.testLite.setText(QtGui.QApplication.translate("settingsFrame", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.startLite.setText(QtGui.QApplication.translate("settingsFrame", "Start Service", None, QtGui.QApplication.UnicodeUTF8))
        self.stopLite.setText(QtGui.QApplication.translate("settingsFrame", "Stop Service", None, QtGui.QApplication.UnicodeUTF8))
        self.changePort.setText(QtGui.QApplication.translate("settingsFrame", "Change Port", None, QtGui.QApplication.UnicodeUTF8))
        self.turbLiteBrowseButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("settingsFrame", "Turbine Configuration (local)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("settingsFrame", "Aspen Version", None, QtGui.QApplication.UnicodeUTF8))
        self.aspenVersionCombo.setItemText(0, QtGui.QApplication.translate("settingsFrame", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.aspenVersionCombo.setItemText(1, QtGui.QApplication.translate("settingsFrame", "Asepn 7.3", None, QtGui.QApplication.UnicodeUTF8))
        self.aspenVersionCombo.setItemText(2, QtGui.QApplication.translate("settingsFrame", "Aspen 7.3.2 or higher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("settingsFrame", "TurbineLite Home", None, QtGui.QApplication.UnicodeUTF8))
        self.turbConfigEditButton.setText(QtGui.QApplication.translate("settingsFrame", "New/Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.turbBrowseButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("settingsFrame", "Turbine Gateway (Remote)", None, QtGui.QApplication.UnicodeUTF8))
        self.TestTurb.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>Test the Turbine configuration to be sure that the configured remote instance of Turbine is responding propery.  If the test fails, Turbine may not be running or the configuration may be wrong.  The test result should provide addtional information on any errors encountered.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TestTurb.setText(QtGui.QApplication.translate("settingsFrame", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.turbCConfigEditButton.setText(QtGui.QApplication.translate("settingsFrame", "New/Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>This is the configuration file for a remote instance of Turbine.  This contains the server URL, username, and password.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("settingsFrame", "Turbine Configuration (remote)", None, QtGui.QApplication.UnicodeUTF8))
        self.turbCBrowseButton.setText(QtGui.QApplication.translate("settingsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>This is the time between checking the status of the jobs submited to a remote instance of Turbine.  This setting should be related to the amount of time a jobs set is expected to take.  A very low setting may overwhelm the Turbine server with status requests.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("settingsFrame", "Check Interval (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setToolTip(QtGui.QApplication.translate("settingsFrame", "<html><head/><body><p>If a job fails, it can be resubmitted up to a maximum of this many times.  Jobs may occasionally fail due to software of network problems, this setting will decrease the odds that a jobs failed for resons other than just failure to converge to a solution.</p><p><br/></p><p>If this option is 0 failed jobs will not be resumitted.  This should be set to 0 if a significant number of simulations are expected not to converge.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("settingsFrame", "Number of Times to Resubmit Failed Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("settingsFrame", "Turbine", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("settingsFrame", "FOQUS Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("settingsFrame", "Critical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("settingsFrame", "Error", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("settingsFrame", "Warning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("settingsFrame", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("settingsFrame", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("settingsFrame", "Turbine Client Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("settingsFrame", "Critical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("settingsFrame", "Error", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("settingsFrame", "Warning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("settingsFrame", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("settingsFrame", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("settingsFrame", "Log Files (in logs subdirectory of working dir)", None, QtGui.QApplication.UnicodeUTF8))
        self.foqusLogFileEdit.setText(QtGui.QApplication.translate("settingsFrame", "foqus.log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settingsFrame", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settingsFrame", "Turbine Client", None, QtGui.QApplication.UnicodeUTF8))
        self.turbineLogFileEdit.setText(QtGui.QApplication.translate("settingsFrame", "foqus.log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settingsFrame", "Std. Out", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settingsFrame", "FOQUS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("settingsFrame", "File Out", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("settingsFrame", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.rotateLogCheck.setText(QtGui.QApplication.translate("settingsFrame", "Rotate Log Files (experimental feature)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("settingsFrame", "Max Log File Size (Mb)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("settingsFrame", "Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.revertButton.setText(QtGui.QApplication.translate("settingsFrame", "Revert Changes", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
