# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main\turbineConfig_UI.ui'
#
# Created: Wed Jul 16 11:46:39 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_turbineConfig(object):
    def setupUi(self, turbineConfig):
        turbineConfig.setObjectName("turbineConfig")
        turbineConfig.resize(538, 186)
        self.verticalLayout = QtGui.QVBoxLayout(turbineConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(turbineConfig)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verBox = QtGui.QComboBox(turbineConfig)
        self.verBox.setObjectName("verBox")
        self.verBox.addItem("")
        self.verBox.addItem("")
        self.horizontalLayout_3.addWidget(self.verBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pwdEdit = QtGui.QLineEdit(turbineConfig)
        self.pwdEdit.setEnabled(False)
        self.pwdEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.pwdEdit.setObjectName("pwdEdit")
        self.gridLayout.addWidget(self.pwdEdit, 4, 1, 1, 1)
        self.userEdit = QtGui.QLineEdit(turbineConfig)
        self.userEdit.setEnabled(False)
        self.userEdit.setObjectName("userEdit")
        self.gridLayout.addWidget(self.userEdit, 3, 1, 1, 1)
        self.addressEdit = QtGui.QLineEdit(turbineConfig)
        self.addressEdit.setEnabled(True)
        self.addressEdit.setText("")
        self.addressEdit.setReadOnly(False)
        self.addressEdit.setObjectName("addressEdit")
        self.gridLayout.addWidget(self.addressEdit, 2, 1, 1, 1)
        self.label = QtGui.QLabel(turbineConfig)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(turbineConfig)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(turbineConfig)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtGui.QPushButton(turbineConfig)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.saveAsButton = QtGui.QPushButton(turbineConfig)
        self.saveAsButton.setObjectName("saveAsButton")
        self.horizontalLayout.addWidget(self.saveAsButton)
        self.cancelButton = QtGui.QPushButton(turbineConfig)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.testButton = QtGui.QPushButton(turbineConfig)
        self.testButton.setObjectName("testButton")
        self.horizontalLayout.addWidget(self.testButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5.setBuddy(self.verBox)
        self.label.setBuddy(self.addressEdit)
        self.label_2.setBuddy(self.userEdit)
        self.label_3.setBuddy(self.pwdEdit)

        self.retranslateUi(turbineConfig)
        QtCore.QMetaObject.connectSlotsByName(turbineConfig)
        turbineConfig.setTabOrder(self.addressEdit, self.userEdit)
        turbineConfig.setTabOrder(self.userEdit, self.pwdEdit)
        turbineConfig.setTabOrder(self.pwdEdit, self.testButton)
        turbineConfig.setTabOrder(self.testButton, self.saveButton)
        turbineConfig.setTabOrder(self.saveButton, self.saveAsButton)
        turbineConfig.setTabOrder(self.saveAsButton, self.cancelButton)
        turbineConfig.setTabOrder(self.cancelButton, self.verBox)

    def retranslateUi(self, turbineConfig):
        turbineConfig.setWindowTitle(QtGui.QApplication.translate("turbineConfig", "Turbine Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("turbineConfig", "Turbine Gateway Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.verBox.setItemText(0, QtGui.QApplication.translate("turbineConfig", "Lite", None, QtGui.QApplication.UnicodeUTF8))
        self.verBox.setItemText(1, QtGui.QApplication.translate("turbineConfig", "Cluster/Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("turbineConfig", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("turbineConfig", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("turbineConfig", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("turbineConfig", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsButton.setText(QtGui.QApplication.translate("turbineConfig", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("turbineConfig", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("turbineConfig", "Test", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
