# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flowsheet\columns_UI.ui'
#
# Created: Fri May 20 13:34:01 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 449)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.metadataColumnsList = QtGui.QListWidget(self.tab)
        self.metadataColumnsList.setObjectName("metadataColumnsList")
        self.verticalLayout_6.addWidget(self.metadataColumnsList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.metadataAllButton = QtGui.QPushButton(self.tab)
        self.metadataAllButton.setObjectName("metadataAllButton")
        self.horizontalLayout_2.addWidget(self.metadataAllButton)
        self.metadataNoneButton = QtGui.QPushButton(self.tab)
        self.metadataNoneButton.setObjectName("metadataNoneButton")
        self.horizontalLayout_2.addWidget(self.metadataNoneButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.inputColumnsList = QtGui.QListWidget(self.tab_3)
        self.inputColumnsList.setObjectName("inputColumnsList")
        self.verticalLayout_7.addWidget(self.inputColumnsList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inputAllButton = QtGui.QPushButton(self.tab_3)
        self.inputAllButton.setObjectName("inputAllButton")
        self.horizontalLayout_3.addWidget(self.inputAllButton)
        self.inputNoneButton = QtGui.QPushButton(self.tab_3)
        self.inputNoneButton.setObjectName("inputNoneButton")
        self.horizontalLayout_3.addWidget(self.inputNoneButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outputColumnsList = QtGui.QListWidget(self.tab_4)
        self.outputColumnsList.setObjectName("outputColumnsList")
        self.verticalLayout_2.addWidget(self.outputColumnsList)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputAllButton = QtGui.QPushButton(self.tab_4)
        self.outputAllButton.setObjectName("outputAllButton")
        self.horizontalLayout_4.addWidget(self.outputAllButton)
        self.outputNoneButton = QtGui.QPushButton(self.tab_4)
        self.outputNoneButton.setObjectName("outputNoneButton")
        self.horizontalLayout_4.addWidget(self.outputNoneButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settingsColumnsList = QtGui.QListWidget(self.tab_2)
        self.settingsColumnsList.setObjectName("settingsColumnsList")
        self.verticalLayout_3.addWidget(self.settingsColumnsList)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.settingsAllButton = QtGui.QPushButton(self.tab_2)
        self.settingsAllButton.setObjectName("settingsAllButton")
        self.horizontalLayout_5.addWidget(self.settingsAllButton)
        self.settingsNoneButton = QtGui.QPushButton(self.tab_2)
        self.settingsNoneButton.setObjectName("settingsNoneButton")
        self.horizontalLayout_5.addWidget(self.settingsNoneButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataAllButton.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.metadataNoneButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.inputAllButton.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.inputNoneButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.outputAllButton.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.outputNoneButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsAllButton.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsNoneButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))

