# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flowsheet\dataFilterDialog_UI.ui'
#
# Created: Mon Sep 14 14:12:31 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dataFilterDialog(object):
    def setupUi(self, dataFilterDialog):
        dataFilterDialog.setObjectName("dataFilterDialog")
        dataFilterDialog.resize(787, 411)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dataFilterDialog.sizePolicy().hasHeightForWidth())
        dataFilterDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(dataFilterDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtGui.QLabel(dataFilterDialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.selectFilterBox = QtGui.QComboBox(dataFilterDialog)
        self.selectFilterBox.setMinimumSize(QtCore.QSize(200, 0))
        self.selectFilterBox.setObjectName("selectFilterBox")
        self.horizontalLayout.addWidget(self.selectFilterBox)
        self.newFilterButton = QtGui.QPushButton(dataFilterDialog)
        self.newFilterButton.setObjectName("newFilterButton")
        self.horizontalLayout.addWidget(self.newFilterButton)
        self.deleteFilterButton = QtGui.QPushButton(dataFilterDialog)
        self.deleteFilterButton.setObjectName("deleteFilterButton")
        self.horizontalLayout.addWidget(self.deleteFilterButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.splitFrame = QtGui.QFrame(dataFilterDialog)
        self.splitFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.splitFrame.setObjectName("splitFrame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.splitFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ruleTable = QtGui.QTableWidget(self.splitFrame)
        self.ruleTable.setObjectName("ruleTable")
        self.ruleTable.setColumnCount(3)
        self.ruleTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ruleTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ruleTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ruleTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_5.addWidget(self.ruleTable)
        self.TreeFrame = QtGui.QFrame(self.splitFrame)
        self.TreeFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.TreeFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.TreeFrame.setObjectName("TreeFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.TreeFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.TreeFrame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.colList = QtGui.QListWidget(self.TreeFrame)
        self.colList.setObjectName("colList")
        self.verticalLayout.addWidget(self.colList)
        self.horizontalLayout_5.addWidget(self.TreeFrame)
        self.verticalLayout_2.addWidget(self.splitFrame)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sortCheck = QtGui.QCheckBox(dataFilterDialog)
        self.sortCheck.setObjectName("sortCheck")
        self.horizontalLayout_3.addWidget(self.sortCheck)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtGui.QLabel(dataFilterDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sortTermEdit = QtGui.QLineEdit(dataFilterDialog)
        self.sortTermEdit.setEnabled(False)
        self.sortTermEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sortTermEdit.setObjectName("sortTermEdit")
        self.horizontalLayout_3.addWidget(self.sortTermEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addRuleButton = QtGui.QPushButton(dataFilterDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addRuleButton.setIcon(icon)
        self.addRuleButton.setObjectName("addRuleButton")
        self.horizontalLayout_2.addWidget(self.addRuleButton)
        self.addOpButton = QtGui.QPushButton(dataFilterDialog)
        self.addOpButton.setIcon(icon)
        self.addOpButton.setObjectName("addOpButton")
        self.horizontalLayout_2.addWidget(self.addOpButton)
        self.muButton = QtGui.QPushButton(dataFilterDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muButton.setIcon(icon1)
        self.muButton.setObjectName("muButton")
        self.horizontalLayout_2.addWidget(self.muButton)
        self.mdButton = QtGui.QPushButton(dataFilterDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mdButton.setIcon(icon2)
        self.mdButton.setObjectName("mdButton")
        self.horizontalLayout_2.addWidget(self.mdButton)
        self.deleteButton = QtGui.QPushButton(dataFilterDialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.showColButton = QtGui.QPushButton(dataFilterDialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showColButton.setIcon(icon4)
        self.showColButton.setObjectName("showColButton")
        self.horizontalLayout_2.addWidget(self.showColButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.doneButton = QtGui.QPushButton(dataFilterDialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.doneButton.setIcon(icon5)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_2.addWidget(self.doneButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2.setBuddy(self.sortTermEdit)

        self.retranslateUi(dataFilterDialog)
        QtCore.QMetaObject.connectSlotsByName(dataFilterDialog)

    def retranslateUi(self, dataFilterDialog):
        dataFilterDialog.setWindowTitle(QtGui.QApplication.translate("dataFilterDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dataFilterDialog", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.newFilterButton.setText(QtGui.QApplication.translate("dataFilterDialog", "New Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteFilterButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Delete Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.ruleTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("dataFilterDialog", "Term 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ruleTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("dataFilterDialog", "Operator", None, QtGui.QApplication.UnicodeUTF8))
        self.ruleTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("dataFilterDialog", "Term 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dataFilterDialog", "Columns (double click to copy)", None, QtGui.QApplication.UnicodeUTF8))
        self.sortCheck.setText(QtGui.QApplication.translate("dataFilterDialog", "Sort Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dataFilterDialog", "Sort term:", None, QtGui.QApplication.UnicodeUTF8))
        self.addRuleButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Add Rule", None, QtGui.QApplication.UnicodeUTF8))
        self.addOpButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Add Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.muButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.mdButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.showColButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Show Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("dataFilterDialog", "Done", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
