# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flowsheet\edgePanel_UI.ui'
#
# Created: Wed Jun 08 12:57:45 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_edgeDock(object):
    def setupUi(self, edgeDock):
        edgeDock.setObjectName("edgeDock")
        edgeDock.resize(527, 699)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fromBox = QtGui.QComboBox(self.dockWidgetContents)
        self.fromBox.setEnabled(False)
        self.fromBox.setMinimumSize(QtCore.QSize(150, 0))
        self.fromBox.setObjectName("fromBox")
        self.gridLayout.addWidget(self.fromBox, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.curveBox = QtGui.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curveBox.sizePolicy().hasHeightForWidth())
        self.curveBox.setSizePolicy(sizePolicy)
        self.curveBox.setMinimumSize(QtCore.QSize(0, 0))
        self.curveBox.setMaximumSize(QtCore.QSize(75, 16777215))
        self.curveBox.setObjectName("curveBox")
        self.gridLayout.addWidget(self.curveBox, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.toBox = QtGui.QComboBox(self.dockWidgetContents)
        self.toBox.setEnabled(False)
        self.toBox.setObjectName("toBox")
        self.gridLayout.addWidget(self.toBox, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.indexBox = QtGui.QComboBox(self.dockWidgetContents)
        self.indexBox.setObjectName("indexBox")
        self.gridLayout.addWidget(self.indexBox, 0, 1, 1, 1)
        self.editOrigin = QtGui.QCheckBox(self.dockWidgetContents)
        self.editOrigin.setObjectName("editOrigin")
        self.gridLayout.addWidget(self.editOrigin, 1, 2, 1, 1)
        self.editDestination = QtGui.QCheckBox(self.dockWidgetContents)
        self.editDestination.setObjectName("editDestination")
        self.gridLayout.addWidget(self.editDestination, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tearBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.tearBox.setObjectName("tearBox")
        self.horizontalLayout_4.addWidget(self.tearBox)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.activeBox = QtGui.QCheckBox(self.dockWidgetContents)
        self.activeBox.setObjectName("activeBox")
        self.horizontalLayout_4.addWidget(self.activeBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.connectTable = QtGui.QTableWidget(self.groupBox)
        self.connectTable.setEnabled(False)
        self.connectTable.setObjectName("connectTable")
        self.connectTable.setColumnCount(3)
        self.connectTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.connectTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.connectTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.connectTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_6.addWidget(self.connectTable)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lockConnection = QtGui.QCheckBox(self.groupBox)
        self.lockConnection.setChecked(True)
        self.lockConnection.setObjectName("lockConnection")
        self.verticalLayout.addWidget(self.lockConnection)
        self.addConButton = QtGui.QPushButton(self.groupBox)
        self.addConButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.addConButton.setIcon(icon)
        self.addConButton.setIconSize(QtCore.QSize(16, 16))
        self.addConButton.setObjectName("addConButton")
        self.verticalLayout.addWidget(self.addConButton)
        self.deleteConButton = QtGui.QPushButton(self.groupBox)
        self.deleteConButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.deleteConButton.setIcon(icon1)
        self.deleteConButton.setIconSize(QtCore.QSize(16, 16))
        self.deleteConButton.setObjectName("deleteConButton")
        self.verticalLayout.addWidget(self.deleteConButton)
        self.autoButton = QtGui.QPushButton(self.groupBox)
        self.autoButton.setObjectName("autoButton")
        self.verticalLayout.addWidget(self.autoButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        edgeDock.setWidget(self.dockWidgetContents)
        self.label_2.setBuddy(self.toBox)
        self.label.setBuddy(self.fromBox)
        self.label_3.setBuddy(self.curveBox)

        self.retranslateUi(edgeDock)
        QtCore.QObject.connect(self.editOrigin, QtCore.SIGNAL("toggled(bool)"), self.fromBox.setEnabled)
        QtCore.QObject.connect(self.editDestination, QtCore.SIGNAL("toggled(bool)"), self.toBox.setEnabled)
        QtCore.QObject.connect(self.lockConnection, QtCore.SIGNAL("toggled(bool)"), self.connectTable.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(edgeDock)

    def retranslateUi(self, edgeDock):
        edgeDock.setWindowTitle(QtGui.QApplication.translate("edgeDock", "Edge Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.fromBox.setToolTip(QtGui.QApplication.translate("edgeDock", "<html><head/><body><p>Node that information flows from</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("edgeDock", "Destination Node:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("edgeDock", "Origin Node:", None, QtGui.QApplication.UnicodeUTF8))
        self.curveBox.setToolTip(QtGui.QApplication.translate("edgeDock", "Distance used to draw a curved edge used to prevent edges from overlapping.  Can be positive or negitive.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("edgeDock", "Curve:", None, QtGui.QApplication.UnicodeUTF8))
        self.toBox.setToolTip(QtGui.QApplication.translate("edgeDock", "<html><head/><body><p>Node that infromation flows to</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("edgeDock", "Index:", None, QtGui.QApplication.UnicodeUTF8))
        self.editOrigin.setText(QtGui.QApplication.translate("edgeDock", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.editDestination.setText(QtGui.QApplication.translate("edgeDock", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tearBox.setToolTip(QtGui.QApplication.translate("edgeDock", "<html><head/><body><p>Mark this edge as a tear edge for solving flowsheets where nodes are interdependent</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tearBox.setText(QtGui.QApplication.translate("edgeDock", "Tear", None, QtGui.QApplication.UnicodeUTF8))
        self.activeBox.setToolTip(QtGui.QApplication.translate("edgeDock", "<html><head/><body><p>If this is not checked the edge will be ignored.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.activeBox.setText(QtGui.QApplication.translate("edgeDock", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("edgeDock", "Variable Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.connectTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("edgeDock", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.connectTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("edgeDock", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.connectTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("edgeDock", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.lockConnection.setText(QtGui.QApplication.translate("edgeDock", "Lock Editing", None, QtGui.QApplication.UnicodeUTF8))
        self.autoButton.setToolTip(QtGui.QApplication.translate("edgeDock", "<html><head/><body><p>Automatically add connections for input or output variables in the origin node to input variables of the same name in the destination node.  These connections can then be edited.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.autoButton.setText(QtGui.QApplication.translate("edgeDock", "Auto", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
