# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flowsheet\nodePanel_UI.ui'
#
# Created: Wed Mar 30 08:55:30 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_nodeDock(object):
    def setupUi(self, nodeDock):
        nodeDock.setObjectName("nodeDock")
        nodeDock.resize(1138, 758)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.applyButton = QtGui.QPushButton(self.dockWidgetContents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.applyButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.applyButton.setFont(font)
        self.applyButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.applyButton.setIcon(icon)
        self.applyButton.setIconSize(QtCore.QSize(16, 16))
        self.applyButton.setFlat(False)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.revertButton = QtGui.QPushButton(self.dockWidgetContents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.revertButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.revertButton.setFont(font)
        self.revertButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.revertButton.setIcon(icon1)
        self.revertButton.setIconSize(QtCore.QSize(16, 16))
        self.revertButton.setFlat(False)
        self.revertButton.setObjectName("revertButton")
        self.horizontalLayout.addWidget(self.revertButton)
        self.runButton = QtGui.QPushButton(self.dockWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.runButton.setIcon(icon2)
        self.runButton.setIconSize(QtCore.QSize(16, 16))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.stopButton = QtGui.QPushButton(self.dockWidgetContents)
        self.stopButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stopButton.setIcon(icon3)
        self.stopButton.setIconSize(QtCore.QSize(16, 16))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.nodeNameBox = QtGui.QComboBox(self.tab)
        self.nodeNameBox.setMinimumSize(QtCore.QSize(150, 0))
        self.nodeNameBox.setEditable(True)
        self.nodeNameBox.setObjectName("nodeNameBox")
        self.horizontalLayout_5.addWidget(self.nodeNameBox)
        self.visCheck = QtGui.QCheckBox(self.tab)
        self.visCheck.setObjectName("visCheck")
        self.horizontalLayout_5.addWidget(self.visCheck)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calcErrorBox = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcErrorBox.sizePolicy().hasHeightForWidth())
        self.calcErrorBox.setSizePolicy(sizePolicy)
        self.calcErrorBox.setMaximumSize(QtCore.QSize(50, 100))
        self.calcErrorBox.setAcceptDrops(False)
        self.calcErrorBox.setReadOnly(True)
        self.calcErrorBox.setObjectName("calcErrorBox")
        self.gridLayout_2.addWidget(self.calcErrorBox, 0, 1, 1, 1)
        self.errorMessageText = QtGui.QLineEdit(self.groupBox)
        self.errorMessageText.setReadOnly(True)
        self.errorMessageText.setObjectName("errorMessageText")
        self.gridLayout_2.addWidget(self.errorMessageText, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.modelTypeBox = QtGui.QComboBox(self.groupBox_2)
        self.modelTypeBox.setMinimumSize(QtCore.QSize(120, 0))
        self.modelTypeBox.setObjectName("modelTypeBox")
        self.modelTypeBox.addItem("")
        self.modelTypeBox.addItem("")
        self.modelTypeBox.addItem("")
        self.modelTypeBox.addItem("")
        self.modelTypeBox.addItem("")
        self.horizontalLayout_3.addWidget(self.modelTypeBox)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.simNameBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simNameBox.sizePolicy().hasHeightForWidth())
        self.simNameBox.setSizePolicy(sizePolicy)
        self.simNameBox.setMinimumSize(QtCore.QSize(200, 0))
        self.simNameBox.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.simNameBox.setObjectName("simNameBox")
        self.horizontalLayout_3.addWidget(self.simNameBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1096, 385))
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.addInputButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addInputButton.sizePolicy().hasHeightForWidth())
        self.addInputButton.setSizePolicy(sizePolicy)
        self.addInputButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.addInputButton.setIcon(icon4)
        self.addInputButton.setFlat(False)
        self.addInputButton.setObjectName("addInputButton")
        self.horizontalLayout_8.addWidget(self.addInputButton)
        self.removeInputButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeInputButton.sizePolicy().hasHeightForWidth())
        self.removeInputButton.setSizePolicy(sizePolicy)
        self.removeInputButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.removeInputButton.setIcon(icon5)
        self.removeInputButton.setFlat(False)
        self.removeInputButton.setObjectName("removeInputButton")
        self.horizontalLayout_8.addWidget(self.removeInputButton)
        self.inputTagBrowser = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTagBrowser.sizePolicy().hasHeightForWidth())
        self.inputTagBrowser.setSizePolicy(sizePolicy)
        self.inputTagBrowser.setMinimumSize(QtCore.QSize(20, 0))
        self.inputTagBrowser.setBaseSize(QtCore.QSize(1, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.inputTagBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.inputTagBrowser.setFont(font)
        self.inputTagBrowser.setCursor(QtCore.Qt.PointingHandCursor)
        self.inputTagBrowser.setFlat(False)
        self.inputTagBrowser.setObjectName("inputTagBrowser")
        self.horizontalLayout_8.addWidget(self.inputTagBrowser)
        self.valuesToDeafultsButton = QtGui.QPushButton(self.page)
        self.valuesToDeafultsButton.setObjectName("valuesToDeafultsButton")
        self.horizontalLayout_8.addWidget(self.valuesToDeafultsButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.inputVarTable = QtGui.QTableWidget(self.page)
        self.inputVarTable.setMinimumSize(QtCore.QSize(0, 200))
        self.inputVarTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.inputVarTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.inputVarTable.setObjectName("inputVarTable")
        self.inputVarTable.setColumnCount(12)
        self.inputVarTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.inputVarTable.setHorizontalHeaderItem(11, item)
        self.verticalLayout_7.addWidget(self.inputVarTable)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setStyleSheet("QWidget { background-color :   rgb(255, 255, 255)}")
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.label_14 = QtGui.QLabel(self.page)
        self.label_14.setStyleSheet("QWidget { background-color :   rgb(255, 250, 180)}")
        self.label_14.setFrameShape(QtGui.QFrame.Box)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.label_16 = QtGui.QLabel(self.page)
        self.label_16.setStyleSheet("QWidget { background-color :   rgb(255, 200, 200)}")
        self.label_16.setFrameShape(QtGui.QFrame.Box)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1096, 385))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.addOutputButton = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addOutputButton.sizePolicy().hasHeightForWidth())
        self.addOutputButton.setSizePolicy(sizePolicy)
        self.addOutputButton.setText("")
        self.addOutputButton.setIcon(icon4)
        self.addOutputButton.setFlat(True)
        self.addOutputButton.setObjectName("addOutputButton")
        self.horizontalLayout_16.addWidget(self.addOutputButton)
        self.removeOutputButton = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeOutputButton.sizePolicy().hasHeightForWidth())
        self.removeOutputButton.setSizePolicy(sizePolicy)
        self.removeOutputButton.setText("")
        self.removeOutputButton.setIcon(icon5)
        self.removeOutputButton.setFlat(True)
        self.removeOutputButton.setObjectName("removeOutputButton")
        self.horizontalLayout_16.addWidget(self.removeOutputButton)
        self.outputTagBrowser = QtGui.QPushButton(self.page_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.outputTagBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.outputTagBrowser.setFont(font)
        self.outputTagBrowser.setCursor(QtCore.Qt.PointingHandCursor)
        self.outputTagBrowser.setFlat(True)
        self.outputTagBrowser.setObjectName("outputTagBrowser")
        self.horizontalLayout_16.addWidget(self.outputTagBrowser)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.outputVarTable = QtGui.QTableWidget(self.page_2)
        self.outputVarTable.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.outputVarTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.outputVarTable.setObjectName("outputVarTable")
        self.outputVarTable.setColumnCount(6)
        self.outputVarTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.outputVarTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.outputVarTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.outputVarTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.outputVarTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.outputVarTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.outputVarTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.outputVarTable)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.simSettingsTable = QtGui.QTableWidget(self.page_3)
        self.simSettingsTable.setObjectName("simSettingsTable")
        self.simSettingsTable.setColumnCount(3)
        self.simSettingsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.simSettingsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.simSettingsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.simSettingsTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_9.addWidget(self.simSettingsTable)
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout_8.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.xBox = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xBox.sizePolicy().hasHeightForWidth())
        self.xBox.setSizePolicy(sizePolicy)
        self.xBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xBox.setObjectName("xBox")
        self.horizontalLayout_11.addWidget(self.xBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.yBox = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yBox.sizePolicy().hasHeightForWidth())
        self.yBox.setSizePolicy(sizePolicy)
        self.yBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.yBox.setObjectName("yBox")
        self.horizontalLayout_12.addWidget(self.yBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.zBox = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zBox.sizePolicy().hasHeightForWidth())
        self.zBox.setSizePolicy(sizePolicy)
        self.zBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zBox.setObjectName("zBox")
        self.horizontalLayout_13.addWidget(self.zBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        spacerItem8 = QtGui.QSpacerItem(20, 520, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.postRadio = QtGui.QRadioButton(self.groupBox_3)
        self.postRadio.setChecked(True)
        self.postRadio.setObjectName("postRadio")
        self.gridLayout.addWidget(self.postRadio, 2, 0, 1, 1)
        self.preRadio = QtGui.QRadioButton(self.groupBox_3)
        self.preRadio.setObjectName("preRadio")
        self.gridLayout.addWidget(self.preRadio, 1, 0, 1, 1)
        self.totalRadio = QtGui.QRadioButton(self.groupBox_3)
        self.totalRadio.setObjectName("totalRadio")
        self.gridLayout.addWidget(self.totalRadio, 3, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pyCode = QtGui.QPlainTextEdit(self.groupBox_4)
        self.pyCode.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.pyCode.setFont(font)
        self.pyCode.setObjectName("pyCode")
        self.verticalLayout_6.addWidget(self.pyCode)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vexButton = QtGui.QPushButton(self.groupBox_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.vexButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.vexButton.setFont(font)
        self.vexButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.vexButton.setIcon(icon6)
        self.vexButton.setFlat(True)
        self.vexButton.setObjectName("vexButton")
        self.horizontalLayout_2.addWidget(self.vexButton)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        nodeDock.setWidget(self.dockWidgetContents)
        self.label_6.setBuddy(self.errorMessageText)
        self.label_9.setBuddy(self.calcErrorBox)
        self.label_3.setBuddy(self.modelTypeBox)
        self.label_18.setBuddy(self.simNameBox)
        self.label_11.setBuddy(self.xBox)
        self.label_12.setBuddy(self.yBox)
        self.label_13.setBuddy(self.zBox)

        self.retranslateUi(nodeDock)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(nodeDock)

    def retranslateUi(self, nodeDock):
        nodeDock.setWindowTitle(QtGui.QApplication.translate("nodeDock", "Node Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("nodeDock", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.revertButton.setText(QtGui.QApplication.translate("nodeDock", "Revert", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("nodeDock", "Run (this node only for testing)", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("nodeDock", "Stop Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("nodeDock", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.visCheck.setText(QtGui.QApplication.translate("nodeDock", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("nodeDock", "Error Status", None, QtGui.QApplication.UnicodeUTF8))
        self.calcErrorBox.setText(QtGui.QApplication.translate("nodeDock", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("nodeDock", "Message:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("nodeDock", "Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("nodeDock", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("nodeDock", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.modelTypeBox.setItemText(0, QtGui.QApplication.translate("nodeDock", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.modelTypeBox.setItemText(1, QtGui.QApplication.translate("nodeDock", "Turbine", None, QtGui.QApplication.UnicodeUTF8))
        self.modelTypeBox.setItemText(2, QtGui.QApplication.translate("nodeDock", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.modelTypeBox.setItemText(3, QtGui.QApplication.translate("nodeDock", "DMF Lite", None, QtGui.QApplication.UnicodeUTF8))
        self.modelTypeBox.setItemText(4, QtGui.QApplication.translate("nodeDock", "DMF Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("nodeDock", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.addInputButton.setToolTip(QtGui.QApplication.translate("nodeDock", "<html><head/><body><p>Add a new input varaible</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.removeInputButton.setToolTip(QtGui.QApplication.translate("nodeDock", "<html><head/><body><p>Remove an input variable</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.inputTagBrowser.setText(QtGui.QApplication.translate("nodeDock", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.valuesToDeafultsButton.setText(QtGui.QApplication.translate("nodeDock", "Values to Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("nodeDock", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("nodeDock", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("nodeDock", "Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("nodeDock", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("nodeDock", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("nodeDock", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("nodeDock", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("nodeDock", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("nodeDock", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("nodeDock", "Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("nodeDock", "Param 1", None, QtGui.QApplication.UnicodeUTF8))
        self.inputVarTable.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("nodeDock", "Param 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("nodeDock", "Legend:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("nodeDock", "Not Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("nodeDock", "Tear Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("nodeDock", "Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("nodeDock", "Input Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.addOutputButton.setToolTip(QtGui.QApplication.translate("nodeDock", "<html><head/><body><p>Add an output variable</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.removeOutputButton.setToolTip(QtGui.QApplication.translate("nodeDock", "<html><head/><body><p>Remove an output variable</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.outputTagBrowser.setText(QtGui.QApplication.translate("nodeDock", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.outputVarTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("nodeDock", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.outputVarTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("nodeDock", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.outputVarTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("nodeDock", "Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.outputVarTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("nodeDock", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.outputVarTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("nodeDock", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.outputVarTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("nodeDock", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("nodeDock", "Output Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.simSettingsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("nodeDock", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.simSettingsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("nodeDock", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.simSettingsTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("nodeDock", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("nodeDock", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("nodeDock", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("nodeDock", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("nodeDock", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("nodeDock", "z:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("nodeDock", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("nodeDock", "Script Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.postRadio.setText(QtGui.QApplication.translate("nodeDock", "Post (Run script after model)", None, QtGui.QApplication.UnicodeUTF8))
        self.preRadio.setText(QtGui.QApplication.translate("nodeDock", "Pre (Run script before model)", None, QtGui.QApplication.UnicodeUTF8))
        self.totalRadio.setText(QtGui.QApplication.translate("nodeDock", "Total (Script the entire node calculation sequence, including running the model)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("nodeDock", "Node Script (Python Code)", None, QtGui.QApplication.UnicodeUTF8))
        self.vexButton.setText(QtGui.QApplication.translate("nodeDock", "Variable Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("nodeDock", "Node Script", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
