# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dabnet_param_dlg.ui'
#
# Created: Wed Aug 26 11:33:19 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dabnetParamDlg(object):
    def setupUi(self, dabnetParamDlg):
        dabnetParamDlg.setObjectName("dabnetParamDlg")
        dabnetParamDlg.resize(854, 508)
        self.gridLayout_5 = QtGui.QGridLayout(dabnetParamDlg)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_MethodForLaguerre = QtGui.QGroupBox(dabnetParamDlg)
        self.groupBox_MethodForLaguerre.setObjectName("groupBox_MethodForLaguerre")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_MethodForLaguerre)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_LaguerreMaxIterations = QtGui.QLabel(self.groupBox_MethodForLaguerre)
        self.label_LaguerreMaxIterations.setObjectName("label_LaguerreMaxIterations")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_LaguerreMaxIterations)
        self.lineEdit_LaguerreMaxIterations = QtGui.QLineEdit(self.groupBox_MethodForLaguerre)
        self.lineEdit_LaguerreMaxIterations.setObjectName("lineEdit_LaguerreMaxIterations")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_LaguerreMaxIterations)
        self.gridLayout_3.addLayout(self.formLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_LaguerreBP = QtGui.QRadioButton(self.groupBox_MethodForLaguerre)
        self.radioButton_LaguerreBP.setObjectName("radioButton_LaguerreBP")
        self.horizontalLayout_2.addWidget(self.radioButton_LaguerreBP)
        self.radioButton_LaguerreIPOPT = QtGui.QRadioButton(self.groupBox_MethodForLaguerre)
        self.radioButton_LaguerreIPOPT.setObjectName("radioButton_LaguerreIPOPT")
        self.horizontalLayout_2.addWidget(self.radioButton_LaguerreIPOPT)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_MethodForLaguerre)
        spacerItem = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox_MethodForBalanced = QtGui.QGroupBox(dabnetParamDlg)
        self.groupBox_MethodForBalanced.setObjectName("groupBox_MethodForBalanced")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_MethodForBalanced)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_BalancedBP = QtGui.QRadioButton(self.groupBox_MethodForBalanced)
        self.radioButton_BalancedBP.setObjectName("radioButton_BalancedBP")
        self.horizontalLayout_3.addWidget(self.radioButton_BalancedBP)
        self.radioButton_BalancedIPOPT = QtGui.QRadioButton(self.groupBox_MethodForBalanced)
        self.radioButton_BalancedIPOPT.setObjectName("radioButton_BalancedIPOPT")
        self.horizontalLayout_3.addWidget(self.radioButton_BalancedIPOPT)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_BalancedMaxIterations = QtGui.QLabel(self.groupBox_MethodForBalanced)
        self.label_BalancedMaxIterations.setObjectName("label_BalancedMaxIterations")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_BalancedMaxIterations)
        self.lineEdit_BalancedMaxIterations = QtGui.QLineEdit(self.groupBox_MethodForBalanced)
        self.lineEdit_BalancedMaxIterations.setObjectName("lineEdit_BalancedMaxIterations")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_BalancedMaxIterations)
        self.gridLayout_4.addLayout(self.formLayout_4, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_MethodForBalanced)
        spacerItem1 = QtGui.QSpacerItem(17, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_InitialWeight = QtGui.QLabel(dabnetParamDlg)
        self.label_InitialWeight.setObjectName("label_InitialWeight")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_InitialWeight)
        self.lineEdit_InitialWeight = QtGui.QLineEdit(dabnetParamDlg)
        self.lineEdit_InitialWeight.setObjectName("lineEdit_InitialWeight")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_InitialWeight)
        self.verticalLayout_4.addLayout(self.formLayout_6)
        self.pushButton_ResetToDefault = QtGui.QPushButton(dabnetParamDlg)
        self.pushButton_ResetToDefault.setAutoDefault(False)
        self.pushButton_ResetToDefault.setObjectName("pushButton_ResetToDefault")
        self.verticalLayout_4.addWidget(self.pushButton_ResetToDefault)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Cancel = QtGui.QPushButton(dabnetParamDlg)
        self.pushButton_Cancel.setAutoDefault(False)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_4.addWidget(self.pushButton_Cancel)
        self.pushButton_OK = QtGui.QPushButton(dabnetParamDlg)
        self.pushButton_OK.setAutoDefault(False)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout_4.addWidget(self.pushButton_OK)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_OutputList = QtGui.QLabel(dabnetParamDlg)
        self.label_OutputList.setObjectName("label_OutputList")
        self.verticalLayout.addWidget(self.label_OutputList)
        self.listWidget_OutputList = QtGui.QListWidget(dabnetParamDlg)
        self.listWidget_OutputList.setObjectName("listWidget_OutputList")
        self.verticalLayout.addWidget(self.listWidget_OutputList)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_InputList = QtGui.QLabel(dabnetParamDlg)
        self.label_InputList.setObjectName("label_InputList")
        self.verticalLayout_2.addWidget(self.label_InputList)
        self.listWidget_InputList = QtGui.QListWidget(dabnetParamDlg)
        self.listWidget_InputList.setObjectName("listWidget_InputList")
        self.verticalLayout_2.addWidget(self.listWidget_InputList)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_ForEachOutput = QtGui.QGroupBox(dabnetParamDlg)
        self.groupBox_ForEachOutput.setObjectName("groupBox_ForEachOutput")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_ForEachOutput)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_UseSpecifiedPoleValue = QtGui.QRadioButton(self.groupBox_ForEachOutput)
        self.radioButton_UseSpecifiedPoleValue.setObjectName("radioButton_UseSpecifiedPoleValue")
        self.gridLayout_6.addWidget(self.radioButton_UseSpecifiedPoleValue, 0, 0, 1, 1)
        self.radioButton_OptimizeBothPoles = QtGui.QRadioButton(self.groupBox_ForEachOutput)
        self.radioButton_OptimizeBothPoles.setObjectName("radioButton_OptimizeBothPoles")
        self.gridLayout_6.addWidget(self.radioButton_OptimizeBothPoles, 0, 1, 1, 1)
        self.radioButton_OptimizeFastPole = QtGui.QRadioButton(self.groupBox_ForEachOutput)
        self.radioButton_OptimizeFastPole.setObjectName("radioButton_OptimizeFastPole")
        self.gridLayout_6.addWidget(self.radioButton_OptimizeFastPole, 1, 0, 1, 1)
        self.radioButton_OptimizeSlowPole = QtGui.QRadioButton(self.groupBox_ForEachOutput)
        self.radioButton_OptimizeSlowPole.setObjectName("radioButton_OptimizeSlowPole")
        self.gridLayout_6.addWidget(self.radioButton_OptimizeSlowPole, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_NumberOfNeurons = QtGui.QLabel(self.groupBox_ForEachOutput)
        self.label_NumberOfNeurons.setObjectName("label_NumberOfNeurons")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_NumberOfNeurons)
        self.lineEdit_NumberOfNeurons = QtGui.QLineEdit(self.groupBox_ForEachOutput)
        self.lineEdit_NumberOfNeurons.setObjectName("lineEdit_NumberOfNeurons")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_NumberOfNeurons)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.checkBox_LinearModel = QtGui.QCheckBox(self.groupBox_ForEachOutput)
        self.checkBox_LinearModel.setObjectName("checkBox_LinearModel")
        self.gridLayout.addWidget(self.checkBox_LinearModel, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_ForEachOutput)
        self.groupBox_ForEachInput = QtGui.QGroupBox(dabnetParamDlg)
        self.groupBox_ForEachInput.setObjectName("groupBox_ForEachInput")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_ForEachInput)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_Use2Poles = QtGui.QCheckBox(self.groupBox_ForEachInput)
        self.checkBox_Use2Poles.setObjectName("checkBox_Use2Poles")
        self.gridLayout_2.addWidget(self.checkBox_Use2Poles, 0, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_NumberOfLaguerreStates = QtGui.QLabel(self.groupBox_ForEachInput)
        self.label_NumberOfLaguerreStates.setObjectName("label_NumberOfLaguerreStates")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_NumberOfLaguerreStates)
        self.lineEdit_NumberOfLaguerreStates = QtGui.QLineEdit(self.groupBox_ForEachInput)
        self.lineEdit_NumberOfLaguerreStates.setObjectName("lineEdit_NumberOfLaguerreStates")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_NumberOfLaguerreStates)
        self.label_EstimatedPoleValue = QtGui.QLabel(self.groupBox_ForEachInput)
        self.label_EstimatedPoleValue.setObjectName("label_EstimatedPoleValue")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_EstimatedPoleValue)
        self.lineEdit_EstimatedPoleValue = QtGui.QLineEdit(self.groupBox_ForEachInput)
        self.lineEdit_EstimatedPoleValue.setObjectName("lineEdit_EstimatedPoleValue")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_EstimatedPoleValue)
        self.label_NumberOfLaguerreStates2 = QtGui.QLabel(self.groupBox_ForEachInput)
        self.label_NumberOfLaguerreStates2.setObjectName("label_NumberOfLaguerreStates2")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_NumberOfLaguerreStates2)
        self.lineEdit_NumberOfLaguerreStates2 = QtGui.QLineEdit(self.groupBox_ForEachInput)
        self.lineEdit_NumberOfLaguerreStates2.setObjectName("lineEdit_NumberOfLaguerreStates2")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_NumberOfLaguerreStates2)
        self.label_EstimatedPoleValue2 = QtGui.QLabel(self.groupBox_ForEachInput)
        self.label_EstimatedPoleValue2.setObjectName("label_EstimatedPoleValue2")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_EstimatedPoleValue2)
        self.lineEdit_EstimatedPoleValue2 = QtGui.QLineEdit(self.groupBox_ForEachInput)
        self.lineEdit_EstimatedPoleValue2.setObjectName("lineEdit_EstimatedPoleValue2")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_EstimatedPoleValue2)
        self.label_NumberOfDelays = QtGui.QLabel(self.groupBox_ForEachInput)
        self.label_NumberOfDelays.setObjectName("label_NumberOfDelays")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_NumberOfDelays)
        self.lineEdit_NumberOfDelays = QtGui.QLineEdit(self.groupBox_ForEachInput)
        self.lineEdit_NumberOfDelays.setObjectName("lineEdit_NumberOfDelays")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_NumberOfDelays)
        self.gridLayout_2.addLayout(self.formLayout_3, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_ForEachInput)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)

        self.retranslateUi(dabnetParamDlg)
        QtCore.QMetaObject.connectSlotsByName(dabnetParamDlg)
        dabnetParamDlg.setTabOrder(self.listWidget_OutputList, self.listWidget_InputList)
        dabnetParamDlg.setTabOrder(self.listWidget_InputList, self.checkBox_LinearModel)
        dabnetParamDlg.setTabOrder(self.checkBox_LinearModel, self.lineEdit_NumberOfNeurons)
        dabnetParamDlg.setTabOrder(self.lineEdit_NumberOfNeurons, self.radioButton_UseSpecifiedPoleValue)
        dabnetParamDlg.setTabOrder(self.radioButton_UseSpecifiedPoleValue, self.radioButton_OptimizeBothPoles)
        dabnetParamDlg.setTabOrder(self.radioButton_OptimizeBothPoles, self.radioButton_OptimizeFastPole)
        dabnetParamDlg.setTabOrder(self.radioButton_OptimizeFastPole, self.radioButton_OptimizeSlowPole)
        dabnetParamDlg.setTabOrder(self.radioButton_OptimizeSlowPole, self.checkBox_Use2Poles)
        dabnetParamDlg.setTabOrder(self.checkBox_Use2Poles, self.lineEdit_NumberOfDelays)
        dabnetParamDlg.setTabOrder(self.lineEdit_NumberOfDelays, self.lineEdit_NumberOfLaguerreStates)
        dabnetParamDlg.setTabOrder(self.lineEdit_NumberOfLaguerreStates, self.lineEdit_EstimatedPoleValue)
        dabnetParamDlg.setTabOrder(self.lineEdit_EstimatedPoleValue, self.lineEdit_NumberOfLaguerreStates2)
        dabnetParamDlg.setTabOrder(self.lineEdit_NumberOfLaguerreStates2, self.lineEdit_EstimatedPoleValue2)
        dabnetParamDlg.setTabOrder(self.lineEdit_EstimatedPoleValue2, self.radioButton_LaguerreBP)
        dabnetParamDlg.setTabOrder(self.radioButton_LaguerreBP, self.radioButton_LaguerreIPOPT)
        dabnetParamDlg.setTabOrder(self.radioButton_LaguerreIPOPT, self.lineEdit_LaguerreMaxIterations)
        dabnetParamDlg.setTabOrder(self.lineEdit_LaguerreMaxIterations, self.radioButton_BalancedBP)
        dabnetParamDlg.setTabOrder(self.radioButton_BalancedBP, self.radioButton_BalancedIPOPT)
        dabnetParamDlg.setTabOrder(self.radioButton_BalancedIPOPT, self.lineEdit_BalancedMaxIterations)
        dabnetParamDlg.setTabOrder(self.lineEdit_BalancedMaxIterations, self.lineEdit_InitialWeight)
        dabnetParamDlg.setTabOrder(self.lineEdit_InitialWeight, self.pushButton_ResetToDefault)
        dabnetParamDlg.setTabOrder(self.pushButton_ResetToDefault, self.pushButton_Cancel)
        dabnetParamDlg.setTabOrder(self.pushButton_Cancel, self.pushButton_OK)

    def retranslateUi(self, dabnetParamDlg):
        dabnetParamDlg.setWindowTitle(QtGui.QApplication.translate("dabnetParamDlg", "DABNet DRM Parameter Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_MethodForLaguerre.setTitle(QtGui.QApplication.translate("dabnetParamDlg", "Training Method For Laguerre Model Neural Network", None, QtGui.QApplication.UnicodeUTF8))
        self.label_LaguerreMaxIterations.setText(QtGui.QApplication.translate("dabnetParamDlg", "Maximum Number of Training Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_LaguerreBP.setText(QtGui.QApplication.translate("dabnetParamDlg", "Back Progagation", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_LaguerreIPOPT.setText(QtGui.QApplication.translate("dabnetParamDlg", "IPOPT", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_MethodForBalanced.setTitle(QtGui.QApplication.translate("dabnetParamDlg", "Training Method for Balanced Model Neural Network", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_BalancedBP.setText(QtGui.QApplication.translate("dabnetParamDlg", "Back Progagation", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_BalancedIPOPT.setText(QtGui.QApplication.translate("dabnetParamDlg", "IPOPT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_BalancedMaxIterations.setText(QtGui.QApplication.translate("dabnetParamDlg", "Maximum Number of Training Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_InitialWeight.setText(QtGui.QApplication.translate("dabnetParamDlg", "Initial Weight of ANN Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ResetToDefault.setText(QtGui.QApplication.translate("dabnetParamDlg", "Reset to Default Options and Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Cancel.setText(QtGui.QApplication.translate("dabnetParamDlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_OK.setText(QtGui.QApplication.translate("dabnetParamDlg", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_OutputList.setText(QtGui.QApplication.translate("dabnetParamDlg", "Output Variable List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_InputList.setText(QtGui.QApplication.translate("dabnetParamDlg", "Input Variable List", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_ForEachOutput.setTitle(QtGui.QApplication.translate("dabnetParamDlg", "For Each Output Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_UseSpecifiedPoleValue.setText(QtGui.QApplication.translate("dabnetParamDlg", "Use Specified Pole(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_OptimizeBothPoles.setText(QtGui.QApplication.translate("dabnetParamDlg", "Optimize Both Poles", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_OptimizeFastPole.setText(QtGui.QApplication.translate("dabnetParamDlg", "Optimize Fast Pole", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_OptimizeSlowPole.setText(QtGui.QApplication.translate("dabnetParamDlg", "Optimize Slow Pole", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumberOfNeurons.setText(QtGui.QApplication.translate("dabnetParamDlg", "Number of Neurons in Hidden Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_LinearModel.setText(QtGui.QApplication.translate("dabnetParamDlg", "Linear Model", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_ForEachInput.setTitle(QtGui.QApplication.translate("dabnetParamDlg", "For Each Input/Output Variable Pair", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Use2Poles.setText(QtGui.QApplication.translate("dabnetParamDlg", "Use Two Poles (Fast and Slow)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumberOfLaguerreStates.setText(QtGui.QApplication.translate("dabnetParamDlg", "Number of Laguerre States (Fast)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_EstimatedPoleValue.setText(QtGui.QApplication.translate("dabnetParamDlg", "Estimated Pole Value (Fast)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumberOfLaguerreStates2.setText(QtGui.QApplication.translate("dabnetParamDlg", "Number of Laguerre States (Slow)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_EstimatedPoleValue2.setText(QtGui.QApplication.translate("dabnetParamDlg", "Estimated Pole Value (Slow)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumberOfDelays.setText(QtGui.QApplication.translate("dabnetParamDlg", "Delay as Number of Sampling Times", None, QtGui.QApplication.UnicodeUTF8))

