# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step_change_dlg.ui'
#
# Created: Tue Nov 25 13:54:57 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_stepChangeDlg(object):
    def setupUi(self, stepChangeDlg):
        stepChangeDlg.setObjectName("stepChangeDlg")
        stepChangeDlg.resize(489, 479)
        self.gridLayout_2 = QtGui.QGridLayout(stepChangeDlg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_SamplingTime = QtGui.QLabel(stepChangeDlg)
        self.label_SamplingTime.setObjectName("label_SamplingTime")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_SamplingTime)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_SamplingTime = QtGui.QLineEdit(stepChangeDlg)
        self.lineEdit_SamplingTime.setEnabled(False)
        self.lineEdit_SamplingTime.setObjectName("lineEdit_SamplingTime")
        self.horizontalLayout.addWidget(self.lineEdit_SamplingTime)
        self.lineEdit_UnitSamplingTime = QtGui.QLineEdit(stepChangeDlg)
        self.lineEdit_UnitSamplingTime.setEnabled(False)
        self.lineEdit_UnitSamplingTime.setReadOnly(True)
        self.lineEdit_UnitSamplingTime.setObjectName("lineEdit_UnitSamplingTime")
        self.horizontalLayout.addWidget(self.lineEdit_UnitSamplingTime)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_SolverMinTime = QtGui.QLabel(stepChangeDlg)
        self.label_SolverMinTime.setObjectName("label_SolverMinTime")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_SolverMinTime)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_SolverMinTime = QtGui.QLineEdit(stepChangeDlg)
        self.lineEdit_SolverMinTime.setEnabled(False)
        self.lineEdit_SolverMinTime.setObjectName("lineEdit_SolverMinTime")
        self.horizontalLayout_2.addWidget(self.lineEdit_SolverMinTime)
        self.lineEdit_UnitSolverMinTime = QtGui.QLineEdit(stepChangeDlg)
        self.lineEdit_UnitSolverMinTime.setEnabled(False)
        self.lineEdit_UnitSolverMinTime.setReadOnly(True)
        self.lineEdit_UnitSolverMinTime.setObjectName("lineEdit_UnitSolverMinTime")
        self.horizontalLayout_2.addWidget(self.lineEdit_UnitSolverMinTime)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_NumberOfLHSPoints = QtGui.QLabel(stepChangeDlg)
        self.label_NumberOfLHSPoints.setObjectName("label_NumberOfLHSPoints")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_NumberOfLHSPoints)
        self.lineEdit_NumberOfLHSPoints = QtGui.QLineEdit(stepChangeDlg)
        self.lineEdit_NumberOfLHSPoints.setObjectName("lineEdit_NumberOfLHSPoints")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_NumberOfLHSPoints)
        self.label_NumberOfLHSSets = QtGui.QLabel(stepChangeDlg)
        self.label_NumberOfLHSSets.setObjectName("label_NumberOfLHSSets")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_NumberOfLHSSets)
        self.lineEdit_NumberOfLHSSets = QtGui.QLineEdit(stepChangeDlg)
        self.lineEdit_NumberOfLHSSets.setObjectName("lineEdit_NumberOfLHSSets")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_NumberOfLHSSets)
        self.checkBox_IncludeReverse = QtGui.QCheckBox(stepChangeDlg)
        self.checkBox_IncludeReverse.setObjectName("checkBox_IncludeReverse")
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.checkBox_IncludeReverse)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.groupBox_ForSelected = QtGui.QGroupBox(stepChangeDlg)
        self.groupBox_ForSelected.setObjectName("groupBox_ForSelected")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_ForSelected)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_SetList = QtGui.QListWidget(self.groupBox_ForSelected)
        self.listWidget_SetList.setObjectName("listWidget_SetList")
        self.gridLayout.addWidget(self.listWidget_SetList, 0, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEdit_Duration = QtGui.QLineEdit(self.groupBox_ForSelected)
        self.lineEdit_Duration.setObjectName("lineEdit_Duration")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_Duration)
        self.label_Duration = QtGui.QLabel(self.groupBox_ForSelected)
        self.label_Duration.setObjectName("label_Duration")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Duration)
        self.gridLayout.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_ForSelected, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Cancel = QtGui.QPushButton(stepChangeDlg)
        self.pushButton_Cancel.setAutoDefault(False)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_Cancel)
        self.pushButton_OK = QtGui.QPushButton(stepChangeDlg)
        self.pushButton_OK.setAutoDefault(False)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout_3.addWidget(self.pushButton_OK)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)

        self.retranslateUi(stepChangeDlg)
        QtCore.QMetaObject.connectSlotsByName(stepChangeDlg)
        stepChangeDlg.setTabOrder(self.lineEdit_SamplingTime, self.lineEdit_NumberOfLHSPoints)
        stepChangeDlg.setTabOrder(self.lineEdit_NumberOfLHSPoints, self.lineEdit_NumberOfLHSSets)
        stepChangeDlg.setTabOrder(self.lineEdit_NumberOfLHSSets, self.checkBox_IncludeReverse)
        stepChangeDlg.setTabOrder(self.checkBox_IncludeReverse, self.listWidget_SetList)
        stepChangeDlg.setTabOrder(self.listWidget_SetList, self.lineEdit_Duration)
        stepChangeDlg.setTabOrder(self.lineEdit_Duration, self.lineEdit_UnitSamplingTime)
        stepChangeDlg.setTabOrder(self.lineEdit_UnitSamplingTime, self.lineEdit_UnitSolverMinTime)

    def retranslateUi(self, stepChangeDlg):
        stepChangeDlg.setWindowTitle(QtGui.QApplication.translate("stepChangeDlg", "Setp Change Sequence Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SamplingTime.setText(QtGui.QApplication.translate("stepChangeDlg", "Sampling Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SolverMinTime.setText(QtGui.QApplication.translate("stepChangeDlg", "Solver Minimum Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumberOfLHSPoints.setText(QtGui.QApplication.translate("stepChangeDlg", "Number of LHS Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NumberOfLHSSets.setText(QtGui.QApplication.translate("stepChangeDlg", "Number of LHS Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_IncludeReverse.setText(QtGui.QApplication.translate("stepChangeDlg", "Include Reverse Step Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_ForSelected.setTitle(QtGui.QApplication.translate("stepChangeDlg", "For Each LHS Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Duration.setText(QtGui.QApplication.translate("stepChangeDlg", "Duraton of Step Change (Number of Time Intervals)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Cancel.setText(QtGui.QApplication.translate("stepChangeDlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_OK.setText(QtGui.QApplication.translate("stepChangeDlg", "OK", None, QtGui.QApplication.UnicodeUTF8))

