# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heatIntegration\heatIntegrationFrame_UI.ui'
#
# Created: Tue Aug 19 16:00:06 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_heatIntegrationFrame(object):
    def setupUi(self, heatIntegrationFrame):
        heatIntegrationFrame.setObjectName("heatIntegrationFrame")
        heatIntegrationFrame.resize(721, 603)
        heatIntegrationFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        heatIntegrationFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(heatIntegrationFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(heatIntegrationFrame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 14, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 11, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 12, 3, 1, 1)
        self.IPSteamConsEdit = QtGui.QLineEdit(self.tab)
        self.IPSteamConsEdit.setObjectName("IPSteamConsEdit")
        self.gridLayout_3.addWidget(self.IPSteamConsEdit, 11, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 9, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 13, 3, 1, 1)
        self.maxtimeEdit = QtGui.QLineEdit(self.tab)
        self.maxtimeEdit.setObjectName("maxtimeEdit")
        self.gridLayout_3.addWidget(self.maxtimeEdit, 6, 2, 1, 1)
        self.LPSteamConsEdit = QtGui.QLineEdit(self.tab)
        self.LPSteamConsEdit.setObjectName("LPSteamConsEdit")
        self.gridLayout_3.addWidget(self.LPSteamConsEdit, 13, 2, 1, 1)
        self.UtilityCostEdit = QtGui.QLineEdit(self.tab)
        self.UtilityCostEdit.setObjectName("UtilityCostEdit")
        self.gridLayout_3.addWidget(self.UtilityCostEdit, 14, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 14, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 11, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 9, 1, 1, 1)
        self.coolingWaterConsEdit = QtGui.QLineEdit(self.tab)
        self.coolingWaterConsEdit.setObjectName("coolingWaterConsEdit")
        self.gridLayout_3.addWidget(self.coolingWaterConsEdit, 9, 2, 1, 1)
        self.MinNoHxEdit = QtGui.QLineEdit(self.tab)
        self.MinNoHxEdit.setObjectName("MinNoHxEdit")
        self.gridLayout_3.addWidget(self.MinNoHxEdit, 12, 2, 1, 1)
        self.netPowerEdit = QtGui.QLineEdit(self.tab)
        self.netPowerEdit.setObjectName("netPowerEdit")
        self.gridLayout_3.addWidget(self.netPowerEdit, 7, 2, 1, 1)
        self.hratEdit = QtGui.QLineEdit(self.tab)
        self.hratEdit.setObjectName("hratEdit")
        self.gridLayout_3.addWidget(self.hratEdit, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 12, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 10, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 3, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 1, 1, 1)
        self.feedWaterHeatAddEdit = QtGui.QLineEdit(self.tab)
        self.feedWaterHeatAddEdit.setObjectName("feedWaterHeatAddEdit")
        self.gridLayout_3.addWidget(self.feedWaterHeatAddEdit, 10, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 13, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 10, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 7, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 7, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_7.setBuddy(self.UtilityCostEdit)
        self.label_10.setBuddy(self.IPSteamConsEdit)
        self.label_13.setBuddy(self.coolingWaterConsEdit)
        self.label_9.setBuddy(self.MinNoHxEdit)
        self.label_11.setBuddy(self.feedWaterHeatAddEdit)
        self.label.setBuddy(self.hratEdit)
        self.label_8.setBuddy(self.LPSteamConsEdit)
        self.label_2.setBuddy(self.netPowerEdit)
        self.label_4.setBuddy(self.maxtimeEdit)

        self.retranslateUi(heatIntegrationFrame)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(heatIntegrationFrame)

    def retranslateUi(self, heatIntegrationFrame):
        heatIntegrationFrame.setWindowTitle(QtGui.QApplication.translate("heatIntegrationFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Utility.Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Intermediate-pressure steam (230 C) consumption (Cost: $8.04/GJ) (GJ/hr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Minimum number of heat exchangers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Cooling water (20 C) consumption (Cost: $0.21/GJ) (GJ/hr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Low-pressure steam (164 C) consumption (Cost: $6.25/GJ) (GJ/hr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Total utility cost ($/hr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("heatIntegrationFrame", "IP_Steam.Consumption", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Cooling_Water.Consumption", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Min.No.HX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("heatIntegrationFrame", "FH.Heat.Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Minimum approach temperature (K)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Maximum allowable time for heat integration (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Hrat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("heatIntegrationFrame", "LP_Steam.Consumption", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Heat addition to feed water heaters (GJ/hr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Net power output without CCS (MW)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Net.Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("heatIntegrationFrame", "Max.Time", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("heatIntegrationFrame", "Heat Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("heatIntegrationFrame", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("heatIntegrationFrame", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("heatIntegrationFrame", "Steam Cycle", None, QtGui.QApplication.UnicodeUTF8))

