# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -qr requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Install FOQUS
          command: |
            . venv/bin/activate
            python3 setup.py -q install

      - run:
          name: Setup testing env
          command: |
            . venv/bin/activate
            pip install -q pytest
            pip install -q coverage

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            coverage run -m pytest
            coverage report
            coverage html  # Generate html report

      - store_artifacts:
          path: htmlcov
