# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -qr requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Install FOQUS
          command: |
            . venv/bin/activate
            python3 setup.py -q install

      - run:
          name: Setup Testing Environment
          command: |
            . venv/bin/activate
            pip install -q pytest coverage pylint

      - run:
          name: Run PyLint
          command: |
            . venv/bin/activate
            pylint -E foqus_lib --extension-pkg-whitelist=PyQt5 --ignored-modules=win32process,win32api,adodbapi || true

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            coverage run -m pytest
            coverage report --omit=*site-packages* --fail-under=22
            coverage html --omit=*site-packages*  # Generate html report

      - store_artifacts:
          path: htmlcov
