# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'surrogate\surrogateFrame_UI.ui'
#
# Created: Wed Apr 20 14:22:36 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_surrogateFrame(object):
    def setupUi(self, surrogateFrame):
        surrogateFrame.setObjectName("surrogateFrame")
        surrogateFrame.resize(979, 778)
        surrogateFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        surrogateFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(surrogateFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtGui.QPushButton(surrogateFrame)
        self.runButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setIconSize(QtCore.QSize(24, 24))
        self.runButton.setFlat(True)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.stopButton = QtGui.QPushButton(surrogateFrame)
        self.stopButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setIconSize(QtCore.QSize(24, 24))
        self.stopButton.setFlat(True)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.label = QtGui.QLabel(surrogateFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.toolSelectBox = QtGui.QComboBox(surrogateFrame)
        self.toolSelectBox.setObjectName("toolSelectBox")
        self.toolSelectBox.addItem("")
        self.toolSelectBox.addItem("")
        self.toolSelectBox.addItem("")
        self.toolSelectBox.addItem("")
        self.horizontalLayout.addWidget(self.toolSelectBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(surrogateFrame)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.methodDescriptionBox = QtGui.QTextBrowser(self.groupBox)
        self.methodDescriptionBox.setObjectName("methodDescriptionBox")
        self.verticalLayout_3.addWidget(self.methodDescriptionBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.toolBox = QtGui.QTabWidget(surrogateFrame)
        self.toolBox.setObjectName("toolBox")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addSamplesButton = QtGui.QPushButton(self.tab)
        self.addSamplesButton.setObjectName("addSamplesButton")
        self.horizontalLayout_2.addWidget(self.addSamplesButton)
        self.irevealFSButton = QtGui.QPushButton(self.tab)
        self.irevealFSButton.setObjectName("irevealFSButton")
        self.horizontalLayout_2.addWidget(self.irevealFSButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.toolBox.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addAllInButton = QtGui.QPushButton(self.groupBox_2)
        self.addAllInButton.setObjectName("addAllInButton")
        self.horizontalLayout_4.addWidget(self.addAllInButton)
        self.delAllInButton = QtGui.QPushButton(self.groupBox_2)
        self.delAllInButton.setObjectName("delAllInButton")
        self.horizontalLayout_4.addWidget(self.delAllInButton)
        self.ivGeneralButton1 = QtGui.QPushButton(self.groupBox_2)
        self.ivGeneralButton1.setObjectName("ivGeneralButton1")
        self.horizontalLayout_4.addWidget(self.ivGeneralButton1)
        self.ivGeneralButton2 = QtGui.QPushButton(self.groupBox_2)
        self.ivGeneralButton2.setObjectName("ivGeneralButton2")
        self.horizontalLayout_4.addWidget(self.ivGeneralButton2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.inputTable = QtGui.QTableWidget(self.groupBox_2)
        self.inputTable.setObjectName("inputTable")
        self.inputTable.setColumnCount(3)
        self.inputTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.inputTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.inputTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.inputTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_5.addWidget(self.inputTable)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addAllOutButton = QtGui.QPushButton(self.groupBox_3)
        self.addAllOutButton.setObjectName("addAllOutButton")
        self.horizontalLayout_3.addWidget(self.addAllOutButton)
        self.delAllOutButton = QtGui.QPushButton(self.groupBox_3)
        self.delAllOutButton.setObjectName("delAllOutButton")
        self.horizontalLayout_3.addWidget(self.delAllOutButton)
        self.ovGeneralButton1 = QtGui.QPushButton(self.groupBox_3)
        self.ovGeneralButton1.setObjectName("ovGeneralButton1")
        self.horizontalLayout_3.addWidget(self.ovGeneralButton1)
        self.ovGeneralButton2 = QtGui.QPushButton(self.groupBox_3)
        self.ovGeneralButton2.setObjectName("ovGeneralButton2")
        self.horizontalLayout_3.addWidget(self.ovGeneralButton2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.outputTable = QtGui.QTableWidget(self.groupBox_3)
        self.outputTable.setObjectName("outputTable")
        self.outputTable.setColumnCount(1)
        self.outputTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.outputTable.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.outputTable)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.toolBox.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.settingsStack = QtGui.QStackedWidget(self.tab_3)
        self.settingsStack.setFrameShape(QtGui.QFrame.NoFrame)
        self.settingsStack.setLineWidth(0)
        self.settingsStack.setObjectName("settingsStack")
        self.verticalLayout_12.addWidget(self.settingsStack)
        self.toolBox.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.monitorTextBox = QtGui.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.monitorTextBox.setFont(font)
        self.monitorTextBox.setObjectName("monitorTextBox")
        self.verticalLayout_13.addWidget(self.monitorTextBox)
        self.toolBox.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.label.setBuddy(self.toolSelectBox)

        self.retranslateUi(surrogateFrame)
        self.toolBox.setCurrentIndex(0)
        self.settingsStack.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(surrogateFrame)

    def retranslateUi(self, surrogateFrame):
        surrogateFrame.setWindowTitle(QtGui.QApplication.translate("surrogateFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("surrogateFrame", "Tool:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolSelectBox.setItemText(0, QtGui.QApplication.translate("surrogateFrame", "ALAMO", None, QtGui.QApplication.UnicodeUTF8))
        self.toolSelectBox.setItemText(1, QtGui.QApplication.translate("surrogateFrame", "DRM-Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.toolSelectBox.setItemText(2, QtGui.QApplication.translate("surrogateFrame", "iREVEAL", None, QtGui.QApplication.UnicodeUTF8))
        self.toolSelectBox.setItemText(3, QtGui.QApplication.translate("surrogateFrame", "PSUADE", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("surrogateFrame", "Method Description", None, QtGui.QApplication.UnicodeUTF8))
        self.addSamplesButton.setText(QtGui.QApplication.translate("surrogateFrame", "Add Samples...", None, QtGui.QApplication.UnicodeUTF8))
        self.irevealFSButton.setText(QtGui.QApplication.translate("surrogateFrame", "Create Flowsheet from iREVEAL File...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tab), QtGui.QApplication.translate("surrogateFrame", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("surrogateFrame", "Input Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.addAllInButton.setText(QtGui.QApplication.translate("surrogateFrame", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.delAllInButton.setText(QtGui.QApplication.translate("surrogateFrame", "Select None", None, QtGui.QApplication.UnicodeUTF8))
        self.ivGeneralButton1.setText(QtGui.QApplication.translate("surrogateFrame", "Button1", None, QtGui.QApplication.UnicodeUTF8))
        self.ivGeneralButton2.setText(QtGui.QApplication.translate("surrogateFrame", "Button2", None, QtGui.QApplication.UnicodeUTF8))
        self.inputTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("surrogateFrame", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.inputTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("surrogateFrame", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.inputTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("surrogateFrame", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("surrogateFrame", "Output Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.addAllOutButton.setText(QtGui.QApplication.translate("surrogateFrame", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.delAllOutButton.setText(QtGui.QApplication.translate("surrogateFrame", "Select None", None, QtGui.QApplication.UnicodeUTF8))
        self.ovGeneralButton1.setText(QtGui.QApplication.translate("surrogateFrame", "Button1", None, QtGui.QApplication.UnicodeUTF8))
        self.ovGeneralButton2.setText(QtGui.QApplication.translate("surrogateFrame", "Button2", None, QtGui.QApplication.UnicodeUTF8))
        self.outputTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("surrogateFrame", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tab_2), QtGui.QApplication.translate("surrogateFrame", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tab_3), QtGui.QApplication.translate("surrogateFrame", "Method Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tab_4), QtGui.QApplication.translate("surrogateFrame", "Execution", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
