# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ouuSetupFrame.ui'
#
# Created: Thu May 26 16:32:35 2016
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ouuSetupFrame(object):
    def setupUi(self, ouuSetupFrame):
        ouuSetupFrame.setObjectName("ouuSetupFrame")
        ouuSetupFrame.resize(995, 835)
        ouuSetupFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        ouuSetupFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_9 = QtGui.QGridLayout(ouuSetupFrame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_6 = QtGui.QGroupBox(ouuSetupFrame)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.node_radio = QtGui.QRadioButton(self.groupBox_6)
        self.node_radio.setObjectName("node_radio")
        self.horizontalLayout_12.addWidget(self.node_radio)
        self.node_combo = QtGui.QComboBox(self.groupBox_6)
        self.node_combo.setObjectName("node_combo")
        self.horizontalLayout_12.addWidget(self.node_combo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.modelFile_radio = QtGui.QRadioButton(self.groupBox_6)
        self.modelFile_radio.setObjectName("modelFile_radio")
        self.horizontalLayout_13.addWidget(self.modelFile_radio)
        self.modelFile_edit = QtGui.QLineEdit(self.groupBox_6)
        self.modelFile_edit.setReadOnly(True)
        self.modelFile_edit.setObjectName("modelFile_edit")
        self.horizontalLayout_13.addWidget(self.modelFile_edit)
        self.modelFileBrowse_button = QtGui.QPushButton(self.groupBox_6)
        self.modelFileBrowse_button.setObjectName("modelFileBrowse_button")
        self.horizontalLayout_13.addWidget(self.modelFileBrowse_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.gridLayout_12.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(ouuSetupFrame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.input_table = InputPriorTable(self.groupBox_5)
        self.input_table.setObjectName("input_table")
        self.input_table.setColumnCount(10)
        self.input_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.input_table.setHorizontalHeaderItem(9, item)
        self.gridLayout_13.addWidget(self.input_table, 0, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 1, 1, 1)
        self.setFixed_button = QtGui.QPushButton(self.groupBox_5)
        self.setFixed_button.setObjectName("setFixed_button")
        self.gridLayout_11.addWidget(self.setFixed_button, 0, 2, 1, 1)
        self.setX1_button = QtGui.QPushButton(self.groupBox_5)
        self.setX1_button.setObjectName("setX1_button")
        self.gridLayout_11.addWidget(self.setX1_button, 0, 3, 1, 1)
        self.setX2_button = QtGui.QPushButton(self.groupBox_5)
        self.setX2_button.setObjectName("setX2_button")
        self.gridLayout_11.addWidget(self.setX2_button, 0, 4, 1, 1)
        self.setX3_button = QtGui.QPushButton(self.groupBox_5)
        self.setX3_button.setObjectName("setX3_button")
        self.gridLayout_11.addWidget(self.setX3_button, 0, 5, 1, 1)
        self.setX4_button = QtGui.QPushButton(self.groupBox_5)
        self.setX4_button.setObjectName("setX4_button")
        self.gridLayout_11.addWidget(self.setX4_button, 0, 6, 1, 1)
        self.fixedCount_static = QtGui.QLabel(self.groupBox_5)
        self.fixedCount_static.setAlignment(QtCore.Qt.AlignCenter)
        self.fixedCount_static.setObjectName("fixedCount_static")
        self.gridLayout_11.addWidget(self.fixedCount_static, 1, 2, 1, 1)
        self.x1Count_static = QtGui.QLabel(self.groupBox_5)
        self.x1Count_static.setAlignment(QtCore.Qt.AlignCenter)
        self.x1Count_static.setObjectName("x1Count_static")
        self.gridLayout_11.addWidget(self.x1Count_static, 1, 3, 1, 1)
        self.x2Count_static = QtGui.QLabel(self.groupBox_5)
        self.x2Count_static.setAlignment(QtCore.Qt.AlignCenter)
        self.x2Count_static.setObjectName("x2Count_static")
        self.gridLayout_11.addWidget(self.x2Count_static, 1, 4, 1, 1)
        self.x3Count_static = QtGui.QLabel(self.groupBox_5)
        self.x3Count_static.setAlignment(QtCore.Qt.AlignCenter)
        self.x3Count_static.setObjectName("x3Count_static")
        self.gridLayout_11.addWidget(self.x3Count_static, 1, 5, 1, 1)
        self.x4Count_static = QtGui.QLabel(self.groupBox_5)
        self.x4Count_static.setAlignment(QtCore.Qt.AlignCenter)
        self.x4Count_static.setObjectName("x4Count_static")
        self.gridLayout_11.addWidget(self.x4Count_static, 1, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 0, 7, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.tabs = QtGui.QTabWidget(ouuSetupFrame)
        self.tabs.setObjectName("tabs")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.secondarySolver_label = QtGui.QLabel(self.groupBox_2)
        self.secondarySolver_label.setObjectName("secondarySolver_label")
        self.horizontalLayout_7.addWidget(self.secondarySolver_label)
        self.secondarySolver_combo = QtGui.QComboBox(self.groupBox_2)
        self.secondarySolver_combo.setObjectName("secondarySolver_combo")
        self.secondarySolver_combo.addItem("")
        self.secondarySolver_combo.addItem("")
        self.horizontalLayout_7.addWidget(self.secondarySolver_combo)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.primarySolver_label = QtGui.QLabel(self.groupBox_2)
        self.primarySolver_label.setObjectName("primarySolver_label")
        self.horizontalLayout_6.addWidget(self.primarySolver_label)
        self.primarySolver_combo = QtGui.QComboBox(self.groupBox_2)
        self.primarySolver_combo.setObjectName("primarySolver_combo")
        self.primarySolver_combo.addItem("")
        self.horizontalLayout_6.addWidget(self.primarySolver_combo)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.G_label = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.G_label.setFont(font)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.output_label = QtGui.QLabel(self.groupBox_4)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setObjectName("output_label")
        self.horizontalLayout_3.addWidget(self.output_label)
        self.output_combo = QtGui.QComboBox(self.groupBox_4)
        self.output_combo.setObjectName("output_combo")
        self.horizontalLayout_3.addWidget(self.output_combo)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 3)
        spacerItem6 = QtGui.QSpacerItem(319, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 4, 1, 3)
        self.mean_radio = QtGui.QRadioButton(self.groupBox_4)
        self.mean_radio.setObjectName("mean_radio")
        self.gridLayout.addWidget(self.mean_radio, 1, 0, 1, 1)
        self.meanWithBeta_radio = QtGui.QRadioButton(self.groupBox_4)
        self.meanWithBeta_radio.setObjectName("meanWithBeta_radio")
        self.gridLayout.addWidget(self.meanWithBeta_radio, 2, 0, 1, 1)
        self.alpha_static = QtGui.QLabel(self.groupBox_4)
        self.alpha_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.alpha_static.setObjectName("alpha_static")
        self.gridLayout.addWidget(self.alpha_static, 2, 2, 1, 1)
        self.betaDoubleSpin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.betaDoubleSpin.setDecimals(4)
        self.betaDoubleSpin.setMinimum(-1000.0)
        self.betaDoubleSpin.setMaximum(1000.0)
        self.betaDoubleSpin.setSingleStep(0.1)
        self.betaDoubleSpin.setObjectName("betaDoubleSpin")
        self.gridLayout.addWidget(self.betaDoubleSpin, 2, 3, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(312, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 6, 1, 1)
        self.alpha_radio = QtGui.QRadioButton(self.groupBox_4)
        self.alpha_radio.setObjectName("alpha_radio")
        self.gridLayout.addWidget(self.alpha_radio, 3, 0, 1, 2)
        self.epsilon_static = QtGui.QLabel(self.groupBox_4)
        self.epsilon_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.epsilon_static.setObjectName("epsilon_static")
        self.gridLayout.addWidget(self.epsilon_static, 3, 2, 1, 1)
        self.alphaDoubleSpin = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.alphaDoubleSpin.setDecimals(4)
        self.alphaDoubleSpin.setMinimum(0.5)
        self.alphaDoubleSpin.setMaximum(1.0)
        self.alphaDoubleSpin.setSingleStep(0.01)
        self.alphaDoubleSpin.setObjectName("alphaDoubleSpin")
        self.gridLayout.addWidget(self.alphaDoubleSpin, 3, 3, 1, 2)
        spacerItem8 = QtGui.QSpacerItem(312, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 3, 6, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 5, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_3, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.z3_group = QtGui.QGroupBox(self.tab)
        self.z3_group.setObjectName("z3_group")
        self.gridLayout_6 = QtGui.QGridLayout(self.z3_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtGui.QLabel(self.z3_group)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.x3FileBrowse_button = QtGui.QPushButton(self.z3_group)
        self.x3FileBrowse_button.setObjectName("x3FileBrowse_button")
        self.horizontalLayout_4.addWidget(self.x3FileBrowse_button)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.z3_table = QtGui.QTableWidget(self.z3_group)
        self.z3_table.setMinimumSize(QtCore.QSize(0, 100))
        self.z3_table.setObjectName("z3_table")
        self.z3_table.setColumnCount(0)
        self.z3_table.setRowCount(0)
        self.gridLayout_6.addWidget(self.z3_table, 0, 1, 2, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.compressSamples_chk = QtGui.QCheckBox(self.z3_group)
        self.compressSamples_chk.setObjectName("compressSamples_chk")
        self.horizontalLayout_5.addWidget(self.compressSamples_chk)
        self.calcScenarios_button = QtGui.QPushButton(self.z3_group)
        self.calcScenarios_button.setObjectName("calcScenarios_button")
        self.horizontalLayout_5.addWidget(self.calcScenarios_button)
        self.scenarioSelect_static = QtGui.QLabel(self.z3_group)
        self.scenarioSelect_static.setObjectName("scenarioSelect_static")
        self.horizontalLayout_5.addWidget(self.scenarioSelect_static)
        self.scenarioSelect_combo = QtGui.QComboBox(self.z3_group)
        self.scenarioSelect_combo.setObjectName("scenarioSelect_combo")
        self.horizontalLayout_5.addWidget(self.scenarioSelect_combo)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.z3_group, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 2, 0, 1, 1)
        self.z4_group = QtGui.QGroupBox(self.tab)
        self.z4_group.setMinimumSize(QtCore.QSize(0, 0))
        self.z4_group.setMaximumSize(QtCore.QSize(16777215, 180))
        self.z4_group.setObjectName("z4_group")
        self.gridLayout_5 = QtGui.QGridLayout(self.z4_group)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.z4NewSample_radio = QtGui.QRadioButton(self.z4_group)
        self.z4NewSample_radio.setObjectName("z4NewSample_radio")
        self.verticalLayout.addWidget(self.z4NewSample_radio)
        spacerItem11 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.x4SampleScheme_label = QtGui.QLabel(self.z4_group)
        self.x4SampleScheme_label.setObjectName("x4SampleScheme_label")
        self.gridLayout_4.addWidget(self.x4SampleScheme_label, 0, 0, 1, 1)
        self.x4SampleScheme_combo = QtGui.QComboBox(self.z4_group)
        self.x4SampleScheme_combo.setObjectName("x4SampleScheme_combo")
        self.x4SampleScheme_combo.addItem("")
        self.x4SampleScheme_combo.addItem("")
        self.gridLayout_4.addWidget(self.x4SampleScheme_combo, 0, 1, 1, 1)
        self.x4SampleSize_label = QtGui.QLabel(self.z4_group)
        self.x4SampleSize_label.setObjectName("x4SampleSize_label")
        self.gridLayout_4.addWidget(self.x4SampleSize_label, 1, 0, 1, 1)
        self.x4SampleSize_spin = QtGui.QSpinBox(self.z4_group)
        self.x4SampleSize_spin.setMaximum(1000)
        self.x4SampleSize_spin.setObjectName("x4SampleSize_spin")
        self.gridLayout_4.addWidget(self.x4SampleSize_spin, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.z4_table = QtGui.QTableWidget(self.z4_group)
        self.z4_table.setMinimumSize(QtCore.QSize(400, 0))
        self.z4_table.setMaximumSize(QtCore.QSize(16777215, 500))
        self.z4_table.setObjectName("z4_table")
        self.z4_table.setColumnCount(0)
        self.z4_table.setRowCount(0)
        self.gridLayout_5.addWidget(self.z4_table, 0, 3, 3, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.z4LoadSample_radio = QtGui.QRadioButton(self.z4_group)
        self.z4LoadSample_radio.setObjectName("z4LoadSample_radio")
        self.horizontalLayout.addWidget(self.z4LoadSample_radio)
        self.x4FileBrowse_button = QtGui.QPushButton(self.z4_group)
        self.x4FileBrowse_button.setObjectName("x4FileBrowse_button")
        self.horizontalLayout.addWidget(self.x4FileBrowse_button)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.x4RSMethod_check = QtGui.QCheckBox(self.z4_group)
        self.x4RSMethod_check.setObjectName("x4RSMethod_check")
        self.gridLayout_5.addWidget(self.x4RSMethod_check, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.z4SubsetSize_label = QtGui.QLabel(self.z4_group)
        self.z4SubsetSize_label.setObjectName("z4SubsetSize_label")
        self.horizontalLayout_2.addWidget(self.z4SubsetSize_label)
        self.z4SubsetSize_spin = QtGui.QSpinBox(self.z4_group)
        self.z4SubsetSize_spin.setMaximum(10000000)
        self.z4SubsetSize_spin.setObjectName("z4SubsetSize_spin")
        self.horizontalLayout_2.addWidget(self.z4SubsetSize_spin)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 1, 1, 2)
        self.gridLayout_8.addWidget(self.z4_group, 1, 0, 1, 1)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem12 = QtGui.QSpacerItem(406, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 0, 0, 1, 1)
        self.run_button = QtGui.QPushButton(self.tab_2)
        self.run_button.setObjectName("run_button")
        self.gridLayout_10.addWidget(self.run_button, 0, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(405, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem13, 0, 2, 1, 1)
        self.summary_group = QtGui.QGroupBox(self.tab_2)
        self.summary_group.setObjectName("summary_group")
        self.gridLayout_17 = QtGui.QGridLayout(self.summary_group)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.bestValue_table = QtGui.QTableWidget(self.summary_group)
        self.bestValue_table.setObjectName("bestValue_table")
        self.bestValue_table.setColumnCount(0)
        self.bestValue_table.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.bestValue_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bestValue_table.setVerticalHeaderItem(1, item)
        self.bestValue_table.horizontalHeader().setVisible(False)
        self.gridLayout_17.addWidget(self.bestValue_table, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.summary_group, 1, 0, 1, 2)
        self.progress_group = QtGui.QGroupBox(self.tab_2)
        self.progress_group.setObjectName("progress_group")
        self.gridLayout_15 = QtGui.QGridLayout(self.progress_group)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.progressScrollArea = QtGui.QScrollArea(self.progress_group)
        self.progressScrollArea.setWidgetResizable(True)
        self.progressScrollArea.setObjectName("progressScrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 410, 364))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_16 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.progressScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_15.addWidget(self.progressScrollArea, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.progress_group, 1, 2, 1, 1)
        self.tabs.addTab(self.tab_2, "")
        self.gridLayout_9.addWidget(self.tabs, 2, 0, 1, 1)

        self.retranslateUi(ouuSetupFrame)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ouuSetupFrame)

    def retranslateUi(self, ouuSetupFrame):
        ouuSetupFrame.setWindowTitle(QtGui.QApplication.translate("ouuSetupFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.node_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "Choose this option if your simulation model\n"
"is a node in the flowsheet.", None, QtGui.QApplication.UnicodeUTF8))
        self.node_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "Choose Flowsheet Node", None, QtGui.QApplication.UnicodeUTF8))
        self.modelFile_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "Choose this option if you have a PSUADE file\n"
"and the model is specified as a “driver” within.", None, QtGui.QApplication.UnicodeUTF8))
        self.modelFile_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "Load Model From File", None, QtGui.QApplication.UnicodeUTF8))
        self.modelFileBrowse_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "Designate input type:\n"
"Fixed for deterministic inputs\n"
"Z1 for primary optimization inputs\n"
"Z2 for recourse optimization inputs\n"
"Z3 for discrete UQ inputs (characterized by scenarios)\n"
"Z4 for continuous UQ inputs (characterized by PDFs)", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ouuSetupFrame", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ouuSetupFrame", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("ouuSetupFrame", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("ouuSetupFrame", "Scale (Z1)", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("ouuSetupFrame", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("ouuSetupFrame", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("ouuSetupFrame", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("ouuSetupFrame", "PDF (Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("ouuSetupFrame", "PDF Param1 (Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.input_table.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("ouuSetupFrame", "PDF Param2 (Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Set Selected As:", None, QtGui.QApplication.UnicodeUTF8))
        self.setFixed_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Fixed Vars", None, QtGui.QApplication.UnicodeUTF8))
        self.setX1_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Primary Opt Vars (Z1)", None, QtGui.QApplication.UnicodeUTF8))
        self.setX2_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Recourse Opt Vars (Z2) ", None, QtGui.QApplication.UnicodeUTF8))
        self.setX3_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Discrete RVs (Z3)", None, QtGui.QApplication.UnicodeUTF8))
        self.setX4_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Continuous RVs (Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedCount_static.setText(QtGui.QApplication.translate("ouuSetupFrame", " 0", None, QtGui.QApplication.UnicodeUTF8))
        self.x1Count_static.setText(QtGui.QApplication.translate("ouuSetupFrame", " 0", None, QtGui.QApplication.UnicodeUTF8))
        self.x2Count_static.setText(QtGui.QApplication.translate("ouuSetupFrame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.x3Count_static.setText(QtGui.QApplication.translate("ouuSetupFrame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.x4Count_static.setText(QtGui.QApplication.translate("ouuSetupFrame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ouuSetupFrame", "Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Optimization Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.secondarySolver_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Inner Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.secondarySolver_combo.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "The inner solver computes the optimal values\n"
"for the recourse optimization inputs (Z2).\n"
"The model can be used as a simulator or an optimizer.\n"
"As a simulator, BOBYQA will be used for optimization.\n"
"As an optimizer, the model itself will compute the optimal values.", None, QtGui.QApplication.UnicodeUTF8))
        self.secondarySolver_combo.setItemText(0, QtGui.QApplication.translate("ouuSetupFrame", "Use model as simulator: G(Z1,Z2,Z3,Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.secondarySolver_combo.setItemText(1, QtGui.QApplication.translate("ouuSetupFrame", "Use model as optimizer: min_Z2 G(Z1,Z2,Z3,Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.primarySolver_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Outer Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.primarySolver_combo.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "The outer solver computes the optimal values\n"
"for the primary optimization inputs (Z1).", None, QtGui.QApplication.UnicodeUTF8))
        self.primarySolver_combo.setItemText(0, QtGui.QApplication.translate("ouuSetupFrame", "BOBYQA", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Objective Function for Optimization Under Uncertainty (OUU)", None, QtGui.QApplication.UnicodeUTF8))
        self.G_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "G(Z1,Z2,Z3,Z4) is the simulation driver in the model.", None, QtGui.QApplication.UnicodeUTF8))
        self.output_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Output for OUU", None, QtGui.QApplication.UnicodeUTF8))
        self.mean_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "In the presence of UQ inputs, the objective function G\n"
"needs to be modified to take uncertainty into account.\n"
"Choose the one that fits your analysis.", None, QtGui.QApplication.UnicodeUTF8))
        self.mean_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "Mean of G(Z1,Z2,Z3,Z4) with respect to Z3 and Z4", None, QtGui.QApplication.UnicodeUTF8))
        self.meanWithBeta_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "In the presence of UQ inputs, the objective function G\n"
"needs to be modified to take uncertainty into account.\n"
"Choose the one that fits your analysis.", None, QtGui.QApplication.UnicodeUTF8))
        self.meanWithBeta_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "Mean of G(Z1,Z2,Z3,Z4) + beta*std(G(Z1,Z2,Z3,Z4))", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha_static.setText(QtGui.QApplication.translate("ouuSetupFrame", "beta", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "In the presence of UQ inputs, the objective function G\n"
"needs to be modified to take uncertainty into account.\n"
"Choose the one that fits your analysis.", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "G(Z1,Z2,Z3*,Z4*) s.t. P(G(Z1,Z2,Z3,Z4) > G(Z1,Z2,Z3*,Z4*)) = 1 - alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.epsilon_static.setText(QtGui.QApplication.translate("ouuSetupFrame", "alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ouuSetupFrame", "e.g. 90% probability P90: alpha = 0.9", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QtGui.QApplication.translate("ouuSetupFrame", "Optimization Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.z3_group.setTitle(QtGui.QApplication.translate("ouuSetupFrame", " Discrete Random Variables (Z3)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ouuSetupFrame", "Load existing sample for Z3", None, QtGui.QApplication.UnicodeUTF8))
        self.x3FileBrowse_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.compressSamples_chk.setText(QtGui.QApplication.translate("ouuSetupFrame", "Compress number of samples", None, QtGui.QApplication.UnicodeUTF8))
        self.calcScenarios_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Calculate candidate sample sizes", None, QtGui.QApplication.UnicodeUTF8))
        self.scenarioSelect_static.setText(QtGui.QApplication.translate("ouuSetupFrame", "Select number of samples:", None, QtGui.QApplication.UnicodeUTF8))
        self.z4_group.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Continuous Random Variables (Z4)", None, QtGui.QApplication.UnicodeUTF8))
        self.z4NewSample_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "If your model has continuous UQ inputs, you can\n"
"(1) generate a new ensemble, or \n"
"(2) load an existing ensemble.", None, QtGui.QApplication.UnicodeUTF8))
        self.z4NewSample_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "Generate new sample for Z4", None, QtGui.QApplication.UnicodeUTF8))
        self.x4SampleScheme_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Sample Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.x4SampleScheme_combo.setItemText(0, QtGui.QApplication.translate("ouuSetupFrame", "LHS", None, QtGui.QApplication.UnicodeUTF8))
        self.x4SampleScheme_combo.setItemText(1, QtGui.QApplication.translate("ouuSetupFrame", "Factorial", None, QtGui.QApplication.UnicodeUTF8))
        self.x4SampleSize_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Sample Size", None, QtGui.QApplication.UnicodeUTF8))
        self.z4LoadSample_radio.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "If your model has continuous UQ inputs, you can\n"
"(1) generate a new ensemble, or \n"
"(2) load an existing ensemble.", None, QtGui.QApplication.UnicodeUTF8))
        self.z4LoadSample_radio.setText(QtGui.QApplication.translate("ouuSetupFrame", "Load existing sample for Z4", None, QtGui.QApplication.UnicodeUTF8))
        self.x4FileBrowse_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.x4RSMethod_check.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "If your Z4 ensemble is small and/or the input-to-output\n"
"mapping can be approximated by a smooth function, \n"
"you can choose to use some or all of the points in your\n"
"ensemble to train a response surface. The trained\n"
"response surface will be used to evaluate the OUU\n"
"objective function more accurately.", None, QtGui.QApplication.UnicodeUTF8))
        self.x4RSMethod_check.setText(QtGui.QApplication.translate("ouuSetupFrame", "Use Response Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.z4SubsetSize_label.setText(QtGui.QApplication.translate("ouuSetupFrame", "Response Surface Sample Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), QtGui.QApplication.translate("ouuSetupFrame", "UQ Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.run_button.setToolTip(QtGui.QApplication.translate("ouuSetupFrame", "Click to start OUU.\n"
"Progress will be shown below. ", None, QtGui.QApplication.UnicodeUTF8))
        self.run_button.setText(QtGui.QApplication.translate("ouuSetupFrame", "Run OUU", None, QtGui.QApplication.UnicodeUTF8))
        self.summary_group.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Best So Far", None, QtGui.QApplication.UnicodeUTF8))
        self.bestValue_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ouuSetupFrame", "Iteration", None, QtGui.QApplication.UnicodeUTF8))
        self.bestValue_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ouuSetupFrame", "Objective", None, QtGui.QApplication.UnicodeUTF8))
        self.progress_group.setTitle(QtGui.QApplication.translate("ouuSetupFrame", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), QtGui.QApplication.translate("ouuSetupFrame", "Launch/Progress", None, QtGui.QApplication.UnicodeUTF8))

from foqus_lib.gui.uq.InputPriorTable import InputPriorTable
