# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optimization\optMonitor_UI.ui'
#
# Created: Thu Mar 26 14:05:00 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_optMonitor(object):
    def setupUi(self, optMonitor):
        optMonitor.setObjectName("optMonitor")
        optMonitor.resize(863, 634)
        optMonitor.setMinimumSize(QtCore.QSize(100, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/opt48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        optMonitor.setWindowIcon(icon)
        optMonitor.setFrameShape(QtGui.QFrame.StyledPanel)
        optMonitor.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(optMonitor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtGui.QPushButton(optMonitor)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.startButton.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.startButton.setIcon(icon1)
        self.startButton.setIconSize(QtCore.QSize(24, 24))
        self.startButton.setFlat(False)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(optMonitor)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.stopButton.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.stopButton.setFont(font)
        self.stopButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(24, 24))
        self.stopButton.setFlat(False)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(optMonitor)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.delayEdit = QtGui.QLineEdit(optMonitor)
        self.delayEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.delayEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.delayEdit.setObjectName("delayEdit")
        self.horizontalLayout.addWidget(self.delayEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mdiArea = QtGui.QMdiArea(optMonitor)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout_2.addWidget(self.mdiArea)

        self.retranslateUi(optMonitor)
        QtCore.QMetaObject.connectSlotsByName(optMonitor)

    def retranslateUi(self, optMonitor):
        optMonitor.setWindowTitle(QtGui.QApplication.translate("optMonitor", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("optMonitor", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("optMonitor", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("optMonitor", "Update delay (ms):", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
