# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optimization\optSampleGenDialog_UI.ui'
#
# Created: Tue Jun 02 11:52:10 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_optSampleGenDialog(object):
    def setupUi(self, optSampleGenDialog):
        optSampleGenDialog.setObjectName("optSampleGenDialog")
        optSampleGenDialog.resize(610, 530)
        self.verticalLayout = QtGui.QVBoxLayout(optSampleGenDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(optSampleGenDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.typeCombo = QtGui.QComboBox(optSampleGenDialog)
        self.typeCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.typeCombo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(optSampleGenDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ffactTable = QtGui.QTableWidget(self.page)
        self.ffactTable.setObjectName("ffactTable")
        self.ffactTable.setColumnCount(2)
        self.ffactTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ffactTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ffactTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.ffactTable)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.FileEdit = QtGui.QLineEdit(self.page_3)
        self.FileEdit.setObjectName("FileEdit")
        self.horizontalLayout_3.addWidget(self.FileEdit)
        self.FileButton = QtGui.QPushButton(self.page_3)
        self.FileButton.setObjectName("FileButton")
        self.horizontalLayout_3.addWidget(self.FileButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 400, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.okayButton = QtGui.QPushButton(optSampleGenDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okayButton.setIcon(icon)
        self.okayButton.setObjectName("okayButton")
        self.horizontalLayout.addWidget(self.okayButton)
        self.cancelButton = QtGui.QPushButton(optSampleGenDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(optSampleGenDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.typeCombo, QtCore.SIGNAL("currentIndexChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(optSampleGenDialog)

    def retranslateUi(self, optSampleGenDialog):
        optSampleGenDialog.setWindowTitle(QtGui.QApplication.translate("optSampleGenDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("optSampleGenDialog", "Sample Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCombo.setItemText(0, QtGui.QApplication.translate("optSampleGenDialog", "Full Factorial", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCombo.setItemText(1, QtGui.QApplication.translate("optSampleGenDialog", "Load From File", None, QtGui.QApplication.UnicodeUTF8))
        self.ffactTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("optSampleGenDialog", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.ffactTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("optSampleGenDialog", "Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("optSampleGenDialog", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.FileButton.setText(QtGui.QApplication.translate("optSampleGenDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.okayButton.setText(QtGui.QApplication.translate("optSampleGenDialog", "Okay", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("optSampleGenDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
