# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optimization\optSetupFrame_UI.ui'
#
# Created: Wed Feb 25 12:58:04 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_optSetupFrame(object):
    def setupUi(self, optSetupFrame):
        optSetupFrame.setObjectName("optSetupFrame")
        optSetupFrame.resize(1063, 777)
        optSetupFrame.setCursor(QtCore.Qt.ArrowCursor)
        optSetupFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        optSetupFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_9 = QtGui.QVBoxLayout(optSetupFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtGui.QTabWidget(optSetupFrame)
        self.tabWidget.setCursor(QtCore.Qt.PointingHandCursor)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.varForm = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varForm.sizePolicy().hasHeightForWidth())
        self.varForm.setSizePolicy(sizePolicy)
        self.varForm.setMinimumSize(QtCore.QSize(5, 5))
        self.varForm.setObjectName("varForm")
        self.varForm.setColumnCount(6)
        self.varForm.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.varForm.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.varForm.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.varForm.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.varForm.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.varForm.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.varForm.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.varForm)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addSampleButton = QtGui.QPushButton(self.tab_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addSampleButton.setIcon(icon)
        self.addSampleButton.setObjectName("addSampleButton")
        self.horizontalLayout_5.addWidget(self.addSampleButton)
        self.deleteSampleButton = QtGui.QPushButton(self.tab_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteSampleButton.setIcon(icon1)
        self.deleteSampleButton.setObjectName("deleteSampleButton")
        self.horizontalLayout_5.addWidget(self.deleteSampleButton)
        self.generateSamplesButton = QtGui.QPushButton(self.tab_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generateSamplesButton.setIcon(icon2)
        self.generateSamplesButton.setObjectName("generateSamplesButton")
        self.horizontalLayout_5.addWidget(self.generateSamplesButton)
        self.clearSamplesButton = QtGui.QPushButton(self.tab_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearSamplesButton.setIcon(icon3)
        self.clearSamplesButton.setObjectName("clearSamplesButton")
        self.horizontalLayout_5.addWidget(self.clearSamplesButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.sampleTable = QtGui.QTableWidget(self.tab_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 255, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.sampleTable.setPalette(palette)
        self.sampleTable.setAlternatingRowColors(True)
        self.sampleTable.setObjectName("sampleTable")
        self.sampleTable.setColumnCount(0)
        self.sampleTable.setRowCount(0)
        self.verticalLayout.addWidget(self.sampleTable)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.objTypeCombo = QtGui.QComboBox(self.tab_3)
        self.objTypeCombo.setMinimumSize(QtCore.QSize(300, 0))
        self.objTypeCombo.setObjectName("objTypeCombo")
        self.objTypeCombo.addItem("")
        self.objTypeCombo.addItem("")
        self.horizontalLayout_6.addWidget(self.objTypeCombo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.stackedWidget = QtGui.QStackedWidget(self.tab_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(5, 5))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fTable = QtGui.QTableWidget(self.groupBox)
        self.fTable.setMinimumSize(QtCore.QSize(5, 5))
        self.fTable.setObjectName("fTable")
        self.fTable.setColumnCount(3)
        self.fTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.fTable)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fAddButton = QtGui.QPushButton(self.groupBox)
        self.fAddButton.setMinimumSize(QtCore.QSize(0, 0))
        self.fAddButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.fAddButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fAddButton.setIcon(icon4)
        self.fAddButton.setIconSize(QtCore.QSize(16, 16))
        self.fAddButton.setFlat(False)
        self.fAddButton.setObjectName("fAddButton")
        self.verticalLayout_5.addWidget(self.fAddButton)
        self.fDelButton = QtGui.QPushButton(self.groupBox)
        self.fDelButton.setMinimumSize(QtCore.QSize(5, 5))
        self.fDelButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.fDelButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fDelButton.setIcon(icon5)
        self.fDelButton.setIconSize(QtCore.QSize(16, 16))
        self.fDelButton.setFlat(False)
        self.fDelButton.setObjectName("fDelButton")
        self.verticalLayout_5.addWidget(self.fDelButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(5, 5))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gTable = QtGui.QTableWidget(self.groupBox_2)
        self.gTable.setMinimumSize(QtCore.QSize(5, 5))
        self.gTable.setObjectName("gTable")
        self.gTable.setColumnCount(3)
        self.gTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.gTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.gTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.gTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_4.addWidget(self.gTable)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gAddButton = QtGui.QPushButton(self.groupBox_2)
        self.gAddButton.setMinimumSize(QtCore.QSize(0, 0))
        self.gAddButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.gAddButton.setText("")
        self.gAddButton.setIcon(icon4)
        self.gAddButton.setIconSize(QtCore.QSize(16, 16))
        self.gAddButton.setFlat(False)
        self.gAddButton.setObjectName("gAddButton")
        self.verticalLayout_2.addWidget(self.gAddButton)
        self.gDelButton = QtGui.QPushButton(self.groupBox_2)
        self.gDelButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.gDelButton.setText("")
        self.gDelButton.setIcon(icon5)
        self.gDelButton.setIconSize(QtCore.QSize(16, 16))
        self.gDelButton.setFlat(False)
        self.gDelButton.setObjectName("gDelButton")
        self.verticalLayout_2.addWidget(self.gDelButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.checkInputButton = QtGui.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.checkInputButton.setFont(font)
        self.checkInputButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.checkInputButton.setIcon(icon6)
        self.checkInputButton.setIconSize(QtCore.QSize(16, 16))
        self.checkInputButton.setFlat(False)
        self.checkInputButton.setObjectName("checkInputButton")
        self.horizontalLayout.addWidget(self.checkInputButton)
        self.vexButton = QtGui.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.vexButton.setFont(font)
        self.vexButton.setCursor(QtCore.Qt.PointingHandCursor)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.vexButton.setIcon(icon7)
        self.vexButton.setIconSize(QtCore.QSize(16, 16))
        self.vexButton.setFlat(False)
        self.vexButton.setObjectName("vexButton")
        self.horizontalLayout.addWidget(self.vexButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_4 = QtGui.QGroupBox(self.page_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_12.addWidget(self.plainTextEdit_2)
        self.customCodeEdit = QtGui.QPlainTextEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.customCodeEdit.setFont(font)
        self.customCodeEdit.setObjectName("customCodeEdit")
        self.verticalLayout_12.addWidget(self.customCodeEdit)
        self.verticalLayout_13.addWidget(self.groupBox_4)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_10.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.solverBox = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solverBox.sizePolicy().hasHeightForWidth())
        self.solverBox.setSizePolicy(sizePolicy)
        self.solverBox.setObjectName("solverBox")
        self.horizontalLayout_3.addWidget(self.solverBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.methodDescriptionBox = QtGui.QTextBrowser(self.groupBox_3)
        self.methodDescriptionBox.setObjectName("methodDescriptionBox")
        self.verticalLayout_4.addWidget(self.methodDescriptionBox)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setMinimumSize(QtCore.QSize(5, 5))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.solverOptionTable = QtGui.QTableWidget(self.groupBox_6)
        self.solverOptionTable.setMinimumSize(QtCore.QSize(5, 5))
        self.solverOptionTable.setObjectName("solverOptionTable")
        self.solverOptionTable.setColumnCount(3)
        self.solverOptionTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.solverOptionTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.solverOptionTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.solverOptionTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_8.addWidget(self.solverOptionTable)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.label_3.setBuddy(self.solverBox)

        self.retranslateUi(optSetupFrame)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.objTypeCombo, QtCore.SIGNAL("currentIndexChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(optSetupFrame)

    def retranslateUi(self, optSetupFrame):
        optSetupFrame.setWindowTitle(QtGui.QApplication.translate("optSetupFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.varForm.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("optSetupFrame", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.varForm.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("optSetupFrame", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.varForm.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("optSetupFrame", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.varForm.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("optSetupFrame", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.varForm.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("optSetupFrame", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.varForm.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("optSetupFrame", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("optSetupFrame", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.addSampleButton.setText(QtGui.QApplication.translate("optSetupFrame", "Add Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSampleButton.setText(QtGui.QApplication.translate("optSetupFrame", "Delete Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.generateSamplesButton.setText(QtGui.QApplication.translate("optSetupFrame", "Generate Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSamplesButton.setText(QtGui.QApplication.translate("optSetupFrame", "Clear Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("optSetupFrame", "Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.objTypeCombo.setItemText(0, QtGui.QApplication.translate("optSetupFrame", "Simple Python Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.objTypeCombo.setItemText(1, QtGui.QApplication.translate("optSetupFrame", "Custom Python", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("optSetupFrame", "Objective Function f(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.fTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("optSetupFrame", "Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.fTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("optSetupFrame", "Penalty Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.fTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("optSetupFrame", "Value for Failure", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("optSetupFrame", "Inequality Constraints g(x) <= 0", None, QtGui.QApplication.UnicodeUTF8))
        self.gTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("optSetupFrame", "Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.gTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("optSetupFrame", "Penalty Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.gTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("optSetupFrame", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.checkInputButton.setText(QtGui.QApplication.translate("optSetupFrame", "Check Input...", None, QtGui.QApplication.UnicodeUTF8))
        self.vexButton.setText(QtGui.QApplication.translate("optSetupFrame", "Variable Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("optSetupFrame", "Custom Python", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_2.setPlainText(QtGui.QApplication.translate("optSetupFrame", "Enter Python below to define an objective function.  The function should return three things the first is the objective function list.  This is a list to support multi-objective problems.  The other two items are only diagnostic, they are not use in any calulation.  The second item is a list of constraint violations.  The lst item is the constraint penalty.  In custom mode it is up to the user to apply constraint penalties.\n"
"\n"
"The arguments to the function are x, f, and fail.  The inputs and outputs of a flowsheet run are stored in x and f.  If sampling is used the first index is the sample index, and the second key is the node name.  If there is one sample only, the first key is the node a name.  The next key is the variables name, and the last index is the time step index.  The timestep index would usually be 0.  Fail is a boolean list.  It indicates if any flowsheet sample failed.\n"
"\n"
"Example:\n"
"\n"
"def objfunc(x, f, fail):\n"
"    # Simple example where the objective is just a flowsheet output\n"
"    if any(fail): #simulation failed to converge\n"
"        obj = [100000]\n"
"    else: #simulation successful\n"
"        obj = [f[\'Node\'][\'x\'][0]]\n"
"    return obj, [0], 0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("optSetupFrame", "Objective/Constraints", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("optSetupFrame", "Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("optSetupFrame", "Select Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("optSetupFrame", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("optSetupFrame", "Solver Options", None, QtGui.QApplication.UnicodeUTF8))
        self.solverOptionTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("optSetupFrame", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.solverOptionTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("optSetupFrame", "Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.solverOptionTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("optSetupFrame", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("optSetupFrame", "Solver", None, QtGui.QApplication.UnicodeUTF8))

import foqus_lib.gui.icons_rc as icons_rc
